//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate, NSString;

@interface QNTADAdPool : NSObject
{
    _Bool _inFilling;
    NSArray *_adsPool;
    unsigned long long _miniumAmount;
    NSString *_loid;
    NSDate *_serverLastDrainDate;
}

@property(retain, nonatomic) NSDate *serverLastDrainDate; // @synthesize serverLastDrainDate=_serverLastDrainDate;
@property(copy, nonatomic) NSString *loid; // @synthesize loid=_loid;
@property(nonatomic) unsigned long long miniumAmount; // @synthesize miniumAmount=_miniumAmount;
@property _Bool inFilling; // @synthesize inFilling=_inFilling;
@property(retain) NSArray *adsPool; // @synthesize adsPool=_adsPool;
- (void).cxx_destruct;
- (void)restoreAds:(id)arg1;
- (id)adsWithAmount:(unsigned long long)arg1 cur:(id)arg2;
- (id)cacheFileName;
- (void)p_onAppWillResignActiveNotification:(id)arg1;
- (void)p_onAppDidBecomeActiveActiveNotification:(id)arg1;
- (void)savePool;
- (void)restorePool;
- (void)checkFill;
- (void)cleanPool;
- (void)fillPool;
- (void)initPool;
- (void)dealloc;
- (id)initWithLoid:(id)arg1 miniumAmount:(unsigned long long)arg2;

@end

