//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface QSAIChatDogAnimationData : NSObject
{
    NSString *_jsonFilePath;
    NSDictionary *_jsonInfo;
    long long _loopTimes;
    long long _groupIndex;
}

@property(nonatomic) long long groupIndex; // @synthesize groupIndex=_groupIndex;
@property(nonatomic) long long loopTimes; // @synthesize loopTimes=_loopTimes;
@property(retain, nonatomic) NSDictionary *jsonInfo; // @synthesize jsonInfo=_jsonInfo;
@property(copy, nonatomic) NSString *jsonFilePath; // @synthesize jsonFilePath=_jsonFilePath;
- (void).cxx_destruct;

@end

