//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSAIChatReceivedBaseView.h"

#import "QSWebImageViewDelegate-Protocol.h"

@class NSString, QSWebImageView, UIImage, UIImageView, UIScrollView;

__attribute__((visibility("hidden")))
@interface QSAIChatReceivedImageView : QSAIChatReceivedBaseView <QSWebImageViewDelegate>
{
    QSWebImageView *_img;
    UIScrollView *_scrollView;
    UIImageView *_bottomRightImgView;
    UIImage *_normalImg;
    UIImage *_longImg;
    UIImageView *_shadowMaskImageView;
}

@property(retain, nonatomic) UIImageView *shadowMaskImageView; // @synthesize shadowMaskImageView=_shadowMaskImageView;
@property(retain, nonatomic) UIImage *longImg; // @synthesize longImg=_longImg;
@property(retain, nonatomic) UIImage *normalImg; // @synthesize normalImg=_normalImg;
@property(retain, nonatomic) UIImageView *bottomRightImgView; // @synthesize bottomRightImgView=_bottomRightImgView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) QSWebImageView *img; // @synthesize img=_img;
- (void).cxx_destruct;
- (void)actionRevealDetail:(id)arg1;
- (void)actionToNext:(id)arg1;
- (void)actionNO:(id)arg1;
- (void)actionYes:(id)arg1;
- (void)webImageViewDidFinishLoading:(id)arg1;
@property(readonly, nonatomic) UIImage *image; // @dynamic image;
- (void)imgTapped:(id)arg1;
- (void)updateWithModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

