//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSAIChatReceivedBaseView.h"

#import "QSWebImageViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableSet, NSString, UIImage, UIImageView, UITableView;

__attribute__((visibility("hidden")))
@interface QSAIChatReceivedImageTextView : QSAIChatReceivedBaseView <UITableViewDelegate, UITableViewDataSource, QSWebImageViewDelegate>
{
    UITableView *_tableView;
    UIImageView *_topMaskImageView;
    UIImageView *_shadowMaskImageView;
    NSMutableSet *_loadedImageSet;
    UIImage *_image2FullScreen;
}

@property(retain, nonatomic) UIImage *image2FullScreen; // @synthesize image2FullScreen=_image2FullScreen;
@property(retain, nonatomic) NSMutableSet *loadedImageSet; // @synthesize loadedImageSet=_loadedImageSet;
@property(retain, nonatomic) UIImageView *shadowMaskImageView; // @synthesize shadowMaskImageView=_shadowMaskImageView;
@property(retain, nonatomic) UIImageView *topMaskImageView; // @synthesize topMaskImageView=_topMaskImageView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)webImageViewDidFinishLoading:(id)arg1;
@property(readonly, nonatomic) UIImage *image; // @dynamic image;
- (void)actionToNext:(id)arg1;
- (void)actionNO:(id)arg1;
- (void)actionYes:(id)arg1;
- (void)updateWithModel:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

