//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSAIChatReceivedVideoListModel : QSModel
{
    NSString *_abstract;
    NSString *_cid;
    NSString *_vid;
    NSString *_pic;
    NSString *_title;
    NSString *_url;
}

+ (id)propertyNameFromParsedKey:(id)arg1;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *pic; // @synthesize pic=_pic;
@property(copy, nonatomic) NSString *vid; // @synthesize vid=_vid;
@property(copy, nonatomic) NSString *cid; // @synthesize cid=_cid;
@property(copy, nonatomic) NSString *abstract; // @synthesize abstract=_abstract;
- (void).cxx_destruct;

@end

