//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString, QSAIChatDogResponseBottomLink, QSAIChatDogResponseEmotion, QSAIChatReceivedMessage;

__attribute__((visibility("hidden")))
@interface QSAIChatDogResponse : QSModel
{
    _Bool _hasNext;
    _Bool _isSup;
    _Bool _guessCard;
    NSString *_groupId;
    NSString *_itemId;
    NSString *_title;
    QSAIChatReceivedMessage *_content;
    QSAIChatDogResponseBottomLink *_buttomLink;
    QSAIChatDogResponseEmotion *_emotion;
    NSString *_toast;
    NSString *_supId;
    NSString *_cardTip;
}

@property(retain, nonatomic) NSString *cardTip; // @synthesize cardTip=_cardTip;
@property(nonatomic) _Bool guessCard; // @synthesize guessCard=_guessCard;
@property(retain, nonatomic) NSString *supId; // @synthesize supId=_supId;
@property(nonatomic) _Bool isSup; // @synthesize isSup=_isSup;
@property(retain, nonatomic) NSString *toast; // @synthesize toast=_toast;
@property(retain, nonatomic) QSAIChatDogResponseEmotion *emotion; // @synthesize emotion=_emotion;
@property(retain, nonatomic) QSAIChatDogResponseBottomLink *buttomLink; // @synthesize buttomLink=_buttomLink;
@property(retain, nonatomic) QSAIChatReceivedMessage *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool hasNext; // @synthesize hasNext=_hasNext;
@property(retain, nonatomic) NSString *itemId; // @synthesize itemId=_itemId;
@property(retain, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
- (void).cxx_destruct;

@end

