//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSString, QSAIChatAttendNationInfo, QSAIChatShareItem;

__attribute__((visibility("hidden")))
@interface QSAIChatInitialConfigInfo : QSModel
{
    long long _askTipFreq;
    NSArray *_tabs;
    QSAIChatShareItem *_shareItem;
    NSString *_guide;
    QSAIChatAttendNationInfo *_attendNation;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) QSAIChatAttendNationInfo *attendNation; // @synthesize attendNation=_attendNation;
@property(retain, nonatomic) NSString *guide; // @synthesize guide=_guide;
@property(retain, nonatomic) QSAIChatShareItem *shareItem; // @synthesize shareItem=_shareItem;
@property(retain, nonatomic) NSArray *tabs; // @synthesize tabs=_tabs;
@property(nonatomic) long long askTipFreq; // @synthesize askTipFreq=_askTipFreq;
- (void).cxx_destruct;

@end

