//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSAIChatDogAnimationBaseModel.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface QSAIChatDogAnimationModelGroup : QSAIChatDogAnimationBaseModel
{
    NSArray *_subAnimations;
}

@property(retain, nonatomic) NSArray *subAnimations; // @synthesize subAnimations=_subAnimations;
- (void).cxx_destruct;
- (void)readJsonFileWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithGroupAction:(id)arg1;

@end

