//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSStatedData.h"

@class QSAIChatInitialConfigInfo;

__attribute__((visibility("hidden")))
@interface QSAIChatInitialConfigData : QSStatedData
{
}

@property(readonly, nonatomic) QSAIChatInitialConfigInfo *configInfo; // @dynamic configInfo;
- (void)resetWithResponseModel:(id)arg1;
- (id)identifier;
- (id)httpURLComponents;
- (double)cacheExpireTime;

@end

