//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString, QSAllTagsContentItem;

__attribute__((visibility("hidden")))
@interface QSAllTagsContentInfo : QSModel
{
    NSString *_followed;
    QSAllTagsContentItem *_recmdList;
    QSAllTagsContentItem *_allList;
}

@property(retain, nonatomic) QSAllTagsContentItem *allList; // @synthesize allList=_allList;
@property(retain, nonatomic) QSAllTagsContentItem *recmdList; // @synthesize recmdList=_recmdList;
@property(copy, nonatomic) NSString *followed; // @synthesize followed=_followed;
- (void).cxx_destruct;

@end

