//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface QSAllTagsContentItem : QSModel
{
    NSString *_ver;
    NSArray *_info;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) NSArray *info; // @synthesize info=_info;
@property(copy, nonatomic) NSString *ver; // @synthesize ver=_ver;
- (void).cxx_destruct;

@end

