//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSAppConfigNoticeInfo : QSModel
{
    _Bool _isNew;
    _Bool _isReaded;
    NSString *_url;
    NSString *_noticeId;
}

+ (id)propertyNameFromParsedKey:(id)arg1;
@property(nonatomic) _Bool isReaded; // @synthesize isReaded=_isReaded;
@property(nonatomic) _Bool isNew; // @synthesize isNew=_isNew;
@property(retain, nonatomic) NSString *noticeId; // @synthesize noticeId=_noticeId;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;

@end

