//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class QSApp;

__attribute__((visibility("hidden")))
@interface QSAppCell : UIButton
{
    QSApp *_app;
}

@property(retain, nonatomic) QSApp *app; // @synthesize app=_app;
- (void).cxx_destruct;
- (void)didMoveToSuperview;
- (id)urlFromApp:(id)arg1;
- (void)dealloc;
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;
- (struct CGRect)contentRectForBounds:(struct CGRect)arg1;
- (id)init;

@end

