//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSString, QSAppConfigAutoPlayInfo, QSAppConfigCheckModeInfo, QSAppConfigHttpDnsInfo, QSAppConfigNoticeInfo, QSAppConfigPlayerReportConfig;

__attribute__((visibility("hidden")))
@interface QSAppConfigInfo : QSModel
{
    _Bool _isSinaWeiboClose;
    _Bool _reportAPIStatus;
    _Bool _isWhiteList;
    _Bool _isLogUploadWhiteList;
    _Bool _isCheckMode;
    _Bool _wifiAd;
    _Bool _https;
    _Bool _testing;
    _Bool _backgroundIsShow;
    _Bool _aidog;
    QSAppConfigNoticeInfo *_notice;
    NSString *_license;
    NSString *_app_rmd;
    NSString *_app_description;
    NSString *_app_version;
    double _reportRate;
    NSString *_columnVersion;
    long long _showSKStoreReviewControllerNextTimeInterval;
    double _showSKStoreReviewControllerMaxPlayTime;
    QSAppConfigCheckModeInfo *_checkInfo;
    NSString *_tab2Url;
    QSAppConfigHttpDnsInfo *_httpDns;
    NSArray *_httpsHosts;
    QSAppConfigAutoPlayInfo *_autoPlayConfig;
    QSAppConfigPlayerReportConfig *_player_report_config;
    NSString *_defaultColumnId;
}

+ (id)propertyNameFromParsedKey:(id)arg1;
@property(nonatomic) _Bool aidog; // @synthesize aidog=_aidog;
@property(nonatomic) _Bool backgroundIsShow; // @synthesize backgroundIsShow=_backgroundIsShow;
@property(retain, nonatomic) NSString *defaultColumnId; // @synthesize defaultColumnId=_defaultColumnId;
@property(nonatomic) _Bool testing; // @synthesize testing=_testing;
@property(retain, nonatomic) QSAppConfigPlayerReportConfig *player_report_config; // @synthesize player_report_config=_player_report_config;
@property(retain, nonatomic) QSAppConfigAutoPlayInfo *autoPlayConfig; // @synthesize autoPlayConfig=_autoPlayConfig;
@property(retain, nonatomic) NSArray *httpsHosts; // @synthesize httpsHosts=_httpsHosts;
@property(retain, nonatomic) QSAppConfigHttpDnsInfo *httpDns; // @synthesize httpDns=_httpDns;
@property(copy, nonatomic) NSString *tab2Url; // @synthesize tab2Url=_tab2Url;
@property(nonatomic) _Bool https; // @synthesize https=_https;
@property(nonatomic) _Bool wifiAd; // @synthesize wifiAd=_wifiAd;
@property(retain, nonatomic) QSAppConfigCheckModeInfo *checkInfo; // @synthesize checkInfo=_checkInfo;
@property(nonatomic) double showSKStoreReviewControllerMaxPlayTime; // @synthesize showSKStoreReviewControllerMaxPlayTime=_showSKStoreReviewControllerMaxPlayTime;
@property(nonatomic) long long showSKStoreReviewControllerNextTimeInterval; // @synthesize showSKStoreReviewControllerNextTimeInterval=_showSKStoreReviewControllerNextTimeInterval;
@property(retain, nonatomic) NSString *columnVersion; // @synthesize columnVersion=_columnVersion;
@property(nonatomic) double reportRate; // @synthesize reportRate=_reportRate;
@property(retain, nonatomic) NSString *app_version; // @synthesize app_version=_app_version;
@property(retain, nonatomic) NSString *app_description; // @synthesize app_description=_app_description;
@property(retain, nonatomic) NSString *app_rmd; // @synthesize app_rmd=_app_rmd;
@property(retain, nonatomic) NSString *license; // @synthesize license=_license;
@property(nonatomic) _Bool isCheckMode; // @synthesize isCheckMode=_isCheckMode;
@property(nonatomic) _Bool isLogUploadWhiteList; // @synthesize isLogUploadWhiteList=_isLogUploadWhiteList;
@property(nonatomic) _Bool isWhiteList; // @synthesize isWhiteList=_isWhiteList;
@property(nonatomic) _Bool reportAPIStatus; // @synthesize reportAPIStatus=_reportAPIStatus;
@property(retain, nonatomic) QSAppConfigNoticeInfo *notice; // @synthesize notice=_notice;
@property(nonatomic) _Bool isSinaWeiboClose; // @synthesize isSinaWeiboClose=_isSinaWeiboClose;
- (void).cxx_destruct;

@end

