//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSStatedData.h"

@class QSAttendStartGuideTagContentInfo;

__attribute__((visibility("hidden")))
@interface QSAttendStartGuideTagData : QSStatedData
{
    QSAttendStartGuideTagContentInfo *_attendStartGuideTagContentInfo;
}

@property(retain, nonatomic) QSAttendStartGuideTagContentInfo *attendStartGuideTagContentInfo; // @synthesize attendStartGuideTagContentInfo=_attendStartGuideTagContentInfo;
- (void).cxx_destruct;
- (void)resetWithResponseModel:(id)arg1;
- (id)httpURLComponents;
- (id)identifier;

@end

