//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSViewController.h"

#import "QSBaseDataDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, NSString, QSAttendStartGuideTagData, QSAttendStartGuideTouchDelegateView, QSAttendTagBottomView, UINavigationBar, UINavigationItem, UIScrollView;
@protocol QSSplashManagerDelegate;

__attribute__((visibility("hidden")))
@interface QSAttendStartGuideViewController : QSViewController <QSBaseDataDelegate, UIScrollViewDelegate, UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
{
    id <QSSplashManagerDelegate> _splashDelegate;
    UINavigationBar *_topBar;
    UINavigationItem *_topNavigationItem;
    UIScrollView *_scrollView;
    QSAttendStartGuideTouchDelegateView *_touchDelegateView;
    NSMutableArray *_indicatorViews;
    NSMutableArray *_pageViews;
    QSAttendTagBottomView *_attendTagBottomView;
    QSAttendStartGuideTagData *_guideTagData;
    NSMutableArray *_waitingAttendTags;
    double _bottomSafeHeight;
}

@property(nonatomic) double bottomSafeHeight; // @synthesize bottomSafeHeight=_bottomSafeHeight;
@property(retain, nonatomic) NSMutableArray *waitingAttendTags; // @synthesize waitingAttendTags=_waitingAttendTags;
@property(retain, nonatomic) QSAttendStartGuideTagData *guideTagData; // @synthesize guideTagData=_guideTagData;
@property(retain, nonatomic) QSAttendTagBottomView *attendTagBottomView; // @synthesize attendTagBottomView=_attendTagBottomView;
@property(retain, nonatomic) NSMutableArray *pageViews; // @synthesize pageViews=_pageViews;
@property(retain, nonatomic) NSMutableArray *indicatorViews; // @synthesize indicatorViews=_indicatorViews;
@property(retain, nonatomic) QSAttendStartGuideTouchDelegateView *touchDelegateView; // @synthesize touchDelegateView=_touchDelegateView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UINavigationItem *topNavigationItem; // @synthesize topNavigationItem=_topNavigationItem;
@property(retain, nonatomic) UINavigationBar *topBar; // @synthesize topBar=_topBar;
@property(nonatomic) __weak id <QSSplashManagerDelegate> splashDelegate; // @synthesize splashDelegate=_splashDelegate;
- (void).cxx_destruct;
- (void)data:(id)arg1 didFinishLoadWithError:(id)arg2;
- (void)dataWillStartLoad:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)updatePageViewAlphaWithContentOffsetX:(double)arg1;
- (id)colorForContentOffsetX:(double)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)collectionBottomBtnPress:(id)arg1;
- (void)finished;
- (id)defaultEllipseRectImageWithSize:(struct CGSize)arg1 backgroundColor:(id)arg2;
- (void)removeObjectInWaitingAttendTagsWithTagId:(id)arg1;
- (_Bool)waitingAttendTagsContainsTagId:(id)arg1;
- (_Bool)isTagAttendedWithTagId:(id)arg1;
- (void)createPageViewWithIndex:(unsigned long long)arg1;
- (void)createIndicatorViews;
- (void)layoutUI;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (struct CGPoint)centerOfLoadingView;
- (id)newPageDescription;
- (void)shouldReloadSinceErrorPressed;
- (_Bool)isEmpty;
- (_Bool)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

