//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSStatedData.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface QSAttendedTagsData : QSStatedData
{
    NSArray *_followedArray;
}

@property(copy, nonatomic) NSArray *followedArray; // @synthesize followedArray=_followedArray;
- (void).cxx_destruct;
- (void)setFollowedArrayWithModel:(id)arg1;
- (void)resetWithResponseModel:(id)arg1;
- (id)httpURLComponents;
- (id)identifier;
- (double)cacheExpireTime;

@end

