//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface QSAttendTagItem : QSModel
{
    _Bool _hasMatch;
    NSString *_tagId;
    NSString *_icon;
    NSString *_name;
    NSDictionary *_jumpData;
    long long _type;
    NSString *_teamId;
}

+ (id)propertyNameFromParsedKey:(id)arg1;
+ (id)ignoredPropertiesWhenEncoding;
@property(copy, nonatomic) NSString *teamId; // @synthesize teamId=_teamId;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSDictionary *jumpData; // @synthesize jumpData=_jumpData;
@property(nonatomic) _Bool hasMatch; // @synthesize hasMatch=_hasMatch;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *tagId; // @synthesize tagId=_tagId;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (void)itemNeedUpdate:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithInfo:(id)arg1;
- (id)init;
@property(nonatomic) _Bool isAttended; // @dynamic isAttended;

@end

