//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface QSBalancePropsInfo : NSObject
{
    long long _prop_isFor;
    long long _prop_TYPE;
    NSString *_prop_ID;
    long long _prop_num;
}

@property(nonatomic) long long prop_num; // @synthesize prop_num=_prop_num;
@property(copy, nonatomic) NSString *prop_ID; // @synthesize prop_ID=_prop_ID;
@property(nonatomic) long long prop_TYPE; // @synthesize prop_TYPE=_prop_TYPE;
@property(nonatomic) long long prop_isFor; // @synthesize prop_isFor=_prop_isFor;
- (void).cxx_destruct;

@end

