//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface QSBackToVideoView : UIView
{
    _Bool _isLiving;
    UIImageView *_videoIcon;
    UILabel *_videoTip;
}

@property(nonatomic) _Bool isLiving; // @synthesize isLiving=_isLiving;
@property(retain, nonatomic) UILabel *videoTip; // @synthesize videoTip=_videoTip;
@property(retain, nonatomic) UIImageView *videoIcon; // @synthesize videoIcon=_videoIcon;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

