//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "QSStateMachineDelegate-Protocol.h"

@class NSDate, NSError, NSString, QSHTTPRequestOperation, QSModel, QSStateMachine;
@protocol QSHttpDataDelegate;

@interface QSBaseHttpData : NSObject <QSStateMachineDelegate>
{
    id <QSHttpDataDelegate> _delegate;
    QSModel *_model;
    QSHTTPRequestOperation *_request;
    NSDate *_lastUpdateTime;
    NSError *_error;
    QSStateMachine *_stateMachine;
    unsigned long long _retryIndex;
}

+ (_Bool)needRetryWithResponse:(id)arg1;
+ (long long)modelType;
+ (Class)modelClass;
@property(nonatomic) unsigned long long retryIndex; // @synthesize retryIndex=_retryIndex;
@property(retain, nonatomic) QSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSDate *lastUpdateTime; // @synthesize lastUpdateTime=_lastUpdateTime;
@property(retain, nonatomic) QSHTTPRequestOperation *request; // @synthesize request=_request;
@property(retain, nonatomic) QSModel *model; // @synthesize model=_model;
@property(nonatomic) __weak id <QSHttpDataDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)stateMachine:(id)arg1 triggerEventFailed:(id)arg2;
- (void)stateMachine:(id)arg1 enterStateFailed:(unsigned long long)arg2;
- (void)stateMachine:(id)arg1 eventDidHappen:(id)arg2;
- (void)stateMachine:(id)arg1 eventWillHappen:(id)arg2;
- (void)stateMachine:(id)arg1 leaveState:(unsigned long long)arg2;
- (void)stateMachine:(id)arg1 enterState:(unsigned long long)arg2;
- (void)refreshDataDidFinishWithError:(id)arg1;
- (void)retryReloadData;
- (void)reloadData;
- (void)start;
- (void)initStateMachine;
- (id)startRequestWithURLComponents:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)retryHttpURLComponents;
- (id)httpURLComponents;
- (void)clearDelegatesAndCancel;
- (void)clear;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

