//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "QSHorizontalTableViewDelegate-Protocol.h"

@class NSString, QSBasketBallGoalsSubCell, QSHorizontalTableView, QSMPMatchStateBasketballGoalsItem, QSMPMatchStateTeamInfo, QSMatchStateBasketballGoalsItem, QSMatchStateTeamInfo, UIImageView, UIView;

__attribute__((visibility("hidden")))
@interface QSBasketBallGoalsCell : UITableViewCell <QSHorizontalTableViewDelegate>
{
    _Bool _isDarkStyle;
    _Bool _extraTime;
    _Bool _firstUpdate;
    QSMatchStateBasketballGoalsItem *_data;
    QSMatchStateTeamInfo *_teamInfo;
    QSMPMatchStateBasketballGoalsItem *_MPData;
    QSMPMatchStateTeamInfo *_MPTeamInfo;
    QSHorizontalTableView *_scoreTable;
    QSBasketBallGoalsSubCell *_scoreHeader;
    QSBasketBallGoalsSubCell *_scoreTail;
    UIImageView *_leftMaskImageView;
    UIImageView *_rightMaskImageView;
    UIView *_bottomSeparator;
}

+ (double)heightWithModel:(id)arg1;
+ (double)height;
@property(retain, nonatomic) UIView *bottomSeparator; // @synthesize bottomSeparator=_bottomSeparator;
@property(retain, nonatomic) UIImageView *rightMaskImageView; // @synthesize rightMaskImageView=_rightMaskImageView;
@property(retain, nonatomic) UIImageView *leftMaskImageView; // @synthesize leftMaskImageView=_leftMaskImageView;
@property(nonatomic) _Bool firstUpdate; // @synthesize firstUpdate=_firstUpdate;
@property(retain, nonatomic) QSBasketBallGoalsSubCell *scoreTail; // @synthesize scoreTail=_scoreTail;
@property(retain, nonatomic) QSBasketBallGoalsSubCell *scoreHeader; // @synthesize scoreHeader=_scoreHeader;
@property(retain, nonatomic) QSHorizontalTableView *scoreTable; // @synthesize scoreTable=_scoreTable;
@property(nonatomic) _Bool extraTime; // @synthesize extraTime=_extraTime;
@property(retain, nonatomic) QSMPMatchStateTeamInfo *MPTeamInfo; // @synthesize MPTeamInfo=_MPTeamInfo;
@property(retain, nonatomic) QSMPMatchStateBasketballGoalsItem *MPData; // @synthesize MPData=_MPData;
@property(retain, nonatomic) QSMatchStateTeamInfo *teamInfo; // @synthesize teamInfo=_teamInfo;
@property(retain, nonatomic) QSMatchStateBasketballGoalsItem *data; // @synthesize data=_data;
@property(nonatomic) _Bool isDarkStyle; // @synthesize isDarkStyle=_isDarkStyle;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndex:(unsigned long long)arg2;
- (double)tableView:(id)arg1 widthForRowAtIndex:(unsigned long long)arg2;
- (double)widthForCell;
- (unsigned long long)numberOfRowsInTableView:(id)arg1;
- (void)lastTap:(id)arg1;
- (void)firstTap:(id)arg1;
- (void)layoutSubviews;
- (void)scrollViewDidScroll:(id)arg1;
- (void)updateMaskView;
- (void)update;
- (void)updateWithModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

