//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "QSFIFOPriorityQueueObjectProtocol-Protocol.h"

@class NSString, QSBusSystem;
@protocol OS_dispatch_queue;

@interface QSBusEvent : NSObject <QSFIFOPriorityQueueObjectProtocol>
{
    _Bool _invalid;
    _Bool _canReplacedByNew;
    NSString *_identifier;
    NSObject<OS_dispatch_queue> *_consumeQueue;
    QSBusSystem *_bus;
}

+ (id)defaultIdentifier;
+ (id)event;
@property(nonatomic) _Bool canReplacedByNew; // @synthesize canReplacedByNew=_canReplacedByNew;
@property(nonatomic) _Bool invalid; // @synthesize invalid=_invalid;
@property(nonatomic) __weak QSBusSystem *bus; // @synthesize bus=_bus;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *consumeQueue; // @synthesize consumeQueue=_consumeQueue;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)init;
- (void)bindWithBusSystem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long priority; // @dynamic priority;
@property(readonly) Class superclass;

@end

