//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSDataHandler.h"

#import "QSCleanCacheProtocol-Protocol.h"

@class NSString;

@interface QSCacheDataHandler : QSDataHandler <QSCleanCacheProtocol>
{
    NSString *_identifier;
    long long _type;
    double _cacheExpireTime;
}

+ (void)cleanCache;
+ (id)rootCachePath;
@property(nonatomic) double cacheExpireTime; // @synthesize cacheExpireTime=_cacheExpireTime;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)cachePath;
- (void)saveCache;
- (void)readCache;
- (void)handleData;
- (id)init;

@end

