//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSStatedData.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface QSChannelInfoManager : QSStatedData
{
    _Bool _needShowNew;
    _Bool _userAdjusted;
    NSString *_tips;
    NSString *_currentVersion;
    NSArray *_userColumns;
    NSArray *_firstColumns;
    NSString *_appVersion;
    CDUnknownBlockType _completion;
}

+ (id)sharedInstance;
+ (id)cachePath;
+ (id)rootCachePath;
+ (void)cleanCache;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) _Bool userAdjusted; // @synthesize userAdjusted=_userAdjusted;
@property(copy, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain, nonatomic) NSArray *firstColumns; // @synthesize firstColumns=_firstColumns;
@property(retain, nonatomic) NSArray *userColumns; // @synthesize userColumns=_userColumns;
@property(retain, nonatomic) NSString *currentVersion; // @synthesize currentVersion=_currentVersion;
@property(nonatomic) _Bool needShowNew; // @synthesize needShowNew=_needShowNew;
@property(copy, nonatomic) NSString *tips; // @synthesize tips=_tips;
- (void).cxx_destruct;
- (void)updateChannelsInfoWithCompletion:(CDUnknownBlockType)arg1;
- (void)refreshDataDidFinishWithError:(id)arg1;
- (void)resetWithResponseModel:(id)arg1;
- (id)httpURLComponents;
- (id)currentFollowedChannels;
- (void)readAllChannels;
- (void)saveCurrentFollowedChannels:(id)arg1;
- (void)newTagHasBeenShowed;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)willEnterForeground;
- (double)updateTimeInterval;
- (id)identifier;
- (id)allMatchChannels;
- (id)allChannels;

@end

