//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSStatedData.h"

#import "QSAutoUpdateProtocol-Protocol.h"

@class NSDictionary, NSString, QSComMatchDetailInfo;

__attribute__((visibility("hidden")))
@interface QSComMatchInfoData : QSStatedData <QSAutoUpdateProtocol>
{
    NSString *_mid;
    NSDictionary *_report;
}

+ (_Bool)cleanCacheWhenUserChanged;
@property(retain, nonatomic) NSDictionary *report; // @synthesize report=_report;
@property(copy, nonatomic) NSString *mid; // @synthesize mid=_mid;
- (void).cxx_destruct;
- (void)onAutoUpdate;
- (double)updateTimeInterval;
- (void)resetFromCacheObject:(id)arg1;
@property(readonly, nonatomic) QSComMatchDetailInfo *detailInfo;
- (void)resetWithResponseModel:(id)arg1;
- (id)httpURLComponents;
- (id)identifier;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

