//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QSAvatarView, UILabel;

__attribute__((visibility("hidden")))
@interface QSCommunityMainBar : UIView
{
    QSAvatarView *_avatarView;
    UILabel *_redPointLabel;
}

@property(retain, nonatomic) UILabel *redPointLabel; // @synthesize redPointLabel=_redPointLabel;
@property(retain, nonatomic) QSAvatarView *avatarView; // @synthesize avatarView=_avatarView;
- (void).cxx_destruct;
- (void)avatarViewDidTap:(id)arg1;
- (void)updateRedPointLabel;
- (void)updateAvatarView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

