//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface QSComListGroupItem : QSModel
{
    NSString *_group;
    NSArray *_modules;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) NSArray *modules; // @synthesize modules=_modules;
@property(copy, nonatomic) NSString *group; // @synthesize group=_group;
- (void).cxx_destruct;

@end

