//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSPagedData.h"

@class NSString, QSComTopicMoreRepliesInfo;

__attribute__((visibility("hidden")))
@interface QSComTopicMoreRepliesData : QSPagedData
{
    NSString *_tid;
    NSString *_rid;
}

+ (void)cleanLocalCacheWithTid:(id)arg1 rid:(id)arg2;
@property(copy, nonatomic) NSString *rid; // @synthesize rid=_rid;
@property(copy, nonatomic) NSString *tid; // @synthesize tid=_tid;
- (void).cxx_destruct;
- (void)addTempSubReplyItem:(id)arg1 toTargetReplyItem:(id)arg2;
- (_Bool)resetWithMoreModels:(id)arg1;
- (id)loadMoreHttpURLComponents;
- (void)resetWithResponseModel:(id)arg1;
- (id)httpURLComponents;
@property(readonly, nonatomic) __weak QSComTopicMoreRepliesInfo *info;
- (id)identifier;
- (void)removeSubReplyItemAtIndex:(long long)arg1;

@end

