//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "QSExpandingTextViewDelegate-Protocol.h"

@class QSTopicExpandingTextView;

__attribute__((visibility("hidden")))
@interface QSComPublishTitleCell : UITableViewCell <QSExpandingTextViewDelegate>
{
    QSTopicExpandingTextView *_mTitleView;
    CDUnknownBlockType _comPublishTitleBeginEditing;
    CDUnknownBlockType _comPublishTitleDidChange;
    CDUnknownBlockType _comPublishTitleDidChangeHeight;
    CDUnknownBlockType _comPublishTitleExceedMaxLen;
    CDUnknownBlockType _comPublishTitleGetMaxLen;
}

+ (double)cellHeight;
@property(copy, nonatomic) CDUnknownBlockType comPublishTitleGetMaxLen; // @synthesize comPublishTitleGetMaxLen=_comPublishTitleGetMaxLen;
@property(copy, nonatomic) CDUnknownBlockType comPublishTitleExceedMaxLen; // @synthesize comPublishTitleExceedMaxLen=_comPublishTitleExceedMaxLen;
@property(copy, nonatomic) CDUnknownBlockType comPublishTitleDidChangeHeight; // @synthesize comPublishTitleDidChangeHeight=_comPublishTitleDidChangeHeight;
@property(copy, nonatomic) CDUnknownBlockType comPublishTitleDidChange; // @synthesize comPublishTitleDidChange=_comPublishTitleDidChange;
@property(copy, nonatomic) CDUnknownBlockType comPublishTitleBeginEditing; // @synthesize comPublishTitleBeginEditing=_comPublishTitleBeginEditing;
@property(retain, nonatomic) QSTopicExpandingTextView *mTitleView; // @synthesize mTitleView=_mTitleView;
- (void).cxx_destruct;
- (void)expandingTextView:(id)arg1 didChangeHeight:(float)arg2;
- (void)expandingTextViewDidChange:(id)arg1;
- (_Bool)expandingTextViewShouldReturn:(id)arg1;
- (_Bool)expandingTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)expandingTextViewShouldBeginEditing:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

