//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray, NSMutableArray, QSComIconView, UIScrollView;

__attribute__((visibility("hidden")))
@interface QSCommMyFollowTableViewCell : UITableViewCell
{
    _Bool _showLogin;
    CDUnknownBlockType _touchBlock;
    UIScrollView *_contentScrollView;
    NSMutableArray *_icons;
    NSArray *_modelList;
    QSComIconView *_addIcon;
}

+ (double)cellHeight;
@property(retain, nonatomic) QSComIconView *addIcon; // @synthesize addIcon=_addIcon;
@property(retain, nonatomic) NSArray *modelList; // @synthesize modelList=_modelList;
@property(retain, nonatomic) NSMutableArray *icons; // @synthesize icons=_icons;
@property(retain, nonatomic) UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(nonatomic) _Bool showLogin; // @synthesize showLogin=_showLogin;
@property(copy, nonatomic) CDUnknownBlockType touchBlock; // @synthesize touchBlock=_touchBlock;
- (void).cxx_destruct;
- (void)touchOutAction:(id)arg1;
- (void)touchDownAction:(id)arg1;
- (void)iconTouchAction:(id)arg1;
- (void)layoutSubviews;
- (void)updateWithModel:(id)arg1;
- (void)iconAddTouchAction:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

