//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSComTopicDetailReplyVideoContentCell.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface QSComTopicDetailLastReplyVideoContentCell : QSComTopicDetailReplyVideoContentCell
{
    UIView *_separatorLine;
}

+ (double)cellHeightWithContentItem:(id)arg1 isReply:(_Bool)arg2;
@property(retain, nonatomic) UIView *separatorLine; // @synthesize separatorLine=_separatorLine;
- (void).cxx_destruct;
- (void)update;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

