//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSComPublishVideoConfigContentItem : QSModel
{
    NSString *_limitedContent;
    long long _userVideoUploadStatus;
}

@property(nonatomic) long long userVideoUploadStatus; // @synthesize userVideoUploadStatus=_userVideoUploadStatus;
@property(copy, nonatomic) NSString *limitedContent; // @synthesize limitedContent=_limitedContent;
- (void).cxx_destruct;

@end

