//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSComTopicDetailContentCell.h"

@class QSComTopicDetailVoteQuestionItem, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface QSComTopicDetailVoteQuestionTitleCell : QSComTopicDetailContentCell
{
    QSComTopicDetailVoteQuestionItem *_questionItem;
    UILabel *_titleLabel;
    UIView *_topBorderView;
    UIView *_leftBorderView;
    UIView *_rightBorderView;
}

+ (double)cellHeightWithContentItem:(id)arg1;
@property(retain, nonatomic) UIView *rightBorderView; // @synthesize rightBorderView=_rightBorderView;
@property(retain, nonatomic) UIView *leftBorderView; // @synthesize leftBorderView=_leftBorderView;
@property(retain, nonatomic) UIView *topBorderView; // @synthesize topBorderView=_topBorderView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) QSComTopicDetailVoteQuestionItem *questionItem; // @synthesize questionItem=_questionItem;
- (void).cxx_destruct;
- (void)update;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

