//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIActivityIndicatorView, UIButton, UILabel;
@protocol QSCommunityMainLoadingCellDelegate;

__attribute__((visibility("hidden")))
@interface QSCommunityMainLoadingCell : UITableViewCell
{
    id <QSCommunityMainLoadingCellDelegate> _delegate;
    long long _status;
    UILabel *_tipLabel;
    UIActivityIndicatorView *_aiView;
    UIButton *_errorButton;
}

+ (double)heightWithStatus:(long long)arg1 curHeight:(double)arg2;
@property(retain, nonatomic) UIButton *errorButton; // @synthesize errorButton=_errorButton;
@property(retain, nonatomic) UIActivityIndicatorView *aiView; // @synthesize aiView=_aiView;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(nonatomic) __weak id <QSCommunityMainLoadingCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didClickedErrorBtn:(id)arg1;
- (void)updateWithHeight:(double)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

