//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class AVPlayer, AVPlayerLayer, NSURL, UIButton, UIImage, UIImageView, UIVisualEffectView;

__attribute__((visibility("hidden")))
@interface QSComPublishPlayVideoViewController : UIViewController
{
    _Bool _wantToDeleteFile;
    NSURL *_fileURL;
    CDUnknownBlockType _dismissWithVideoFileURL;
    UIImage *_image;
    CDUnknownBlockType _dismissWithImage;
    AVPlayer *_player;
    AVPlayerLayer *_playerLayer;
    UIImageView *_imageView;
    UIButton *_finishBtn;
    UIButton *_backBtn;
    UIVisualEffectView *_backBtnVisualEffectView;
}

@property(retain, nonatomic) UIVisualEffectView *backBtnVisualEffectView; // @synthesize backBtnVisualEffectView=_backBtnVisualEffectView;
@property(retain, nonatomic) UIButton *backBtn; // @synthesize backBtn=_backBtn;
@property(retain, nonatomic) UIButton *finishBtn; // @synthesize finishBtn=_finishBtn;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) AVPlayerLayer *playerLayer; // @synthesize playerLayer=_playerLayer;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(copy, nonatomic) CDUnknownBlockType dismissWithImage; // @synthesize dismissWithImage=_dismissWithImage;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) CDUnknownBlockType dismissWithVideoFileURL; // @synthesize dismissWithVideoFileURL=_dismissWithVideoFileURL;
@property(nonatomic) _Bool wantToDeleteFile; // @synthesize wantToDeleteFile=_wantToDeleteFile;
@property(retain, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
- (void).cxx_destruct;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)updateUIWithSize:(struct CGSize)arg1;
- (void)backBtnClicked:(id)arg1;
- (void)finishBtnClicked:(id)arg1;
- (void)routeChange:(id)arg1;
- (void)willEnterForeground:(id)arg1;
- (void)playbackFinished:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (_Bool)prefersStatusBarHidden;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

