//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface QSCommunityRootInfo : QSModel
{
    NSString *_position;
    NSArray *_tabs;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) NSArray *tabs; // @synthesize tabs=_tabs;
@property(copy, nonatomic) NSString *position; // @synthesize position=_position;
- (void).cxx_destruct;

@end

