//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface QSCommentOperationData : NSObject
{
}

+ (void)ignoreCommentUser:(id)arg1 target:(id)arg2 uidex:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)banCommentUser:(id)arg1 target:(id)arg2 uidex:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)deleteComment:(id)arg1 target:(id)arg2 uidex:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)reportComment:(id)arg1 target:(id)arg2 uidex:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)reportComment:(id)arg1 target:(id)arg2 uidex:(id)arg3 banType:(long long)arg4 completion:(CDUnknownBlockType)arg5;
+ (void)replyComment:(id)arg1 withTarget:(id)arg2 andContent:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)supportComment:(id)arg1 withTarget:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)addCommentWithContent:(id)arg1 andImageInfo:(id)arg2 toTarget:(id)arg3 completion:(CDUnknownBlockType)arg4;

@end

