//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSPagedData.h"

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface QSCommunityMainNewActData : QSPagedData
{
    _Bool _innerCanLoadMore;
    long long _listTypeIndex;
    NSMutableArray *_topics;
    NSString *_lastId;
}

+ (_Bool)cleanCacheWhenUserChanged;
@property(nonatomic) _Bool innerCanLoadMore; // @synthesize innerCanLoadMore=_innerCanLoadMore;
@property(retain, nonatomic) NSString *lastId; // @synthesize lastId=_lastId;
@property(retain, nonatomic) NSMutableArray *topics; // @synthesize topics=_topics;
@property(nonatomic) long long listTypeIndex; // @synthesize listTypeIndex=_listTypeIndex;
- (void).cxx_destruct;
- (void)deleteTopicItem:(id)arg1;
- (_Bool)isEmpty;
- (_Bool)resetWithMoreModels:(id)arg1;
- (void)resetWithResponseModel:(id)arg1;
- (id)loadMoreHttpURLComponents;
- (id)httpURLComponents;
- (void)setListTypeForParams:(id)arg1;
- (id)identifier;
- (void)clearOnlyCurTopics;
- (_Bool)canLoadMore;
- (void)emptyMemoryCache;
- (void)resetFromCacheObject:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (double)cacheExpireTime;

@end

