//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSDictionary, NSString, UIImage;

__attribute__((visibility("hidden")))
@interface QSDailyNewsDataNewsItem : QSModel
{
    long long _showType;
    NSString *_title;
    NSString *_pic;
    NSString *_vid;
    UIImage *_image;
    NSDictionary *_jumpData;
}

+ (id)ignoredPropertiesWhenEncoding;
@property(retain, nonatomic) NSDictionary *jumpData; // @synthesize jumpData=_jumpData;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *vid; // @synthesize vid=_vid;
@property(retain, nonatomic) NSString *pic; // @synthesize pic=_pic;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long showType; // @synthesize showType=_showType;
- (void).cxx_destruct;

@end

