//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "QSMatchPushFocusMatchesVideoCollectionMultipleButtonViewDelegate-Protocol.h"

@class NSMutableArray, NSString, QSDailyNewsDataNodeItem, QSMatchPushFocusMatchesVideoCollectionMultipleButtonView, QSMatchPushFocusMatchesVideoCollectionVideoView, QSViewController, QSWebImageView, UILabel, UIView;
@protocol QSDailyNewsContentCellDelegate;

__attribute__((visibility("hidden")))
@interface QSDailyNewsContentCell : UITableViewCell <QSMatchPushFocusMatchesVideoCollectionMultipleButtonViewDelegate>
{
    id <QSDailyNewsContentCellDelegate> _delegate;
    QSViewController *_viewController;
    QSDailyNewsDataNodeItem *_item;
    UILabel *_titleLabel;
    UILabel *_timeLabel;
    QSWebImageView *_pictureView;
    QSMatchPushFocusMatchesVideoCollectionVideoView *_videoView;
    UILabel *_contentLabel;
    QSMatchPushFocusMatchesVideoCollectionMultipleButtonView *_multipleButtonView;
    NSMutableArray *_newsButtonArray;
    UIView *_viewAboveVideoView;
    UIView *_viewBelowVideoView;
    UIView *_line1;
    UIView *_line2;
}

+ (double)heightForContent:(id)arg1;
+ (double)videoHeightOfWidth:(double)arg1;
+ (struct CGRect)contentRect:(id)arg1;
+ (id)contentAttributedString:(id)arg1;
+ (id)createNewsButton:(id)arg1;
@property(retain, nonatomic) UIView *line2; // @synthesize line2=_line2;
@property(retain, nonatomic) UIView *line1; // @synthesize line1=_line1;
@property(retain, nonatomic) UIView *viewBelowVideoView; // @synthesize viewBelowVideoView=_viewBelowVideoView;
@property(retain, nonatomic) UIView *viewAboveVideoView; // @synthesize viewAboveVideoView=_viewAboveVideoView;
@property(retain, nonatomic) NSMutableArray *newsButtonArray; // @synthesize newsButtonArray=_newsButtonArray;
@property(retain, nonatomic) QSMatchPushFocusMatchesVideoCollectionMultipleButtonView *multipleButtonView; // @synthesize multipleButtonView=_multipleButtonView;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) QSMatchPushFocusMatchesVideoCollectionVideoView *videoView; // @synthesize videoView=_videoView;
@property(retain, nonatomic) QSWebImageView *pictureView; // @synthesize pictureView=_pictureView;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak QSDailyNewsDataNodeItem *item; // @synthesize item=_item;
@property(nonatomic) __weak QSViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) __weak id <QSDailyNewsContentCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)pushFocusMatchesVideoCollectionMultipleButtonViewDidPressThirdButton:(id)arg1;
- (void)pushFocusMatchesVideoCollectionMultipleButtonViewDidPressSecondButton:(id)arg1;
- (void)pushFocusMatchesVideoCollectionMultipleButtonViewDidPressfirstButton:(id)arg1;
- (void)onNewsButtonClicked:(id)arg1;
- (void)videoCollectionCellClicked:(id)arg1;
- (void)videoCellDisappearShouldSavePossibleExistedVideoCurrentDuration;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

