//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMapTable, NSRecursiveLock;

@interface QSDatabaseManagement : NSObject
{
    NSMapTable *_connectedDatabase;
    NSRecursiveLock *_lock;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMapTable *connectedDatabase; // @synthesize connectedDatabase=_connectedDatabase;
- (void).cxx_destruct;
- (id)databaseWithPath:(id)arg1;
- (void)addDatabase:(id)arg1;
- (void)removeDatabase:(id)arg1;
- (id)init;

@end

