//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSPredicate, NSString;

@interface QSDBTableQueryCommand : NSObject
{
    NSArray *_queriedKeys;
    NSPredicate *_filter;
    NSString *_groupedKey;
    NSArray *_sortDescriptors;
    unsigned long long _limit;
    unsigned long long _offset;
    NSString *_moreSQL;
}

+ (id)queryCommandWithQueriedKeys:(id)arg1 filter:(id)arg2 groupedKey:(id)arg3 sortDescriptors:(id)arg4 limit:(unsigned long long)arg5 offset:(unsigned long long)arg6;
@property(retain, nonatomic) NSString *moreSQL; // @synthesize moreSQL=_moreSQL;
@property(nonatomic) unsigned long long offset; // @synthesize offset=_offset;
@property(nonatomic) unsigned long long limit; // @synthesize limit=_limit;
@property(retain, nonatomic) NSArray *sortDescriptors; // @synthesize sortDescriptors=_sortDescriptors;
@property(retain, nonatomic) NSString *groupedKey; // @synthesize groupedKey=_groupedKey;
@property(retain, nonatomic) NSPredicate *filter; // @synthesize filter=_filter;
@property(retain, nonatomic) NSArray *queriedKeys; // @synthesize queriedKeys=_queriedKeys;
- (void).cxx_destruct;
- (id)sqlStringWithTableName:(id)arg1;

@end

