//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableDictionary, UIButton;
@protocol QSDebugConsoleActionDelegate;

__attribute__((visibility("hidden")))
@interface QSDebugConsoleNavigationBar : UIView
{
    id <QSDebugConsoleActionDelegate> _actionDelegate;
    UIButton *_closeButton;
    UIButton *_settingButton;
    UIButton *_toggleButton;
    NSMutableDictionary *_infoLables;
    NSMutableDictionary *_infoItems;
}

@property(retain, nonatomic) NSMutableDictionary *infoItems; // @synthesize infoItems=_infoItems;
@property(retain, nonatomic) NSMutableDictionary *infoLables; // @synthesize infoLables=_infoLables;
@property(retain, nonatomic) UIButton *toggleButton; // @synthesize toggleButton=_toggleButton;
@property(retain, nonatomic) UIButton *settingButton; // @synthesize settingButton=_settingButton;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) __weak id <QSDebugConsoleActionDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
- (void).cxx_destruct;
- (void)toggleButtonPressed;
- (void)settingButtonPressed;
- (void)closeButtonPressed;
- (void)itemButtonPressed:(id)arg1;
- (void)updateInfoItem:(id)arg1;
- (void)cleanAllInfoItems;
- (void)cleanInfoItem:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

