//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIWindow.h>

@class QSDebugConsoleView;

__attribute__((visibility("hidden")))
@interface QSDebugConsoleWindow : UIWindow
{
    QSDebugConsoleView *_consoleView;
}

@property(retain, nonatomic) QSDebugConsoleView *consoleView; // @synthesize consoleView=_consoleView;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)dismissConsoleView;
- (void)showConsoleView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

