//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSString, QSDebugConsoleFilterOption, UIButton, UITableView;
@protocol QSDebugConsoleActionDelegate;

__attribute__((visibility("hidden")))
@interface QSDebugConsoleSettingView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    id <QSDebugConsoleActionDelegate> _actionDelegate;
    UITableView *_tableView;
    UIButton *_closeButton;
    QSDebugConsoleFilterOption *_option;
    NSArray *_categories;
    NSArray *_logTypes;
}

@property(retain, nonatomic) NSArray *logTypes; // @synthesize logTypes=_logTypes;
@property(retain, nonatomic) NSArray *categories; // @synthesize categories=_categories;
@property(retain, nonatomic) QSDebugConsoleFilterOption *option; // @synthesize option=_option;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <QSDebugConsoleActionDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
- (void).cxx_destruct;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)closeButtonPressed;
- (void)layoutSubviews;
- (id)initWithOption:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

