//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface QSDebugConsoleLogItem : NSObject
{
    unsigned long long _type;
    NSString *_category;
    NSString *_content;
    NSString *_detailContent;
    double _createTime;
}

@property(nonatomic) double createTime; // @synthesize createTime=_createTime;
@property(copy, nonatomic) NSString *detailContent; // @synthesize detailContent=_detailContent;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *category; // @synthesize category=_category;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (id)init;
@property(nonatomic) double cellHeight;
@property(retain, nonatomic) NSString *cellContent;

@end

