//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSRegularExpression;

__attribute__((visibility("hidden")))
@interface QSEmotions : NSObject
{
    NSArray *_allEmotions;
    NSRegularExpression *_emotionsRegex;
    unsigned long long _maxEmotionTextLength;
    NSDictionary *_allEmotionInfo;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSDictionary *allEmotionInfo; // @synthesize allEmotionInfo=_allEmotionInfo;
@property(nonatomic) unsigned long long maxEmotionTextLength; // @synthesize maxEmotionTextLength=_maxEmotionTextLength;
@property(retain, nonatomic) NSRegularExpression *emotionsRegex; // @synthesize emotionsRegex=_emotionsRegex;
@property(retain, nonatomic) NSArray *allEmotions; // @synthesize allEmotions=_allEmotions;
- (void).cxx_destruct;
- (id)emotionItemWithName:(id)arg1;
- (id)init;

@end

