//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSMutableArray, QSMatchDetailFootballFormation, QSMatchDetailInfo, QSMatchStateTeamInfo, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface QSFootballFormationCell : UITableViewCell
{
    QSMatchDetailFootballFormation *_model;
    QSMatchDetailInfo *_detailInfo;
    QSMatchStateTeamInfo *_teamInfo;
    UIImageView *_fieldBgImageView;
    NSMutableArray *_homeStarters;
    NSMutableArray *_awayStarters;
    UILabel *_homeTeamNameLabel;
    UILabel *_awayTeamNameLabel;
    UILabel *_homeTeamFormationLabel;
    UILabel *_awayTeamFormationLabel;
    UILabel *_benchesTitle;
    NSMutableArray *_benchesRows;
}

+ (double)heightWithModel:(id)arg1;
@property(retain, nonatomic) NSMutableArray *benchesRows; // @synthesize benchesRows=_benchesRows;
@property(retain, nonatomic) UILabel *benchesTitle; // @synthesize benchesTitle=_benchesTitle;
@property(retain, nonatomic) UILabel *awayTeamFormationLabel; // @synthesize awayTeamFormationLabel=_awayTeamFormationLabel;
@property(retain, nonatomic) UILabel *homeTeamFormationLabel; // @synthesize homeTeamFormationLabel=_homeTeamFormationLabel;
@property(retain, nonatomic) UILabel *awayTeamNameLabel; // @synthesize awayTeamNameLabel=_awayTeamNameLabel;
@property(retain, nonatomic) UILabel *homeTeamNameLabel; // @synthesize homeTeamNameLabel=_homeTeamNameLabel;
@property(retain, nonatomic) NSMutableArray *awayStarters; // @synthesize awayStarters=_awayStarters;
@property(retain, nonatomic) NSMutableArray *homeStarters; // @synthesize homeStarters=_homeStarters;
@property(retain, nonatomic) UIImageView *fieldBgImageView; // @synthesize fieldBgImageView=_fieldBgImageView;
@property(retain, nonatomic) QSMatchStateTeamInfo *teamInfo; // @synthesize teamInfo=_teamInfo;
@property(retain, nonatomic) QSMatchDetailInfo *detailInfo; // @synthesize detailInfo=_detailInfo;
@property(retain, nonatomic) QSMatchDetailFootballFormation *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)update;
- (struct CGPoint)pointFromPosString:(id)arg1 isHome:(_Bool)arg2;
- (id)formationDisplay:(id)arg1;
- (unsigned long long)maxPlayerPerRow:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

