//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QSFootballFormationBubble, QSMatchDetailFootballFormationPlayer, QSWebImageViewEx, UIColor, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface QSFootballFormationStartPlayerView : UIView
{
    QSMatchDetailFootballFormationPlayer *_player;
    UIImageView *_playerImageView;
    UILabel *_playerLabel;
    UIImageView *_shadowImageView;
    UILabel *_nameLabel;
    UIColor *_color;
    QSWebImageViewEx *_redYellowIcon1;
    QSWebImageViewEx *_redYellowIcon2;
    QSFootballFormationBubble *_exchangeBubble;
    QSFootballFormationBubble *_goalBubble;
    QSFootballFormationBubble *_wulongBubble;
    QSFootballFormationBubble *_shootoutBubble;
}

@property(retain, nonatomic) QSFootballFormationBubble *shootoutBubble; // @synthesize shootoutBubble=_shootoutBubble;
@property(retain, nonatomic) QSFootballFormationBubble *wulongBubble; // @synthesize wulongBubble=_wulongBubble;
@property(retain, nonatomic) QSFootballFormationBubble *goalBubble; // @synthesize goalBubble=_goalBubble;
@property(retain, nonatomic) QSFootballFormationBubble *exchangeBubble; // @synthesize exchangeBubble=_exchangeBubble;
@property(retain, nonatomic) QSWebImageViewEx *redYellowIcon2; // @synthesize redYellowIcon2=_redYellowIcon2;
@property(retain, nonatomic) QSWebImageViewEx *redYellowIcon1; // @synthesize redYellowIcon1=_redYellowIcon1;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *shadowImageView; // @synthesize shadowImageView=_shadowImageView;
@property(retain, nonatomic) UILabel *playerLabel; // @synthesize playerLabel=_playerLabel;
@property(retain, nonatomic) UIImageView *playerImageView; // @synthesize playerImageView=_playerImageView;
@property(retain, nonatomic) QSMatchDetailFootballFormationPlayer *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (void)update;
- (void)startPlayerTaped:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

