//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSMonitorData.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSFrameRateMonitorData : QSMonitorData
{
    float _rate;
    NSString *_report;
}

@property(copy, nonatomic) NSString *report; // @synthesize report=_report;
@property(nonatomic) float rate; // @synthesize rate=_rate;
- (void).cxx_destruct;

@end

