//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSBaseMatchLivePropsListView.h"

#import "QSFullScreenMatchLivePropsItemViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, NSString, QSMatchLivePropsListItem, UIActivityIndicatorView, UIButton, UIControl, UIImageView, UILabel, UIPageControl, UIScrollView, UIView;
@protocol QSFullScreenLiveChatPropsListViewDelegate;

__attribute__((visibility("hidden")))
@interface QSFullScreenMatchLivePropsListView : QSBaseMatchLivePropsListView <QSFullScreenMatchLivePropsItemViewDelegate, UIScrollViewDelegate>
{
    _Bool _buyButtonIsBusy;
    UIView *_bgView;
    UIView *_wrapperView;
    UIView *_contentView;
    UIScrollView *_propsScrollView;
    UIPageControl *_pageControl;
    UIView *_walletView;
    UIImageView *_kbIconView;
    UILabel *_kbLabel;
    UIImageView *_diamondIconView;
    UILabel *_diamondLabel;
    UIControl *_walletControl;
    UIButton *_buyButton;
    UIActivityIndicatorView *_buyButtonBusyView;
    UIActivityIndicatorView *_activityView;
    UILabel *_errorLabel;
    UIImageView *_emptyView;
    UIView *_kbNotEnoughErrorView;
    UILabel *_kbNotEnoughErrorLabel;
    UIButton *_kbNotEnoughErrorCancelBtn;
    UIButton *_kbNotEnoughErrorOKBtn;
    UIButton *_kbNotEnoughErrorCloseBtn;
    NSMutableArray *_propsItemViewArray;
    long long _currentPageIndex;
    unsigned long long _totalPage;
    QSMatchLivePropsListItem *_selectedProps;
    NSString *_errorText;
}

+ (int)propsNumOfOnePage;
+ (double)propsListContentViewHeight;
+ (double)propsListWalletHeight;
+ (double)propsListScrollViewHeight;
@property(copy, nonatomic) NSString *errorText; // @synthesize errorText=_errorText;
@property(retain, nonatomic) QSMatchLivePropsListItem *selectedProps; // @synthesize selectedProps=_selectedProps;
@property(nonatomic) unsigned long long totalPage; // @synthesize totalPage=_totalPage;
@property(nonatomic) long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(retain, nonatomic) NSMutableArray *propsItemViewArray; // @synthesize propsItemViewArray=_propsItemViewArray;
@property(retain, nonatomic) UIButton *kbNotEnoughErrorCloseBtn; // @synthesize kbNotEnoughErrorCloseBtn=_kbNotEnoughErrorCloseBtn;
@property(retain, nonatomic) UIButton *kbNotEnoughErrorOKBtn; // @synthesize kbNotEnoughErrorOKBtn=_kbNotEnoughErrorOKBtn;
@property(retain, nonatomic) UIButton *kbNotEnoughErrorCancelBtn; // @synthesize kbNotEnoughErrorCancelBtn=_kbNotEnoughErrorCancelBtn;
@property(retain, nonatomic) UILabel *kbNotEnoughErrorLabel; // @synthesize kbNotEnoughErrorLabel=_kbNotEnoughErrorLabel;
@property(retain, nonatomic) UIView *kbNotEnoughErrorView; // @synthesize kbNotEnoughErrorView=_kbNotEnoughErrorView;
@property(retain, nonatomic) UIImageView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) UILabel *errorLabel; // @synthesize errorLabel=_errorLabel;
@property(retain, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView=_activityView;
@property(retain, nonatomic) UIActivityIndicatorView *buyButtonBusyView; // @synthesize buyButtonBusyView=_buyButtonBusyView;
@property(retain, nonatomic) UIButton *buyButton; // @synthesize buyButton=_buyButton;
@property(retain, nonatomic) UIControl *walletControl; // @synthesize walletControl=_walletControl;
@property(retain, nonatomic) UILabel *diamondLabel; // @synthesize diamondLabel=_diamondLabel;
@property(retain, nonatomic) UIImageView *diamondIconView; // @synthesize diamondIconView=_diamondIconView;
@property(retain, nonatomic) UILabel *kbLabel; // @synthesize kbLabel=_kbLabel;
@property(retain, nonatomic) UIImageView *kbIconView; // @synthesize kbIconView=_kbIconView;
@property(retain, nonatomic) UIView *walletView; // @synthesize walletView=_walletView;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIScrollView *propsScrollView; // @synthesize propsScrollView=_propsScrollView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *wrapperView; // @synthesize wrapperView=_wrapperView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) _Bool buyButtonIsBusy; // @synthesize buyButtonIsBusy=_buyButtonIsBusy;
- (void).cxx_destruct;
- (void)closeKbNotEnoughErroView;
- (void)kbNotEnoughErrorCancelClicked:(id)arg1;
- (void)kbNotEnoughErrorOKClicked:(id)arg1;
- (void)kbNotEnoughErrorCloseClicked:(id)arg1;
- (void)walletClicked:(id)arg1;
- (void)pageChanged:(id)arg1;
- (void)bgClicked:(id)arg1;
- (void)buyButtonClicked:(id)arg1;
- (void)propsListItemViewBeenClicked:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)removeErrorAndLoadingView;
- (void)updateBuyButtonBusyView;
- (void)updateContentUI;
- (void)setPropsList:(id)arg1;
- (void)showError:(id)arg1;
- (void)dismissAnimated:(_Bool)arg1;
- (void)dismiss;
- (void)showInView:(id)arg1;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <QSFullScreenLiveChatPropsListViewDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

