//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "QSCleanCacheProtocol-Protocol.h"

@class NSMutableDictionary, NSRecursiveLock;

@interface QSGifImageCache : NSObject <QSCleanCacheProtocol>
{
    NSMutableDictionary *_httpInfo;
    NSMutableDictionary *_requests;
    NSRecursiveLock *_lock;
}

+ (void)cleanCache;
+ (id)sharedInstance;
@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableDictionary *requests; // @synthesize requests=_requests;
@property(retain, nonatomic) NSMutableDictionary *httpInfo; // @synthesize httpInfo=_httpInfo;
- (void).cxx_destruct;
- (_Bool)isGifImageValidWithURL:(id)arg1;
- (void)stopGettingGifImageWithURL:(id)arg1 identifier:(id)arg2;
- (void)processLocalGifDirectoryCachePath:(id)arg1 withURL:(id)arg2;
- (void)startDownloadGifImageWithURL:(id)arg1;
- (long long)priorityForDownloadingImage:(id)arg1;
- (_Bool)canDownloadWithURL:(id)arg1;
- (void)getGifImageWithURL:(id)arg1 holdWhenWWan:(_Bool)arg2 identifier:(id)arg3 priority:(long long)arg4 downloadProgressBlock:(CDUnknownBlockType)arg5 completion:(CDUnknownBlockType)arg6;
- (void)getGifImageWithURL:(id)arg1 identifier:(id)arg2 priority:(long long)arg3 downloadProgressBlock:(CDUnknownBlockType)arg4 completion:(CDUnknownBlockType)arg5;
- (id)init;

@end

