//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class QSWebImageView, UIImage;

__attribute__((visibility("hidden")))
@interface QSGuessRankingAdCell : UITableViewCell
{
    UIImage *_adImage;
    QSWebImageView *_picImageView;
}

+ (id)getReuseIdentifier;
@property(retain, nonatomic) QSWebImageView *picImageView; // @synthesize picImageView=_picImageView;
@property(retain, nonatomic) UIImage *adImage; // @synthesize adImage=_adImage;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

