//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSPagedData.h"

@class NSString, QSGuessRankingAdItem, QSGuessRankingPrize;

__attribute__((visibility("hidden")))
@interface QSGuessRankingData : QSPagedData
{
    NSString *_mid;
    QSGuessRankingAdItem *_ad;
    QSGuessRankingPrize *_prize;
    NSString *_adLogo;
}

+ (_Bool)cleanCacheWhenUserChanged;
@property(retain, nonatomic) NSString *adLogo; // @synthesize adLogo=_adLogo;
@property(retain, nonatomic) QSGuessRankingPrize *prize; // @synthesize prize=_prize;
@property(retain, nonatomic) QSGuessRankingAdItem *ad; // @synthesize ad=_ad;
@property(retain, nonatomic) NSString *mid; // @synthesize mid=_mid;
- (void).cxx_destruct;
- (void)refreshData;
- (void)resetWithResponseModel:(id)arg1;
- (id)httpURLComponents;
- (id)init;

@end

