//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSDictionary, NSString, QSHomeRecommendMatchDataVideoInfo;

__attribute__((visibility("hidden")))
@interface QSHomeRecommendMatchDataInfo : QSModel
{
    _Bool _ifHasVideo;
    NSDictionary *_jumpData;
    NSString *_matchDesc;
    NSString *_mid;
    NSString *_summary;
    NSString *_title;
    NSString *_type;
    long long _showType;
    QSHomeRecommendMatchDataVideoInfo *_video;
}

@property(retain, nonatomic) QSHomeRecommendMatchDataVideoInfo *video; // @synthesize video=_video;
@property(nonatomic) long long showType; // @synthesize showType=_showType;
@property(nonatomic) _Bool ifHasVideo; // @synthesize ifHasVideo=_ifHasVideo;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(copy, nonatomic) NSString *mid; // @synthesize mid=_mid;
@property(copy, nonatomic) NSString *matchDesc; // @synthesize matchDesc=_matchDesc;
@property(retain, nonatomic) NSDictionary *jumpData; // @synthesize jumpData=_jumpData;
- (void).cxx_destruct;

@end

