//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QSMatchDetailInfo, QSWebImageViewEx, UILabel;

__attribute__((visibility("hidden")))
@interface QSHomeVideoMatchContent : UIView
{
    QSMatchDetailInfo *_detailInfo;
    QSWebImageViewEx *_homeTeamLogoImageView;
    QSWebImageViewEx *_guestTeamLogoImageView;
    UILabel *_dateLabel;
    UILabel *_timeLabel;
}

@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) QSWebImageViewEx *guestTeamLogoImageView; // @synthesize guestTeamLogoImageView=_guestTeamLogoImageView;
@property(retain, nonatomic) QSWebImageViewEx *homeTeamLogoImageView; // @synthesize homeTeamLogoImageView=_homeTeamLogoImageView;
@property(retain, nonatomic) QSMatchDetailInfo *detailInfo; // @synthesize detailInfo=_detailInfo;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

