//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface QSHomeRecommendHeadImageInfo : QSModel
{
    _Bool _ifHasVideo;
    int _newsTypeColor;
    NSString *_vid;
    NSString *_cid;
    NSString *_pic;
    NSString *_title;
    NSString *_newsType;
    NSString *_commentsNum;
    NSString *_pubTime;
    NSDictionary *_report;
}

+ (id)propertyNameFromParsedKey:(id)arg1;
@property(retain, nonatomic) NSDictionary *report; // @synthesize report=_report;
@property(retain, nonatomic) NSString *pubTime; // @synthesize pubTime=_pubTime;
@property(retain, nonatomic) NSString *commentsNum; // @synthesize commentsNum=_commentsNum;
@property(nonatomic) int newsTypeColor; // @synthesize newsTypeColor=_newsTypeColor;
@property(retain, nonatomic) NSString *newsType; // @synthesize newsType=_newsType;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *pic; // @synthesize pic=_pic;
@property(copy, nonatomic) NSString *cid; // @synthesize cid=_cid;
@property(copy, nonatomic) NSString *vid; // @synthesize vid=_vid;
@property(nonatomic) _Bool ifHasVideo; // @synthesize ifHasVideo=_ifHasVideo;
- (void).cxx_destruct;

@end

