//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSVideoListBaseCell.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface QSHomeVideoBasePlayerCell : QSVideoListBaseCell
{
    UIView *_playerView;
    unsigned long long _playType;
}

+ (id)actionsWillBePerformed;
@property(nonatomic) unsigned long long playType; // @synthesize playType=_playType;
@property(retain, nonatomic) UIView *playerView; // @synthesize playerView=_playerView;
- (void).cxx_destruct;
- (void)stopPlayVideo;
- (void)startPlayVideo;
- (id)currentPreviewImage;
- (id)title;
- (id)currentVideoID;

@end

