//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class QSVideoListItemModel;

__attribute__((visibility("hidden")))
@interface QSHomeVideoPlayerCellModel : NSObject
{
    _Bool _enableScroll;
    _Bool _showSubContent;
    unsigned long long _baseInfoType;
    double _bottomSeparatorHeight;
    QSVideoListItemModel *_itemModel;
    struct UIEdgeInsets _contentInsets;
}

@property(retain, nonatomic) QSVideoListItemModel *itemModel; // @synthesize itemModel=_itemModel;
@property(nonatomic) double bottomSeparatorHeight; // @synthesize bottomSeparatorHeight=_bottomSeparatorHeight;
@property(nonatomic) _Bool showSubContent; // @synthesize showSubContent=_showSubContent;
@property(nonatomic) _Bool enableScroll; // @synthesize enableScroll=_enableScroll;
@property(nonatomic) unsigned long long baseInfoType; // @synthesize baseInfoType=_baseInfoType;
@property(nonatomic) struct UIEdgeInsets contentInsets; // @synthesize contentInsets=_contentInsets;
- (void).cxx_destruct;

@end

