//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface QSHomeRecommendGuessItem : QSModel
{
    _Bool _isFree;
    NSString *_aid;
    NSString *_expertIcon;
    NSString *_expertId;
    NSString *_expertName;
    NSString *_tag;
    NSDictionary *_jumpData;
    NSString *_newsId;
    NSString *_news_type;
    NSString *_news_type_color;
    unsigned long long _price;
    NSString *_title;
    NSString *_saleStopTime;
}

@property(copy, nonatomic) NSString *saleStopTime; // @synthesize saleStopTime=_saleStopTime;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) unsigned long long price; // @synthesize price=_price;
@property(copy, nonatomic) NSString *news_type_color; // @synthesize news_type_color=_news_type_color;
@property(copy, nonatomic) NSString *news_type; // @synthesize news_type=_news_type;
@property(copy, nonatomic) NSString *newsId; // @synthesize newsId=_newsId;
@property(retain, nonatomic) NSDictionary *jumpData; // @synthesize jumpData=_jumpData;
@property(nonatomic) _Bool isFree; // @synthesize isFree=_isFree;
@property(copy, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(copy, nonatomic) NSString *expertName; // @synthesize expertName=_expertName;
@property(copy, nonatomic) NSString *expertId; // @synthesize expertId=_expertId;
@property(copy, nonatomic) NSString *expertIcon; // @synthesize expertIcon=_expertIcon;
@property(copy, nonatomic) NSString *aid; // @synthesize aid=_aid;
- (void).cxx_destruct;

@end

