//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface QSHomeRecommendWordCupMatchInfo : QSModel
{
    NSString *_today;
    NSString *_descPrefix;
    NSString *_descSuffix;
    NSString *_num;
    NSString *_adLogo;
    long long _position;
    NSArray *_matchList;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) NSArray *matchList; // @synthesize matchList=_matchList;
@property(nonatomic) long long position; // @synthesize position=_position;
@property(copy, nonatomic) NSString *adLogo; // @synthesize adLogo=_adLogo;
@property(copy, nonatomic) NSString *num; // @synthesize num=_num;
@property(copy, nonatomic) NSString *descSuffix; // @synthesize descSuffix=_descSuffix;
@property(copy, nonatomic) NSString *descPrefix; // @synthesize descPrefix=_descPrefix;
@property(copy, nonatomic) NSString *today; // @synthesize today=_today;
- (void).cxx_destruct;

@end

