//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface QSHomeVideoMultiVideoModel : QSModel
{
    NSMutableArray *_videoItems;
}

@property(retain, nonatomic) NSMutableArray *videoItems; // @synthesize videoItems=_videoItems;
- (void).cxx_destruct;
- (void)deleteItem:(id)arg1;
- (void)addVideoItems:(id)arg1;
- (void)addVideoItem:(id)arg1;
- (unsigned long long)itemsCount;
- (id)allItems;
- (id)itemWithIndex:(unsigned long long)arg1;
- (id)init;

@end

