//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSHomeVideoSubContentView.h"

#import "QSHorizontalTableViewDelegate-Protocol.h"

@class NSString, QSHorizontalTableView, QSVideoListMatchModel, UIImageView;

__attribute__((visibility("hidden")))
@interface QSHomeVideoNBAScoreSubContent : QSHomeVideoSubContentView <QSHorizontalTableViewDelegate>
{
    QSHorizontalTableView *_scoreView;
    QSVideoListMatchModel *_matchModel;
    UIImageView *_arrowView;
}

+ (double)heightWithModel:(id)arg1;
@property(retain, nonatomic) UIImageView *arrowView; // @synthesize arrowView=_arrowView;
@property(retain, nonatomic) QSVideoListMatchModel *matchModel; // @synthesize matchModel=_matchModel;
@property(retain, nonatomic) QSHorizontalTableView *scoreView; // @synthesize scoreView=_scoreView;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndex:(unsigned long long)arg2;
- (double)tableView:(id)arg1 widthForRowAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfRowsInTableView:(id)arg1;
- (void)setListCellStyle:(unsigned long long)arg1;
- (void)layoutSubviews;
- (void)updateModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

