//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSHomePageFeedCellManager.h"

__attribute__((visibility("hidden")))
@interface QSHomeRecommendCellManager : QSHomePageFeedCellManager
{
}

+ (id)cellInfosForSection:(long long)arg1 withInfo:(id)arg2;
+ (_Bool)shouldShowHeaderInSection:(long long)arg1 withRecommedData:(id)arg2;
+ (void)setupSeparatorLineForCell:(id)arg1 withSectionsInfo:(id)arg2 atIndexPath:(id)arg3;
+ (id)cellWithRecommendCellInfo:(id)arg1 inTableView:(id)arg2;
+ (id)sectionInfosWithRecommedData:(id)arg1;

@end

