//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSDataController.h"

@class QSHttpCacheModelData;

@interface QSHttpCacheDataController : QSDataController
{
    QSHttpCacheModelData *_innerData;
}

@property(retain, nonatomic) QSHttpCacheModelData *innerData; // @synthesize innerData=_innerData;
- (void).cxx_destruct;
- (_Bool)isReloading;
- (void)forceReload;
- (void)reload;
- (id)initWithHttpURLComponents:(id)arg1 cacheIdentifier:(id)arg2 cacheExpireTime:(double)arg3 dataClass:(Class)arg4;
- (void)setModelData:(id)arg1;
- (id)modelData;

@end

