//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CTTelephonyNetworkInfo, NSDictionary, NSRunLoop, NSString, QSOperationQueue;

@interface QSHTTPRequestManagement : NSObject
{
    struct __SCNetworkReachability *_defaultRouteReachability;
    _Bool _cacheInvalidAlways;
    _Bool _enableHttp;
    NSString *_userAgent;
    NSDictionary *_deviceInfos;
    NSDictionary *_externDeviceInfos;
    long long _networkStatus;
    long long _networkStatusSubType;
    CDUnknownBlockType _cookiesBlock;
    CDUnknownBlockType _externOperationWhenFinished;
    CDUnknownBlockType _blockForCheckCurrentIsIPV6;
    QSOperationQueue *_requestsQueue;
    NSRunLoop *_networkStatusListenRunloop;
    CTTelephonyNetworkInfo *_telephonyNetworkInfo;
}

+ (void)enqueueBatchOfHTTPRequestOperations:(id)arg1 completionQueue:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
+ (id)startDataRequestWithURLComponents:(id)arg1 parserType:(long long)arg2 priority:(long long)arg3 objectParserBlock:(CDUnknownBlockType)arg4 completionQueue:(id)arg5 completion:(CDUnknownBlockType)arg6;
+ (id)startDataRequestAndParsingResultWithURLComponents:(id)arg1 priority:(long long)arg2 objectParserBlock:(CDUnknownBlockType)arg3 completionQueue:(id)arg4 completion:(CDUnknownBlockType)arg5;
+ (id)startDataRequestAndParsingResultWithURLComponents:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)startHttpRequestWithURLComponents:(id)arg1 parserType:(long long)arg2 priority:(long long)arg3 objectParserBlock:(CDUnknownBlockType)arg4 completionQueue:(id)arg5 completion:(CDUnknownBlockType)arg6;
+ (id)networkRequestThread;
+ (void)networkRequestThreadEntryPoint:(id)arg1;
+ (id)sharedInstance;
@property(nonatomic) _Bool enableHttp; // @synthesize enableHttp=_enableHttp;
@property(retain, nonatomic) CTTelephonyNetworkInfo *telephonyNetworkInfo; // @synthesize telephonyNetworkInfo=_telephonyNetworkInfo;
@property(nonatomic) __weak NSRunLoop *networkStatusListenRunloop; // @synthesize networkStatusListenRunloop=_networkStatusListenRunloop;
@property(retain, nonatomic) QSOperationQueue *requestsQueue; // @synthesize requestsQueue=_requestsQueue;
@property(copy, nonatomic) CDUnknownBlockType blockForCheckCurrentIsIPV6; // @synthesize blockForCheckCurrentIsIPV6=_blockForCheckCurrentIsIPV6;
@property(copy, nonatomic) CDUnknownBlockType externOperationWhenFinished; // @synthesize externOperationWhenFinished=_externOperationWhenFinished;
@property(copy, nonatomic) CDUnknownBlockType cookiesBlock; // @synthesize cookiesBlock=_cookiesBlock;
@property(nonatomic) long long networkStatusSubType; // @synthesize networkStatusSubType=_networkStatusSubType;
@property(nonatomic) long long networkStatus; // @synthesize networkStatus=_networkStatus;
@property(retain, nonatomic) NSDictionary *externDeviceInfos; // @synthesize externDeviceInfos=_externDeviceInfos;
@property(retain, nonatomic) NSDictionary *deviceInfos; // @synthesize deviceInfos=_deviceInfos;
@property(retain, nonatomic) NSString *userAgent; // @synthesize userAgent=_userAgent;
@property(nonatomic) _Bool cacheInvalidAlways; // @synthesize cacheInvalidAlways=_cacheInvalidAlways;
- (void).cxx_destruct;
- (id)IPV6Prefx;
- (void)addOperation:(id)arg1;
- (void)modifyHttpConnectMaxNum;
- (void)initAllConfig;
- (void)updateCurrentRadioAccessTechnology;
- (void)startListenRadioAccessTechnology;
- (void)reset:(long long)arg1;
- (void)stopListenNetWorkStatus;
- (void)startListenNetWorkStatusWithRunLoop:(id)arg1;
- (_Bool)currentNetworkIsWifi;
- (_Bool)currentNetworkUnavailable;
- (_Bool)currentNetworkAvailable;
- (void)setHttpRequestEnabled:(_Bool)arg1;

@end

