//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSTableViewControllerEx.h"

#import "QSBaseDataDelegate-Protocol.h"
#import "QSMediaPlayerViewControllerDelegate-Protocol.h"
#import "QSNewsCommentCellDelegate-Protocol.h"
#import "QSNewsInputBarDelegate-Protocol.h"
#import "QSPushViewControllerProtocol-Protocol.h"

@class NSString, QSImmersedVideoDetailData, QSInteractAnimator, QSNewsCommentItem, QSNewsInputBar, QSVideoLikeData, QSVideoListItemModel, UIButton, UIImageView, UINavigationBar, UIView;

__attribute__((visibility("hidden")))
@interface QSImmersedVideoDetailController : QSTableViewControllerEx <QSMediaPlayerViewControllerDelegate, QSBaseDataDelegate, QSNewsCommentCellDelegate, QSNewsInputBarDelegate, QSPushViewControllerProtocol>
{
    _Bool _showComment;
    unsigned long long _displayType;
    NSString *_vid;
    NSString *_cid;
    NSString *_targetId;
    QSVideoListItemModel *_itemModel;
    UIView *_headerView;
    UINavigationBar *_immersedBar;
    UIButton *_closeButton;
    QSNewsInputBar *_inputBar;
    QSNewsCommentItem *_replyCommentItem;
    QSImmersedVideoDetailData *_videoDetailData;
    QSVideoLikeData *_videoLikeData;
    QSInteractAnimator *_embededPushAnimator;
    UIImageView *_vipView;
}

+ (id)allViewControllerType;
@property(retain, nonatomic) UIImageView *vipView; // @synthesize vipView=_vipView;
@property(retain, nonatomic) QSInteractAnimator *embededPushAnimator; // @synthesize embededPushAnimator=_embededPushAnimator;
@property(retain, nonatomic) QSVideoLikeData *videoLikeData; // @synthesize videoLikeData=_videoLikeData;
@property(retain, nonatomic) QSImmersedVideoDetailData *videoDetailData; // @synthesize videoDetailData=_videoDetailData;
@property(retain, nonatomic) QSNewsCommentItem *replyCommentItem; // @synthesize replyCommentItem=_replyCommentItem;
@property(retain, nonatomic) QSNewsInputBar *inputBar; // @synthesize inputBar=_inputBar;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UINavigationBar *immersedBar; // @synthesize immersedBar=_immersedBar;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) QSVideoListItemModel *itemModel; // @synthesize itemModel=_itemModel;
@property(nonatomic) _Bool showComment; // @synthesize showComment=_showComment;
@property(copy, nonatomic) NSString *targetId; // @synthesize targetId=_targetId;
@property(copy, nonatomic) NSString *cid; // @synthesize cid=_cid;
@property(copy, nonatomic) NSString *vid; // @synthesize vid=_vid;
@property(nonatomic) unsigned long long displayType; // @synthesize displayType=_displayType;
- (void).cxx_destruct;
- (id)infoWillBeShared;
- (_Bool)inputBarShouldReturn:(id)arg1;
- (void)inputBarDidEndEditing:(id)arg1;
- (void)inputBarDidStartEditing:(id)arg1;
- (_Bool)inputBarWillStartEditing:(id)arg1 withMode:(unsigned long long)arg2;
- (void)newsInputBarOnMaskTap:(id)arg1;
- (void)replyCommentItem:(id)arg1;
- (void)stopUserInput;
- (void)newsCommentCellOnSupport:(id)arg1 supportButton:(id)arg2;
- (void)newsCommentCellOnIgnore:(id)arg1;
- (void)newsCommentCellOnBan:(id)arg1;
- (void)newsCommentCellOnDelete:(id)arg1;
- (void)newsCommentCellOnReport:(id)arg1;
- (void)newsCommentCellOnCopy:(id)arg1;
- (void)newsCommentCellOnReply:(id)arg1;
- (id)newsCommentMenuMaskShowInView;
- (void)finishTransitionWithAnimator:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)attachAnimatedView:(id)arg1 frameInNav:(struct CGRect)arg2;
- (void)updateAnimator:(id)arg1;
- (id)animatorWithOperation:(long long)arg1 withGesture:(id)arg2;
- (void)reloadCommentWithTargetId:(id)arg1;
- (void)startToPlayWithItem:(id)arg1 forced:(_Bool)arg2;
- (void)data:(id)arg1 didFinishLoadWithError:(id)arg2;
- (void)dataWillStartLoad:(id)arg1;
- (void)shouldReloadSinceErrorPressed;
- (_Bool)isEmpty;
- (_Bool)isEmptyViewInvalid;
- (_Bool)mediaPlayerViewControllerAutoPlayWhenSettingMediaItem:(id)arg1;
- (_Bool)mediaPlayerViewControllerHasNextVideo:(id)arg1 nextVideoName:(id *)arg2;
- (_Bool)mediaPlayerViewControllerShowPreNextVideoButton:(id)arg1;
- (void)mediaPlayerViewControllerDidChangeMediaPlayerState:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)cellAction:(id)arg1 performedWithData:(id)arg2 inCell:(id)arg3;
- (struct CGRect)frameForPresentedWarpperView;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (_Bool)tableViewHasMoreData:(id)arg1;
- (void)tableViewShouldLoadMoreData:(id)arg1;
- (id)errorImageHighlight;
- (id)errorImage;
- (void)showError;
- (long long)loadingViewStyle;
- (struct CGPoint)centerOfLoadingView;
- (void)hideVipView;
- (void)showVipView;
- (void)showContent;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)handleBackPress;
- (void)updateNavigationBar;
- (double)topOffset;
- (double)topBarOffset;
- (_Bool)shouldShowSelfDefinedNavigationBar;
- (long long)preferredStatusBarStyle;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithParameters:(id)arg1;
- (id)newPageDescription;
- (id)currentParameters;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

