//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSViewController.h"

#import "QSFullScreenImageBrowseViewDelegate-Protocol.h"
#import "QSNewsInputBarDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, QSFullScreenImageBrowseView, QSImageNavPopAnimator, QSNewsContentInfo, QSNewsInputBar, UILabel, UIPanGestureRecognizer, UIScrollView, UIView;

__attribute__((visibility("hidden")))
@interface QSImageNewsViewController : QSViewController <QSFullScreenImageBrowseViewDelegate, QSNewsInputBarDelegate, UIGestureRecognizerDelegate>
{
    NSString *_skipImageUrl;
    long long _skipImageIndex;
    NSString *_newsId;
    QSNewsContentInfo *_contentInfo;
    NSString *_imageUrlByClicked;
    QSFullScreenImageBrowseView *_imageBrowseView;
    UIView *_descMaskView;
    UIScrollView *_descScrollView;
    UILabel *_descLabel;
    unsigned long long _curIndex;
    QSNewsInputBar *_inputBar;
    QSImageNavPopAnimator *_popAnimator;
    UIPanGestureRecognizer *_popGesture;
}

@property(retain, nonatomic) UIPanGestureRecognizer *popGesture; // @synthesize popGesture=_popGesture;
@property(retain, nonatomic) QSImageNavPopAnimator *popAnimator; // @synthesize popAnimator=_popAnimator;
@property(retain, nonatomic) QSNewsInputBar *inputBar; // @synthesize inputBar=_inputBar;
@property(nonatomic) unsigned long long curIndex; // @synthesize curIndex=_curIndex;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UIScrollView *descScrollView; // @synthesize descScrollView=_descScrollView;
@property(retain, nonatomic) UIView *descMaskView; // @synthesize descMaskView=_descMaskView;
@property(retain, nonatomic) QSFullScreenImageBrowseView *imageBrowseView; // @synthesize imageBrowseView=_imageBrowseView;
@property(retain, nonatomic) NSString *imageUrlByClicked; // @synthesize imageUrlByClicked=_imageUrlByClicked;
@property(retain, nonatomic) QSNewsContentInfo *contentInfo; // @synthesize contentInfo=_contentInfo;
@property(retain, nonatomic) NSString *newsId; // @synthesize newsId=_newsId;
@property(nonatomic) long long skipImageIndex; // @synthesize skipImageIndex=_skipImageIndex;
@property(retain, nonatomic) NSString *skipImageUrl; // @synthesize skipImageUrl=_skipImageUrl;
- (void).cxx_destruct;
- (_Bool)inputBarShouldReturn:(id)arg1;
- (void)inputBarDidEndEditing:(id)arg1;
- (void)inputBarDidStartEditing:(id)arg1;
- (_Bool)inputBarWillStartEditing:(id)arg1 withMode:(unsigned long long)arg2;
- (void)newsInputBarOnComment:(id)arg1;
- (_Bool)hasComment;
- (void)stopUserInput;
- (void)fullScreenImageBrowseView:(id)arg1 didChangeToNewIndex:(unsigned long long)arg2;
- (void)updateDescription;
- (void)update;
- (int)getImageIndexByImageUrl:(id)arg1;
- (double)inputBarHeight;
- (void)fullScrrenPressed:(id)arg1;
- (_Bool)interactivePopGestureShouldBegin;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)currentVisableStatusWillChange;
- (void)handleBackPress:(id)arg1;
- (void)sharePressed:(id)arg1;
- (void)onPushGesture:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)externInfoForBossReporter;
- (id)animatorWithOperation:(long long)arg1 withGesture:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

