//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface QSImageRequestConfigure : NSObject
{
    _Bool _holdWhenWWan;
    NSString *_requestIdentifier;
    long long _priority;
    CDUnknownBlockType _modifyBlock;
    CDUnknownBlockType _completion;
    CDUnknownBlockType _downloadProgressBlock;
    NSString *_modifyIdentifier;
}

@property(nonatomic) _Bool holdWhenWWan; // @synthesize holdWhenWWan=_holdWhenWWan;
@property(retain, nonatomic) NSString *modifyIdentifier; // @synthesize modifyIdentifier=_modifyIdentifier;
@property(copy, nonatomic) CDUnknownBlockType downloadProgressBlock; // @synthesize downloadProgressBlock=_downloadProgressBlock;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(copy, nonatomic) CDUnknownBlockType modifyBlock; // @synthesize modifyBlock=_modifyBlock;
@property(nonatomic) long long priority; // @synthesize priority=_priority;
@property(retain, nonatomic) NSString *requestIdentifier; // @synthesize requestIdentifier=_requestIdentifier;
- (void).cxx_destruct;

@end

