//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSStatedData.h"

#import "QSAutoUpdateProtocol-Protocol.h"

@class NSString, QSMatchGuessQuestion;
@protocol QSInMatchGuessDataDelegate;

__attribute__((visibility("hidden")))
@interface QSInMatchGuessData : QSStatedData <QSAutoUpdateProtocol>
{
    NSString *_mid;
    double _updateFreq;
}

@property(nonatomic) double updateFreq; // @synthesize updateFreq=_updateFreq;
@property(retain, nonatomic) NSString *mid; // @synthesize mid=_mid;
- (void).cxx_destruct;
- (void)resetWithAutoRefreshModels:(id)arg1;
- (id)autoUpdateHttpURLComponents;
- (void)onAutoUpdate;
- (double)updateTimeInterval;
- (double)cacheExpireTime;
@property(readonly, nonatomic) QSMatchGuessQuestion *lastGuess; // @dynamic lastGuess;
- (void)resetWithResponseModel:(id)arg1;
- (id)httpURLComponents;
- (id)identifier;
- (void)resetFromCacheObject:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <QSInMatchGuessDataDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

