//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSInMatchLiveTitleView.h"

@class NSString, QSBackToVideoView, QSMatchSimpleTitleView, UIImageView;

__attribute__((visibility("hidden")))
@interface QSInMatchVideoLiveTitleView : QSInMatchLiveTitleView
{
    _Bool _isBackingToVideo;
    _Bool _isShowTitleView;
    _Bool _isShowArrow;
    NSString *_title;
    QSBackToVideoView *_backToVideoView;
    QSMatchSimpleTitleView *_matchView;
    UIImageView *_arrowImageView;
}

@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(nonatomic) _Bool isShowArrow; // @synthesize isShowArrow=_isShowArrow;
@property(nonatomic) _Bool isShowTitleView; // @synthesize isShowTitleView=_isShowTitleView;
@property(retain, nonatomic) QSMatchSimpleTitleView *matchView; // @synthesize matchView=_matchView;
@property(retain, nonatomic) QSBackToVideoView *backToVideoView; // @synthesize backToVideoView=_backToVideoView;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool isBackingToVideo; // @synthesize isBackingToVideo=_isBackingToVideo;
- (void).cxx_destruct;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)update;
- (void)resetTitleAlpha;
- (void)showArrow:(_Bool)arg1;
- (void)showTitleView:(_Bool)arg1;
- (void)showBackToVideo:(_Bool)arg1;
- (void)hideMatchViewForProjection:(_Bool)arg1;
- (void)setItemInfo:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

