//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSKCoinExchangeListInfoItem : QSModel
{
    NSString *_productId;
    unsigned long long _kbCount;
    unsigned long long _discount;
    unsigned long long _diamondCount;
    unsigned long long _vol;
    unsigned long long _acid;
}

@property(nonatomic) unsigned long long acid; // @synthesize acid=_acid;
@property(nonatomic) unsigned long long vol; // @synthesize vol=_vol;
@property(nonatomic) unsigned long long diamondCount; // @synthesize diamondCount=_diamondCount;
@property(nonatomic) unsigned long long discount; // @synthesize discount=_discount;
@property(nonatomic) unsigned long long kbCount; // @synthesize kbCount=_kbCount;
@property(copy, nonatomic) NSString *productId; // @synthesize productId=_productId;
- (void).cxx_destruct;

@end

