//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSLiveChatStructData : QSModel
{
    NSString *_leftIcon;
    NSString *_leftName;
    unsigned long long _leftPoints;
    NSString *_leftPropsId;
    NSString *_rightIcon;
    NSString *_rightName;
    unsigned long long _rightPoints;
    NSString *_rightPropsId;
    NSString *_title;
    NSString *_topLogo;
}

@property(copy, nonatomic) NSString *topLogo; // @synthesize topLogo=_topLogo;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *rightPropsId; // @synthesize rightPropsId=_rightPropsId;
@property(nonatomic) unsigned long long rightPoints; // @synthesize rightPoints=_rightPoints;
@property(copy, nonatomic) NSString *rightName; // @synthesize rightName=_rightName;
@property(copy, nonatomic) NSString *rightIcon; // @synthesize rightIcon=_rightIcon;
@property(copy, nonatomic) NSString *leftPropsId; // @synthesize leftPropsId=_leftPropsId;
@property(nonatomic) unsigned long long leftPoints; // @synthesize leftPoints=_leftPoints;
@property(copy, nonatomic) NSString *leftName; // @synthesize leftName=_leftName;
@property(copy, nonatomic) NSString *leftIcon; // @synthesize leftIcon=_leftIcon;
- (void).cxx_destruct;

@end

