//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSLiveChatPropInfoItem : QSModel
{
    NSString *_header;
    NSString *_num;
    NSString *_prop_name;
    NSString *_prop_url;
    NSString *_sender_nick;
    NSString *_target_nick;
}

@property(retain, nonatomic) NSString *target_nick; // @synthesize target_nick=_target_nick;
@property(retain, nonatomic) NSString *sender_nick; // @synthesize sender_nick=_sender_nick;
@property(retain, nonatomic) NSString *prop_url; // @synthesize prop_url=_prop_url;
@property(retain, nonatomic) NSString *prop_name; // @synthesize prop_name=_prop_name;
@property(retain, nonatomic) NSString *num; // @synthesize num=_num;
@property(retain, nonatomic) NSString *header; // @synthesize header=_header;
- (void).cxx_destruct;

@end

