//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSMediaPlayerDefinitionView.h"

@class QSBusSystem;

__attribute__((visibility("hidden")))
@interface QSLivePlayerDefinitionView : QSMediaPlayerDefinitionView
{
    QSBusSystem *_mediaPlayerBusSystem;
}

@property(retain, nonatomic) QSBusSystem *mediaPlayerBusSystem; // @synthesize mediaPlayerBusSystem=_mediaPlayerBusSystem;
- (void).cxx_destruct;

@end

