//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSMatchGuessCell.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface QSLiveChatGuessCell : QSMatchGuessCell
{
    UIImageView *_borderView;
}

+ (double)cellYOffset;
+ (double)cellXPadding;
@property(retain, nonatomic) UIImageView *borderView; // @synthesize borderView=_borderView;
- (void).cxx_destruct;
- (void)update;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

