//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString, QSLotteryPropsRequestLinkInfo;

__attribute__((visibility("hidden")))
@interface QSLotteryPropsRequestInfo : QSModel
{
    _Bool _isHit;
    NSString *_hitWord;
    NSString *_hitTitle;
    NSString *_prizeId;
    NSString *_prizeLogo;
    NSString *_prizeName;
    QSLotteryPropsRequestLinkInfo *_link;
}

@property(retain, nonatomic) QSLotteryPropsRequestLinkInfo *link; // @synthesize link=_link;
@property(copy, nonatomic) NSString *prizeName; // @synthesize prizeName=_prizeName;
@property(copy, nonatomic) NSString *prizeLogo; // @synthesize prizeLogo=_prizeLogo;
@property(copy, nonatomic) NSString *prizeId; // @synthesize prizeId=_prizeId;
@property(copy, nonatomic) NSString *hitTitle; // @synthesize hitTitle=_hitTitle;
@property(copy, nonatomic) NSString *hitWord; // @synthesize hitWord=_hitWord;
@property(nonatomic) _Bool isHit; // @synthesize isHit=_isHit;
- (void).cxx_destruct;

@end

