//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSViewController.h"

@class QSLogItem, UITextView;

__attribute__((visibility("hidden")))
@interface QSLogDetailViewController : QSViewController
{
    QSLogItem *_item;
    UITextView *_textView;
}

@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) QSLogItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)returnPressed:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)shouldShowSelfDefinedNavigationBar;

@end

