//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface QSMatchGuessAllRankAnchorRank : QSModel
{
    NSDictionary *_jumpData;
    NSString *_title;
    NSArray *_rankList;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) NSArray *rankList; // @synthesize rankList=_rankList;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSDictionary *jumpData; // @synthesize jumpData=_jumpData;
- (void).cxx_destruct;

@end

