//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString, QSMatchGuessEntranceUserInfo, QSMatchGuessQuestion;

__attribute__((visibility("hidden")))
@interface QSMatchGuessEntranceInfo : QSModel
{
    _Bool _hasGuess;
    QSMatchGuessEntranceUserInfo *_userInfo;
    NSString *_guessWord;
    NSString *_prizeIcon;
    QSMatchGuessQuestion *_guessData;
    NSString *_adLogo;
}

@property(retain, nonatomic) NSString *adLogo; // @synthesize adLogo=_adLogo;
@property(retain, nonatomic) QSMatchGuessQuestion *guessData; // @synthesize guessData=_guessData;
@property(nonatomic) _Bool hasGuess; // @synthesize hasGuess=_hasGuess;
@property(copy, nonatomic) NSString *prizeIcon; // @synthesize prizeIcon=_prizeIcon;
@property(copy, nonatomic) NSString *guessWord; // @synthesize guessWord=_guessWord;
@property(retain, nonatomic) QSMatchGuessEntranceUserInfo *userInfo; // @synthesize userInfo=_userInfo;
- (void).cxx_destruct;

@end

