//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString, QSMatchStateOddsInfoItemInit, QSMatchStateOddsInfoItemRecent;

__attribute__((visibility("hidden")))
@interface QSMatchStateOddsInfoItem : QSModel
{
    NSString *_company;
    QSMatchStateOddsInfoItemRecent *_recent;
    QSMatchStateOddsInfoItemInit *_oddInit;
}

+ (id)propertyNameFromParsedKey:(id)arg1;
@property(retain, nonatomic) QSMatchStateOddsInfoItemInit *oddInit; // @synthesize oddInit=_oddInit;
@property(retain, nonatomic) QSMatchStateOddsInfoItemRecent *recent; // @synthesize recent=_recent;
@property(retain, nonatomic) NSString *company; // @synthesize company=_company;
- (void).cxx_destruct;

@end

