//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QSMatchDetailInfo, UILabel;

__attribute__((visibility("hidden")))
@interface QSMatchSummaryScoreNonVSContentView : UIView
{
    UILabel *_matchDescLabel;
    QSMatchDetailInfo *_detailInfo;
    UILabel *_detailLabel;
    UILabel *_quarterLabel;
}

+ (double)heightWithModel:(id)arg1;
@property(retain, nonatomic) UILabel *quarterLabel; // @synthesize quarterLabel=_quarterLabel;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) QSMatchDetailInfo *detailInfo; // @synthesize detailInfo=_detailInfo;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

