//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSMatchLiveBasePropsMessageItem.h"

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface QSMatchLiveAdPropsMessageItem : QSMatchLiveBasePropsMessageItem
{
    NSString *_logo;
    NSString *_adword1;
    NSString *_adword2;
    NSString *_pic;
    NSDictionary *_jumpData;
}

@property(retain, nonatomic) NSDictionary *jumpData; // @synthesize jumpData=_jumpData;
@property(copy, nonatomic) NSString *pic; // @synthesize pic=_pic;
@property(copy, nonatomic) NSString *adword2; // @synthesize adword2=_adword2;
@property(copy, nonatomic) NSString *adword1; // @synthesize adword1=_adword1;
@property(copy, nonatomic) NSString *logo; // @synthesize logo=_logo;
- (void).cxx_destruct;

@end

