//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QSLotteryPropsRequestInfo, QSWebImageView, UIButton, UILabel;
@protocol QSMatchLiveLotteryPropsWinAlertDelegate;

__attribute__((visibility("hidden")))
@interface QSMatchLiveLotteryPropsWinAlert : UIView
{
    _Bool _fullScreen;
    id <QSMatchLiveLotteryPropsWinAlertDelegate> _delegate;
    QSLotteryPropsRequestInfo *_requestInfo;
    UIButton *_closeButton;
    QSWebImageView *_logoView;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UIView *_line;
    UIButton *_okButton;
}

@property(retain, nonatomic) UIButton *okButton; // @synthesize okButton=_okButton;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) QSWebImageView *logoView; // @synthesize logoView=_logoView;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic, getter=isFullScreen) _Bool fullScreen; // @synthesize fullScreen=_fullScreen;
@property(retain, nonatomic) QSLotteryPropsRequestInfo *requestInfo; // @synthesize requestInfo=_requestInfo;
@property(nonatomic) __weak id <QSMatchLiveLotteryPropsWinAlertDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)okClicked:(id)arg1;
- (void)closeClicked:(id)arg1;
- (void)adjustSubviews;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

