//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "QSMatchGuessBetViewDelegate-Protocol.h"
#import "QSMatchGuessInfoViewDelegate-Protocol.h"
#import "QSMatchGuessWagerCommitDelegate-Protocol.h"
#import "QSMatchGuessWagerDelegate-Protocol.h"

@class NSString, QSMatchGuessBetView, QSMatchGuessInfoView, QSMatchGuessQuestion, UIButton;
@protocol QSMatchGuessViewDelegate;

__attribute__((visibility("hidden")))
@interface QSMatchGuessView : UIView <QSMatchGuessWagerDelegate, QSMatchGuessWagerCommitDelegate, QSMatchGuessInfoViewDelegate, QSMatchGuessBetViewDelegate>
{
    _Bool _detailShowed;
    id <QSMatchGuessViewDelegate> _delegate;
    NSString *_mid;
    QSMatchGuessQuestion *_question;
    UIButton *_guessButton;
    QSMatchGuessInfoView *_guessInfoView;
    QSMatchGuessBetView *_guessBetView;
    struct CGRect _originalFrame;
}

@property(nonatomic) struct CGRect originalFrame; // @synthesize originalFrame=_originalFrame;
@property(retain, nonatomic) QSMatchGuessBetView *guessBetView; // @synthesize guessBetView=_guessBetView;
@property(retain, nonatomic) QSMatchGuessInfoView *guessInfoView; // @synthesize guessInfoView=_guessInfoView;
@property(retain, nonatomic) UIButton *guessButton; // @synthesize guessButton=_guessButton;
@property(retain, nonatomic) QSMatchGuessQuestion *question; // @synthesize question=_question;
@property(copy, nonatomic) NSString *mid; // @synthesize mid=_mid;
@property(nonatomic) _Bool detailShowed; // @synthesize detailShowed=_detailShowed;
@property(nonatomic) __weak id <QSMatchGuessViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)guessButtonDidTap:(id)arg1;
- (void)matchGuessBetView:(id)arg1 didTapCloseButton:(id)arg2;
- (void)matchGuessBetView:(id)arg1 didTapBackButton:(id)arg2;
- (void)guessQuestionCell:(id)arg1 didSelectIndex:(long long)arg2;
- (void)matchGuessInfoView:(id)arg1 didTapCloseButton:(id)arg2;
- (void)revertToSmallScreen;
- (void)exchangeKb:(unsigned long long)arg1;
- (void)wagerCommitSuccess;
- (void)transitionFromGuessBetViewToGuessInfoView;
- (void)transitionFromGuessInfoViewToGuessBetView;
- (void)transitionFromGuessButtonToGuessInfoView;
- (void)showGuessInfoViewDirectly;
- (void)didShowGuessInfoView;
- (void)willShowGuessInfoView;
- (void)hideGuessButton;
- (void)showGuessButton;
- (_Bool)shouldReceiveTouchEventsWithPoint:(struct CGPoint)arg1;
- (void)showWagerViewWithJoinPreInfo:(id)arg1;
- (void)hide;
- (void)showGuessViewWithMid:(id)arg1 question:(id)arg2 inView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

