//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSStatedData.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface QSMatchDetailAllRelatedNewsData : QSStatedData
{
    NSString *_mid;
    NSString *_newsId;
    NSArray *_news;
}

@property(readonly, nonatomic) __weak NSArray *news; // @synthesize news=_news;
@property(retain, nonatomic) NSString *newsId; // @synthesize newsId=_newsId;
@property(retain, nonatomic) NSString *mid; // @synthesize mid=_mid;
- (void).cxx_destruct;
@property(readonly, nonatomic) __weak NSArray *items;
- (void)resetWithResponseModel:(id)arg1;
- (id)identifier;
- (id)httpURLComponents;

@end

