//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface QSMatchDetailLiveTypeChangeView : UIView
{
    UIView *_contentView;
    UIImageView *_contentBgView;
    UILabel *_topLabel;
    UILabel *_bottomLabel;
}

@property(retain, nonatomic) UILabel *bottomLabel; // @synthesize bottomLabel=_bottomLabel;
@property(retain, nonatomic) UILabel *topLabel; // @synthesize topLabel=_topLabel;
@property(retain, nonatomic) UIImageView *contentBgView; // @synthesize contentBgView=_contentBgView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)dismissAnimated:(_Bool)arg1;
- (void)showInSuperView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

