//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface QSMatchStatePlayerStatSectionRow : QSModel
{
    NSArray *_row;
    NSString *_playerId;
    NSString *_playerUrl;
}

@property(retain, nonatomic) NSString *playerUrl; // @synthesize playerUrl=_playerUrl;
@property(retain, nonatomic) NSString *playerId; // @synthesize playerId=_playerId;
@property(retain, nonatomic) NSArray *row; // @synthesize row=_row;
- (void).cxx_destruct;

@end

