//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSMatchDetailAudioLiveListItem : QSModel
{
    _Bool _isTwoZby;
    NSString *_zbyId;
    NSString *_audioId;
    NSString *_support;
    NSString *_name;
    NSString *_desc;
    NSString *_lIcon;
    NSString *_sIcon;
    NSString *_hasViceZby;
    NSString *_name2;
    NSString *_desc2;
    NSString *_lIcon2;
    NSString *_sIcon2;
    unsigned long long _status;
    unsigned long long _status2;
    NSString *_newsId;
    NSString *_cid;
    NSString *_audioUrl;
    NSString *_audioCopyRight;
}

+ (id)ignoredPropertiesWhenEncoding;
@property(nonatomic) _Bool isTwoZby; // @synthesize isTwoZby=_isTwoZby;
@property(retain, nonatomic) NSString *audioCopyRight; // @synthesize audioCopyRight=_audioCopyRight;
@property(retain, nonatomic) NSString *audioUrl; // @synthesize audioUrl=_audioUrl;
@property(retain, nonatomic) NSString *cid; // @synthesize cid=_cid;
@property(retain, nonatomic) NSString *newsId; // @synthesize newsId=_newsId;
@property(nonatomic) unsigned long long status2; // @synthesize status2=_status2;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *sIcon2; // @synthesize sIcon2=_sIcon2;
@property(retain, nonatomic) NSString *lIcon2; // @synthesize lIcon2=_lIcon2;
@property(retain, nonatomic) NSString *desc2; // @synthesize desc2=_desc2;
@property(retain, nonatomic) NSString *name2; // @synthesize name2=_name2;
@property(retain, nonatomic) NSString *hasViceZby; // @synthesize hasViceZby=_hasViceZby;
@property(retain, nonatomic) NSString *sIcon; // @synthesize sIcon=_sIcon;
@property(retain, nonatomic) NSString *lIcon; // @synthesize lIcon=_lIcon;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *support; // @synthesize support=_support;
@property(retain, nonatomic) NSString *audioId; // @synthesize audioId=_audioId;
@property(retain, nonatomic) NSString *zbyId; // @synthesize zbyId=_zbyId;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)currentStatus;

@end

