//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface QSMatchDetailGuessOddsMonitor : NSObject
{
    NSDictionary *_oddsRecords;
}

@property(retain, nonatomic) NSDictionary *oddsRecords; // @synthesize oddsRecords=_oddsRecords;
- (void).cxx_destruct;
- (long long)oddsChangeRecordOfChoiceItem:(id)arg1 guessItem:(id)arg2;
- (void)resetWithGuessItemList:(id)arg1;
- (id)init;

@end

