//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSMatchLiveBasePropsMessageItem.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSMatchLiveRealTimePropsMessageItem : QSMatchLiveBasePropsMessageItem
{
    NSString *_propsid;
    NSString *_propsName;
    NSString *_propsIcon;
    NSString *_targetCode;
    NSString *_targetName;
    NSString *_targetIcon;
    NSString *_word;
}

@property(copy, nonatomic) NSString *word; // @synthesize word=_word;
@property(copy, nonatomic) NSString *targetIcon; // @synthesize targetIcon=_targetIcon;
@property(copy, nonatomic) NSString *targetName; // @synthesize targetName=_targetName;
@property(copy, nonatomic) NSString *targetCode; // @synthesize targetCode=_targetCode;
@property(copy, nonatomic) NSString *propsIcon; // @synthesize propsIcon=_propsIcon;
@property(copy, nonatomic) NSString *propsName; // @synthesize propsName=_propsName;
@property(copy, nonatomic) NSString *propsid; // @synthesize propsid=_propsid;
- (void).cxx_destruct;

@end

