//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "QSPerformanceMonitorProtocal-Protocol.h"

@class NSString;
@protocol OS_dispatch_queue, OS_dispatch_semaphore, QSQSPerformanceMonitorUpdateProtocal;

__attribute__((visibility("hidden")))
@interface QSMainThreadMonitor : NSObject <QSPerformanceMonitorProtocal>
{
    unsigned long long _runLoopActivity;
    struct __CFRunLoopObserver *_runLoopObserver;
    unsigned long long _observedActivity;
    _Bool _isStoped;
    id <QSQSPerformanceMonitorUpdateProtocal> delegate;
    unsigned long long _loopInterval;
    unsigned long long _thresholdInterval;
    unsigned long long _currentBlockedInterval;
    NSObject<OS_dispatch_semaphore> *_lagSemaphore;
    NSObject<OS_dispatch_queue> *_lagMonitorQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *lagMonitorQueue; // @synthesize lagMonitorQueue=_lagMonitorQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *lagSemaphore; // @synthesize lagSemaphore=_lagSemaphore;
@property(nonatomic) unsigned long long currentBlockedInterval; // @synthesize currentBlockedInterval=_currentBlockedInterval;
@property(nonatomic) unsigned long long thresholdInterval; // @synthesize thresholdInterval=_thresholdInterval;
@property(nonatomic) unsigned long long loopInterval; // @synthesize loopInterval=_loopInterval;
@property(nonatomic) _Bool isStoped; // @synthesize isStoped=_isStoped;
@property(nonatomic) __weak id <QSQSPerformanceMonitorUpdateProtocal> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)outputData;
- (void)detectAppLag;
- (void)singalWithRunLoopActivity:(unsigned long long)arg1;
- (void)stopMonitor;
- (void)ping;
- (void)startMonitor;
- (_Bool)isRunning;
- (unsigned long long)dataType;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

