//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSMatchTeamPlayersBaseView.h"

@class NSString, QSAvatarViewWith1PxBorder, QSMatchStatePlayerStatSectionRow;

__attribute__((visibility("hidden")))
@interface QSMatchTeamPlayersContentView : QSMatchTeamPlayersBaseView
{
    _Bool _showSeparateLine;
    QSMatchStatePlayerStatSectionRow *_row;
    QSAvatarViewWith1PxBorder *_playerImageView;
    NSString *_nameText;
}

@property(retain, nonatomic) NSString *nameText; // @synthesize nameText=_nameText;
@property(retain, nonatomic) QSAvatarViewWith1PxBorder *playerImageView; // @synthesize playerImageView=_playerImageView;
@property(nonatomic) _Bool showSeparateLine; // @synthesize showSeparateLine=_showSeparateLine;
@property(retain, nonatomic) QSMatchStatePlayerStatSectionRow *row; // @synthesize row=_row;
- (void).cxx_destruct;
- (void)setContent:(id)arg1 textXPositions:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

