//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSMatchLiveBasePropsMessageView.h"

@class QSMatchLiveKickPropsMessageItem, QSMatchLivePropsMessageRankView, UIButton, UILabel;

__attribute__((visibility("hidden")))
@interface QSMatchLiveKickPropsMessageView : QSMatchLiveBasePropsMessageView
{
    UILabel *_headLabel;
    UILabel *_nickNameLabel;
    UILabel *_tailLabel;
    UILabel *_kickOffTipLabel;
    UIButton *_reactionButton;
    QSMatchLivePropsMessageRankView *_rankView;
}

@property(retain, nonatomic) QSMatchLivePropsMessageRankView *rankView; // @synthesize rankView=_rankView;
@property(retain, nonatomic) UIButton *reactionButton; // @synthesize reactionButton=_reactionButton;
@property(retain, nonatomic) UILabel *kickOffTipLabel; // @synthesize kickOffTipLabel=_kickOffTipLabel;
@property(retain, nonatomic) UILabel *tailLabel; // @synthesize tailLabel=_tailLabel;
@property(retain, nonatomic) UILabel *nickNameLabel; // @synthesize nickNameLabel=_nickNameLabel;
@property(retain, nonatomic) UILabel *headLabel; // @synthesize headLabel=_headLabel;
- (void).cxx_destruct;
- (void)reactionButtonClicked:(id)arg1;
@property(readonly, nonatomic) QSMatchLiveKickPropsMessageItem *kickMessageItem; // @dynamic kickMessageItem;
- (void)updateWithMessageItem:(id)arg1;

@end

