//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSMatchVideoItem : QSModel
{
    _Bool _isPay;
    NSString *_vid;
    NSString *_title;
    NSString *_duration;
    NSString *_imgurl;
    NSString *_imgurl2;
    NSString *_views;
    NSString *_tag;
}

+ (id)propertyNameFromParsedKey:(id)arg1;
@property(retain, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(nonatomic) _Bool isPay; // @synthesize isPay=_isPay;
@property(copy, nonatomic) NSString *views; // @synthesize views=_views;
@property(copy, nonatomic) NSString *imgurl2; // @synthesize imgurl2=_imgurl2;
@property(copy, nonatomic) NSString *imgurl; // @synthesize imgurl=_imgurl;
@property(copy, nonatomic) NSString *duration; // @synthesize duration=_duration;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *vid; // @synthesize vid=_vid;
- (void).cxx_destruct;

@end

