//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class QSMatchStatePlayerStatSectionHead, QSMatchTeamPlayersHeaderView;

__attribute__((visibility("hidden")))
@interface QSMatchTeamPlayersTitleCell : UITableViewCell
{
    QSMatchStatePlayerStatSectionHead *_head;
    QSMatchTeamPlayersHeaderView *_headerView;
}

+ (double)height;
@property(retain, nonatomic) QSMatchTeamPlayersHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) QSMatchStatePlayerStatSectionHead *head; // @synthesize head=_head;
- (void).cxx_destruct;
- (id)updateWithRightTextXPositions:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

