//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSViewController.h"

#import "QSBaseDataDelegate-Protocol.h"
#import "QSMPVideoPlayerLayerViewControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, QSBusSystem, QSMPLayersViewController, QSMPSharedItem, QSMatchLiveSourceMediaItem, QSMatchSkipData, UIImageView, UILabel, UITableView, UIView;
@protocol QSMatchSkipDelegate;

__attribute__((visibility("hidden")))
@interface QSMatchSkipViewController : QSViewController <UITableViewDataSource, UITableViewDelegate, QSBaseDataDelegate, QSMPVideoPlayerLayerViewControllerDelegate>
{
    _Bool _isInPlayer;
    QSMPSharedItem *_sharedItem;
    QSBusSystem *_mediaPlayerBusSystem;
    QSMPLayersViewController *_videoPlayerViewController;
    id <QSMatchSkipDelegate> _delegate;
    QSMatchLiveSourceMediaItem *_liveSourceMediaItem;
    NSString *_matchTitle;
    QSMatchSkipData *_skipData;
    UITableView *_tableView;
    UIView *_maskView;
    UILabel *_titleLabel;
    UIImageView *_arrowImageView;
    double _initTime;
}

@property(nonatomic) double initTime; // @synthesize initTime=_initTime;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) QSMatchSkipData *skipData; // @synthesize skipData=_skipData;
@property(retain, nonatomic) NSString *matchTitle; // @synthesize matchTitle=_matchTitle;
@property(nonatomic) _Bool isInPlayer; // @synthesize isInPlayer=_isInPlayer;
@property(retain, nonatomic) QSMatchLiveSourceMediaItem *liveSourceMediaItem; // @synthesize liveSourceMediaItem=_liveSourceMediaItem;
@property(nonatomic) __weak id <QSMatchSkipDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak QSMPLayersViewController *videoPlayerViewController; // @synthesize videoPlayerViewController=_videoPlayerViewController;
@property(retain, nonatomic) QSBusSystem *mediaPlayerBusSystem; // @synthesize mediaPlayerBusSystem=_mediaPlayerBusSystem;
@property(retain, nonatomic) QSMPSharedItem *sharedItem; // @synthesize sharedItem=_sharedItem;
- (void).cxx_destruct;
- (id)fromMid;
- (id)currentMid;
- (void)reloadSkipData;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)updateTableViewHeight;
- (void)dismiss;
- (void)tap:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)init;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (void)deviceOrientationDidChanged:(id)arg1;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewWillAppear:(_Bool)arg1;
- (long long)preferredStatusBarStyle;
- (struct CGRect)suggestTableViewFrame;
- (void)data:(id)arg1 didFinishLoadWithError:(id)arg2;
- (void)dataWillStartLoad:(id)arg1;
- (id)createEmptyView;
- (void)showError;
- (struct CGPoint)centerOfLoadingView;
- (_Bool)isEmpty;
- (void)shouldReloadSinceErrorPressed;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=isPlayerMuted) _Bool playerMuted;
@property(readonly) Class superclass;

@end

