//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSDictionary, NSString, QSMatchGuessKbActivity, QSMatchGuessListTips, QSMatchGuessLotteryInfo;

__attribute__((visibility("hidden")))
@interface QSMatchGuessInfo : QSModel
{
    _Bool _matchActive;
    _Bool _rankAble;
    _Bool _listAble;
    _Bool _cardMark;
    _Bool _hasCard;
    QSMatchGuessLotteryInfo *_lottery;
    NSArray *_guessList;
    NSString *_updateFreq;
    NSString *_inactiveMsg;
    QSMatchGuessListTips *_tips;
    NSArray *_showList;
    NSString *_rankUrl;
    NSString *_cardBonus;
    NSString *_userRank;
    NSDictionary *_rankJumpData;
    NSDictionary *_listJumpData;
    QSMatchGuessKbActivity *_kbActivity;
    NSArray *_notices;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) NSArray *notices; // @synthesize notices=_notices;
@property(retain, nonatomic) QSMatchGuessKbActivity *kbActivity; // @synthesize kbActivity=_kbActivity;
@property(retain, nonatomic) NSDictionary *listJumpData; // @synthesize listJumpData=_listJumpData;
@property(retain, nonatomic) NSDictionary *rankJumpData; // @synthesize rankJumpData=_rankJumpData;
@property(retain, nonatomic) NSString *userRank; // @synthesize userRank=_userRank;
@property(retain, nonatomic) NSString *cardBonus; // @synthesize cardBonus=_cardBonus;
@property(nonatomic) _Bool hasCard; // @synthesize hasCard=_hasCard;
@property(nonatomic) _Bool cardMark; // @synthesize cardMark=_cardMark;
@property(retain, nonatomic) NSString *rankUrl; // @synthesize rankUrl=_rankUrl;
@property(retain, nonatomic) NSArray *showList; // @synthesize showList=_showList;
@property(nonatomic) _Bool listAble; // @synthesize listAble=_listAble;
@property(nonatomic) _Bool rankAble; // @synthesize rankAble=_rankAble;
@property(nonatomic) _Bool matchActive; // @synthesize matchActive=_matchActive;
@property(retain, nonatomic) QSMatchGuessListTips *tips; // @synthesize tips=_tips;
@property(retain, nonatomic) NSString *inactiveMsg; // @synthesize inactiveMsg=_inactiveMsg;
@property(retain, nonatomic) NSString *updateFreq; // @synthesize updateFreq=_updateFreq;
@property(retain, nonatomic) NSArray *guessList; // @synthesize guessList=_guessList;
@property(retain, nonatomic) QSMatchGuessLotteryInfo *lottery; // @synthesize lottery=_lottery;
- (void).cxx_destruct;

@end

