//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSMatchStateBaseInfo.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface QSMatchStateOddsInfo : QSMatchStateBaseInfo
{
    NSString *_middleDesc;
    NSArray *_odds;
    NSString *_leftBadge;
    NSString *_rightBadge;
    NSString *_leftUrl;
    NSString *_rightUrl;
    NSString *_leftName;
    NSString *_rightName;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) NSString *rightName; // @synthesize rightName=_rightName;
@property(retain, nonatomic) NSString *leftName; // @synthesize leftName=_leftName;
@property(retain, nonatomic) NSString *rightUrl; // @synthesize rightUrl=_rightUrl;
@property(retain, nonatomic) NSString *leftUrl; // @synthesize leftUrl=_leftUrl;
@property(retain, nonatomic) NSString *rightBadge; // @synthesize rightBadge=_rightBadge;
@property(retain, nonatomic) NSString *leftBadge; // @synthesize leftBadge=_leftBadge;
@property(retain, nonatomic) NSArray *odds; // @synthesize odds=_odds;
@property(retain, nonatomic) NSString *middleDesc; // @synthesize middleDesc=_middleDesc;
- (void).cxx_destruct;

@end

