//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSMatchCateColumnItem : QSModel
{
    NSString *_columnId;
    NSString *_icon;
    NSString *_name;
    long long _matchNum;
    NSString *_matchDesc;
}

@property(retain, nonatomic) NSString *matchDesc; // @synthesize matchDesc=_matchDesc;
@property(nonatomic) long long matchNum; // @synthesize matchNum=_matchNum;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *columnId; // @synthesize columnId=_columnId;
- (void).cxx_destruct;

@end

