//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface QSMatchPushFocusMatchesContentFutureMatchItem : QSModel
{
    _Bool _rankColumn;
    NSString *_columnId;
    NSString *_columnName;
    NSArray *_matches;
    NSString *_version;
    NSString *_title;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool rankColumn; // @synthesize rankColumn=_rankColumn;
@property(retain, nonatomic) NSString *version; // @synthesize version=_version;
@property(retain, nonatomic) NSArray *matches; // @synthesize matches=_matches;
@property(retain, nonatomic) NSString *columnName; // @synthesize columnName=_columnName;
@property(retain, nonatomic) NSString *columnId; // @synthesize columnId=_columnId;
- (void).cxx_destruct;
- (void)resetWithNewItem:(id)arg1;

@end

