//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSBaseHttpData.h"

@class NSString, QSMatchLivePropsBuyItem, QSMatchLivePropsListItem;

__attribute__((visibility("hidden")))
@interface QSMatchLivePropsBuyData : QSBaseHttpData
{
    _Bool _isHitEnd;
    _Bool _isFirstBuy;
    _Bool _fullscreen;
    int _totalHits;
    NSString *_orderid;
    NSString *_mid;
    QSMatchLivePropsListItem *_propsItem;
    NSString *_version;
}

+ (id)errorDescOfError:(id)arg1;
+ (_Bool)isKCoinNotEnoughError:(id)arg1;
+ (long long)modelType;
+ (Class)modelClass;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(nonatomic) _Bool fullscreen; // @synthesize fullscreen=_fullscreen;
@property(nonatomic) _Bool isFirstBuy; // @synthesize isFirstBuy=_isFirstBuy;
@property(nonatomic) int totalHits; // @synthesize totalHits=_totalHits;
@property(nonatomic) _Bool isHitEnd; // @synthesize isHitEnd=_isHitEnd;
@property(retain, nonatomic) QSMatchLivePropsListItem *propsItem; // @synthesize propsItem=_propsItem;
@property(copy, nonatomic) NSString *mid; // @synthesize mid=_mid;
@property(copy, nonatomic) NSString *orderid; // @synthesize orderid=_orderid;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isRequestingData) _Bool requestingData; // @dynamic requestingData;
@property(readonly, nonatomic) QSMatchLivePropsBuyItem *buyItem; // @dynamic buyItem;
- (id)startRequestWithURLComponents:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)httpURLComponents;

@end

