//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface QSMPVideoPlayerLayerConfig : NSObject
{
    _Bool _hidden;
    _Bool _keepAliveEvenHidden;
    unsigned long long _identifier;
    Class _layerClass;
    unsigned long long _dataIdentifier;
    Class _dataClass;
    unsigned long long _type;
    unsigned long long _autoresizingMask;
    unsigned long long _level;
    struct CGRect _frame;
    struct UIEdgeInsets _fixEdgeInset;
}

+ (id)layerConfigWithIdentifier:(unsigned long long)arg1 layerClass:(Class)arg2;
@property(nonatomic) unsigned long long level; // @synthesize level=_level;
@property(nonatomic) _Bool keepAliveEvenHidden; // @synthesize keepAliveEvenHidden=_keepAliveEvenHidden;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
@property(nonatomic) unsigned long long autoresizingMask; // @synthesize autoresizingMask=_autoresizingMask;
@property(nonatomic) struct UIEdgeInsets fixEdgeInset; // @synthesize fixEdgeInset=_fixEdgeInset;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) Class dataClass; // @synthesize dataClass=_dataClass;
@property(nonatomic) unsigned long long dataIdentifier; // @synthesize dataIdentifier=_dataIdentifier;
@property(retain, nonatomic) Class layerClass; // @synthesize layerClass=_layerClass;
@property(nonatomic) unsigned long long identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;

@end

