//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSMPMatchStateBasketballPlayerInfo : QSModel
{
    NSString *_playerId;
    NSString *_name;
    NSString *_enName;
    NSString *_pic;
    NSString *_started;
    NSString *_points;
    NSString *_rebounds;
    NSString *_steals;
    NSString *_assists;
    NSString *_blocked;
    NSString *_personalFouls;
    NSString *_fieldGoals;
    NSString *_threePoints;
    NSString *_freeThrows;
    NSString *_jerseyNum;
    struct CGSize _picSize;
}

@property(copy, nonatomic) NSString *jerseyNum; // @synthesize jerseyNum=_jerseyNum;
@property(copy, nonatomic) NSString *freeThrows; // @synthesize freeThrows=_freeThrows;
@property(copy, nonatomic) NSString *threePoints; // @synthesize threePoints=_threePoints;
@property(copy, nonatomic) NSString *fieldGoals; // @synthesize fieldGoals=_fieldGoals;
@property(copy, nonatomic) NSString *personalFouls; // @synthesize personalFouls=_personalFouls;
@property(copy, nonatomic) NSString *blocked; // @synthesize blocked=_blocked;
@property(copy, nonatomic) NSString *assists; // @synthesize assists=_assists;
@property(copy, nonatomic) NSString *steals; // @synthesize steals=_steals;
@property(copy, nonatomic) NSString *rebounds; // @synthesize rebounds=_rebounds;
@property(copy, nonatomic) NSString *points; // @synthesize points=_points;
@property(copy, nonatomic) NSString *started; // @synthesize started=_started;
@property(nonatomic) struct CGSize picSize; // @synthesize picSize=_picSize;
@property(copy, nonatomic) NSString *pic; // @synthesize pic=_pic;
@property(copy, nonatomic) NSString *enName; // @synthesize enName=_enName;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *playerId; // @synthesize playerId=_playerId;
- (void).cxx_destruct;
- (_Bool)manualSetValue:(id)arg1 forKey:(id)arg2;
- (_Bool)isEqual:(id)arg1;

@end

