//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface QSMPPlayerInfoAdjustBG : UIView
{
    UIView *_leftBG;
    UIView *_rightBG;
    UIView *_leftLine;
    UIView *_rightLine;
}

@property(retain, nonatomic) UIView *rightLine; // @synthesize rightLine=_rightLine;
@property(retain, nonatomic) UIView *leftLine; // @synthesize leftLine=_leftLine;
@property(retain, nonatomic) UIView *rightBG; // @synthesize rightBG=_rightBG;
@property(retain, nonatomic) UIView *leftBG; // @synthesize leftBG=_leftBG;
- (void).cxx_destruct;
- (void)setLeftHidden:(_Bool)arg1;
- (void)setRightHidden:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

