//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString, QSMPMatchStatePlayerOfBasketballMaxPlayer;

__attribute__((visibility("hidden")))
@interface QSMPMatchDetailBasketballMaxPlayerItem : QSModel
{
    NSString *_leftVal;
    NSString *_rightVal;
    QSMPMatchStatePlayerOfBasketballMaxPlayer *_leftPlayer;
    QSMPMatchStatePlayerOfBasketballMaxPlayer *_rightPlayer;
    NSString *_text;
}

@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) QSMPMatchStatePlayerOfBasketballMaxPlayer *rightPlayer; // @synthesize rightPlayer=_rightPlayer;
@property(retain, nonatomic) QSMPMatchStatePlayerOfBasketballMaxPlayer *leftPlayer; // @synthesize leftPlayer=_leftPlayer;
@property(retain, nonatomic) NSString *rightVal; // @synthesize rightVal=_rightVal;
@property(retain, nonatomic) NSString *leftVal; // @synthesize leftVal=_leftVal;
- (void).cxx_destruct;

@end

