//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSMPSeeBackPreviewBigPicInfo : QSModel
{
    NSString *_file_id;
    long long _time_stamp;
}

@property(nonatomic) long long time_stamp; // @synthesize time_stamp=_time_stamp;
@property(copy, nonatomic) NSString *file_id; // @synthesize file_id=_file_id;
- (void).cxx_destruct;

@end

