//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, QSMPMatchStateBasketballPlayerInfo, QSMPPlayerBriefView, QSMPPlayerDetailView, QSMPPlayerNameLabelView, QSMPPlayerNumberView, QSWebImageView;

__attribute__((visibility("hidden")))
@interface QSMPPlayerInfoCellContentView : UIView
{
    QSWebImageView *_headView;
    QSMPPlayerNumberView *_numberView;
    QSMPPlayerNameLabelView *_nameLabel;
    QSMPPlayerDetailView *_detailLabel;
    QSMPPlayerBriefView *_briefLabel;
    UIView *_lineView;
    QSMPMatchStateBasketballPlayerInfo *_player;
    long long _state;
    long long _nextState;
    unsigned long long _contentIndex;
    NSString *_teamColor;
}

@property(retain, nonatomic) NSString *teamColor; // @synthesize teamColor=_teamColor;
@property(nonatomic) unsigned long long contentIndex; // @synthesize contentIndex=_contentIndex;
@property(nonatomic) long long nextState; // @synthesize nextState=_nextState;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(retain, nonatomic) QSMPMatchStateBasketballPlayerInfo *player; // @synthesize player=_player;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) QSMPPlayerBriefView *briefLabel; // @synthesize briefLabel=_briefLabel;
@property(retain, nonatomic) QSMPPlayerDetailView *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) QSMPPlayerNameLabelView *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) QSMPPlayerNumberView *numberView; // @synthesize numberView=_numberView;
@property(retain, nonatomic) QSWebImageView *headView; // @synthesize headView=_headView;
- (void).cxx_destruct;
- (void)updateContentView;
- (void)_updateContentsFrameWithContentsHeight:(float)arg1;
- (void)updatePlayerData;
- (void)changeStateAndUpdateContentView:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

