//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSStatedData.h"

@class NSString, QSMPSeeBackPreviewInfo;

__attribute__((visibility("hidden")))
@interface QSMPSeeBackPreviewData : QSStatedData
{
    NSString *_sid;
    NSString *_date;
    QSMPSeeBackPreviewInfo *_previewInfo;
}

@property(retain, nonatomic) QSMPSeeBackPreviewInfo *previewInfo; // @synthesize previewInfo=_previewInfo;
@property(copy, nonatomic) NSString *date; // @synthesize date=_date;
@property(copy, nonatomic) NSString *sid; // @synthesize sid=_sid;
- (void).cxx_destruct;
- (id)startRequestWithURLComponents:(id)arg1 objectParserBlock:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)resetWithResponseModel:(id)arg1;
- (id)httpURLComponents;
- (double)cacheExpireTime;
- (id)identifier;

@end

