//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, QSMPSeeBackPreviewInfo, UIImage, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface QSMPSeeBackPreviewView : UIView
{
    long long _seekTime;
    long long _seeBackTime;
    QSMPSeeBackPreviewInfo *_previewInfo;
    NSString *_desc;
    UIImageView *_vipTagView;
    UILabel *_timeLabel;
    UIView *_imageContainerView;
    UIImageView *_imageView;
    UILabel *_descLabel;
    UIImage *_previewImage;
}

@property(retain, nonatomic) UIImage *previewImage; // @synthesize previewImage=_previewImage;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIView *imageContainerView; // @synthesize imageContainerView=_imageContainerView;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIImageView *vipTagView; // @synthesize vipTagView=_vipTagView;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) QSMPSeeBackPreviewInfo *previewInfo; // @synthesize previewInfo=_previewInfo;
@property(nonatomic) long long seeBackTime; // @synthesize seeBackTime=_seeBackTime;
@property(nonatomic) long long seekTime; // @synthesize seekTime=_seekTime;
- (void).cxx_destruct;
- (void)updateUI;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

