//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class QSAvatarView, QSMPMatchStateTeamInfo, UILabel;

__attribute__((visibility("hidden")))
@interface QSMPDataTitleCell : UITableViewCell
{
    QSMPMatchStateTeamInfo *_teamInfo;
    double _rightOffset;
    QSAvatarView *_leftTeamIcon;
    UILabel *_leftTeamLabel;
    QSAvatarView *_rightTeamIcon;
    UILabel *_rightTeamLabel;
    UILabel *_titleLabel;
}

+ (double)heightWithModel:(id)arg1;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *rightTeamLabel; // @synthesize rightTeamLabel=_rightTeamLabel;
@property(retain, nonatomic) QSAvatarView *rightTeamIcon; // @synthesize rightTeamIcon=_rightTeamIcon;
@property(retain, nonatomic) UILabel *leftTeamLabel; // @synthesize leftTeamLabel=_leftTeamLabel;
@property(retain, nonatomic) QSAvatarView *leftTeamIcon; // @synthesize leftTeamIcon=_leftTeamIcon;
@property(nonatomic) double rightOffset; // @synthesize rightOffset=_rightOffset;
@property(retain, nonatomic) QSMPMatchStateTeamInfo *teamInfo; // @synthesize teamInfo=_teamInfo;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setTitle:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

