//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface QSMsgInfo : QSModel
{
    double _refreshDuration;
    NSString *_shequCount;
    NSString *_sysCount;
    NSString *_guessCount;
    NSString *_giftCount;
    NSString *_vipSysCount;
    NSMutableDictionary *_othersCount;
}

@property(retain, nonatomic) NSMutableDictionary *othersCount; // @synthesize othersCount=_othersCount;
@property(copy, nonatomic) NSString *vipSysCount; // @synthesize vipSysCount=_vipSysCount;
@property(copy, nonatomic) NSString *giftCount; // @synthesize giftCount=_giftCount;
@property(copy, nonatomic) NSString *guessCount; // @synthesize guessCount=_guessCount;
@property(copy, nonatomic) NSString *sysCount; // @synthesize sysCount=_sysCount;
@property(copy, nonatomic) NSString *shequCount; // @synthesize shequCount=_shequCount;
@property(nonatomic) double refreshDuration; // @synthesize refreshDuration=_refreshDuration;
- (void).cxx_destruct;
- (_Bool)manualSetValue:(id)arg1 forKey:(id)arg2;

@end

