//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSViewController.h"

#import "QSBalanceTransferCellDelegate-Protocol.h"
#import "QSBaseDataDelegate-Protocol.h"
#import "QSDiamondTransferTipViewDelegate-Protocol.h"
#import "QSMyWalletHeaderCellDelegate-Protocol.h"
#import "QSPushViewControllerProtocol-Protocol.h"
#import "QSTableViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"

@class NSNumberFormatter, NSString, QSMyWalletData, QSTableView, UIView;

__attribute__((visibility("hidden")))
@interface QSMyWalletViewController : QSViewController <QSTableViewDelegate, UITableViewDataSource, QSBaseDataDelegate, QSMyWalletHeaderCellDelegate, QSBalanceTransferCellDelegate, QSDiamondTransferTipViewDelegate, QSPushViewControllerProtocol>
{
    QSTableView *_listView;
    UIView *_defaultSectionFooter;
    UIView *_notLoginHeader;
    QSMyWalletData *_listData;
    NSNumberFormatter *_numberFormatter;
}

+ (id)allViewControllerType;
@property(retain, nonatomic) NSNumberFormatter *numberFormatter; // @synthesize numberFormatter=_numberFormatter;
@property(retain, nonatomic) QSMyWalletData *listData; // @synthesize listData=_listData;
@property(retain, nonatomic) UIView *notLoginHeader; // @synthesize notLoginHeader=_notLoginHeader;
@property(retain, nonatomic) UIView *defaultSectionFooter; // @synthesize defaultSectionFooter=_defaultSectionFooter;
@property(retain, nonatomic) QSTableView *listView; // @synthesize listView=_listView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)navigateToConsumeRecordViewController;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)confirmTransferDiamond;
- (void)transformDiamondWithLoginType:(long long)arg1;
- (void)watchMatchTicketDidTap;
- (void)kCoinExchangeDidTap;
- (void)diamondPurchaseDidTap;
- (void)loginButtonDidTap:(id)arg1;
- (void)clickReturn:(id)arg1;
- (void)data:(id)arg1 didFinishLoadWithError:(id)arg2;
- (void)dataWillStartLoad:(id)arg1;
- (void)userDidChange;
- (void)balanceDidChange;
- (void)dealloc;
- (void)viewDidLoad;
- (void)resetTableHeader;
- (void)viewWillAppear:(_Bool)arg1;
- (void)shouldReloadSinceErrorPressed;
- (_Bool)isEmpty;
- (id)tableViewDataLastUpdateTime:(id)arg1;
- (_Bool)tableViewHasMoreData:(id)arg1;
- (_Bool)tableViewDataIsLoading:(id)arg1;
- (void)tableViewShouldLoadMoreData:(id)arg1;
- (void)tableViewShouldRefreshData:(id)arg1;
- (_Bool)shouldShowSelfDefinedNavigationBar;
- (id)initWithParameters:(id)arg1;
- (id)currentParameters;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

