//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, QSAvatarView, QSMyMainUserInfo, QSRedPointView, UIButton, UIImageView, UILabel, UITapGestureRecognizer, UIView;
@protocol QSMyMainViewUserCellDelegate;

__attribute__((visibility("hidden")))
@interface QSMyMainViewUserCell : UITableViewCell
{
    _Bool _showMemberButton;
    id <QSMyMainViewUserCellDelegate> _delegate;
    UILabel *_nameLabel;
    NSString *_redPointString;
    QSAvatarView *_avatarImageView;
    UIImageView *_loginImageView;
    UIButton *_logonBtn;
    UIImageView *_vipImageView;
    UILabel *_serviceEndTimeLabel;
    UIButton *_memberBtn;
    UITapGestureRecognizer *_tapVipMedal;
    UILabel *_informLabel;
    UIView *_bottomSeparatorView;
    QSMyMainUserInfo *_cellModel;
    QSRedPointView *_redPointView;
}

+ (double)heightWithModel:(id)arg1;
@property(retain, nonatomic) QSRedPointView *redPointView; // @synthesize redPointView=_redPointView;
@property(retain, nonatomic) QSMyMainUserInfo *cellModel; // @synthesize cellModel=_cellModel;
@property(retain, nonatomic) UIView *bottomSeparatorView; // @synthesize bottomSeparatorView=_bottomSeparatorView;
@property(retain, nonatomic) UILabel *informLabel; // @synthesize informLabel=_informLabel;
@property(retain, nonatomic) UITapGestureRecognizer *tapVipMedal; // @synthesize tapVipMedal=_tapVipMedal;
@property(retain, nonatomic) UIButton *memberBtn; // @synthesize memberBtn=_memberBtn;
@property(retain, nonatomic) UILabel *serviceEndTimeLabel; // @synthesize serviceEndTimeLabel=_serviceEndTimeLabel;
@property(retain, nonatomic) UIImageView *vipImageView; // @synthesize vipImageView=_vipImageView;
@property(retain, nonatomic) UIButton *logonBtn; // @synthesize logonBtn=_logonBtn;
@property(retain, nonatomic) UIImageView *loginImageView; // @synthesize loginImageView=_loginImageView;
@property(retain, nonatomic) QSAvatarView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(copy, nonatomic) NSString *redPointString; // @synthesize redPointString=_redPointString;
@property(nonatomic) _Bool showMemberButton; // @synthesize showMemberButton=_showMemberButton;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak id <QSMyMainViewUserCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)goMemberCenter;
- (void)memberButtonPressed:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)logonPressed:(id)arg1;
- (void)refreshUserVipIcon;
- (void)updateRedPointHidden;
- (void)updateWithModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

