//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class QSAttendTagItem, QSWebImageView, UIButton, UILabel;

__attribute__((visibility("hidden")))
@interface QSMyAttendedTagCell : UITableViewCell
{
    QSAttendTagItem *_tagItem;
    QSWebImageView *_teamLogoImageView;
    UILabel *_teamNameLabel;
    UIButton *_followButton;
}

+ (double)height;
@property(retain, nonatomic) UIButton *followButton; // @synthesize followButton=_followButton;
@property(retain, nonatomic) UILabel *teamNameLabel; // @synthesize teamNameLabel=_teamNameLabel;
@property(retain, nonatomic) QSWebImageView *teamLogoImageView; // @synthesize teamLogoImageView=_teamLogoImageView;
@property(retain, nonatomic) QSAttendTagItem *tagItem; // @synthesize tagItem=_tagItem;
- (void).cxx_destruct;
- (void)setDataForFollowButton:(_Bool)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)clickedBtnFollow:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

