//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class QSAvatarView, QSMessageItem, QSPartedRichTextLabel, QSRichTextLabel, UIButton, UIImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface QSMyMessageCell : UITableViewCell
{
    QSMessageItem *_messageItem;
    CDUnknownBlockType _excuteWhenReplyBtnDidTapped;
    QSAvatarView *_avatarView;
    UILabel *_userNameLabel;
    UIImageView *_vipImageView;
    UILabel *_timeLabel;
    QSPartedRichTextLabel *_contentLabel;
    QSRichTextLabel *_sourceLabel;
    UIView *_sourceContentView;
    UIView *_separatorView;
    UIImageView *_reddotView;
    UIButton *_replyBtn;
}

+ (id)makeSourceTextInfo:(id)arg1;
+ (id)makeMutilTextInfos:(id)arg1;
+ (double)heightWithMessageItem:(id)arg1;
@property(retain, nonatomic) UIButton *replyBtn; // @synthesize replyBtn=_replyBtn;
@property(retain, nonatomic) UIImageView *reddotView; // @synthesize reddotView=_reddotView;
@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) UIView *sourceContentView; // @synthesize sourceContentView=_sourceContentView;
@property(retain, nonatomic) QSRichTextLabel *sourceLabel; // @synthesize sourceLabel=_sourceLabel;
@property(retain, nonatomic) QSPartedRichTextLabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIImageView *vipImageView; // @synthesize vipImageView=_vipImageView;
@property(retain, nonatomic) UILabel *userNameLabel; // @synthesize userNameLabel=_userNameLabel;
@property(retain, nonatomic) QSAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(copy, nonatomic) CDUnknownBlockType excuteWhenReplyBtnDidTapped; // @synthesize excuteWhenReplyBtnDidTapped=_excuteWhenReplyBtnDidTapped;
@property(retain, nonatomic) QSMessageItem *messageItem; // @synthesize messageItem=_messageItem;
- (void).cxx_destruct;
- (void)avatarViewDidTap:(id)arg1;
- (void)replyBtnDidTapped:(id)arg1;
- (void)layoutSubviews;
- (void)updateCell;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

