//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSMutableArray, NSString, QSNavigationAnimator, UINavigationController, UIPanGestureRecognizer, UIScreenEdgePanGestureRecognizer, UIView, UIViewController;

__attribute__((visibility("hidden")))
@interface QSNavigationController : QSViewController <UIGestureRecognizerDelegate>
{
    UIViewController *_currentViewController;
    UIPanGestureRecognizer *_panGesture;
    UIView *_navigationContentView;
    NSMutableArray *_viewControllers;
    QSNavigationAnimator *_pushAnimator;
    QSNavigationAnimator *_popAnimator;
    UIScreenEdgePanGestureRecognizer *_edgePanGesture;
    UINavigationController *_fuseNav;
    QSNavigationAnimator *_currentPopAnimator;
}

@property(nonatomic) __weak QSNavigationAnimator *currentPopAnimator; // @synthesize currentPopAnimator=_currentPopAnimator;
@property(retain, nonatomic) UINavigationController *fuseNav; // @synthesize fuseNav=_fuseNav;
@property(retain, nonatomic) UIScreenEdgePanGestureRecognizer *edgePanGesture; // @synthesize edgePanGesture=_edgePanGesture;
@property(retain, nonatomic) QSNavigationAnimator *popAnimator; // @synthesize popAnimator=_popAnimator;
@property(retain, nonatomic) QSNavigationAnimator *pushAnimator; // @synthesize pushAnimator=_pushAnimator;
@property(retain, nonatomic) NSMutableArray *viewControllers; // @synthesize viewControllers=_viewControllers;
@property(retain, nonatomic) UIView *navigationContentView; // @synthesize navigationContentView=_navigationContentView;
@property(retain, nonatomic) UIPanGestureRecognizer *panGesture; // @synthesize panGesture=_panGesture;
@property(nonatomic) __weak UIViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
- (void).cxx_destruct;
- (id)_popAnimatorWithFrom:(id)arg1 to:(id)arg2 gestrue:(id)arg3;
- (id)_pushAnimatorWithFrom:(id)arg1 to:(id)arg2 gesture:(id)arg3;
- (void)_setViewControllers:(id)arg1 removedControllers:(id)arg2 animated:(_Bool)arg3;
- (void)_removeViewController:(id)arg1;
- (void)_addViewController:(id)arg1;
- (void)_didShowControler:(id)arg1 from:(id)arg2 animator:(id)arg3;
- (void)_cancelShowControler:(id)arg1 from:(id)arg2 animator:(id)arg3;
- (void)_willShowControler:(id)arg1 from:(id)arg2 animator:(id)arg3;
- (void)onGestureRecognized:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)navigationBar;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
@property(readonly, nonatomic) UIViewController *topViewController;
@property(readonly, nonatomic) UIViewController *visibleViewController;
- (void)setViewControllers:(id)arg1 animated:(_Bool)arg2;
- (id)popToViewController:(id)arg1 animated:(_Bool)arg2;
- (id)popToRootViewControllerAnimated:(_Bool)arg1;
- (id)popViewControllerAnimated:(_Bool)arg1;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (_Bool)isAnimating;
- (void)viewWillLayoutSubviews;
- (void)resetDidAppearDate;
- (void)logSelfImmediately;
- (void)setShouldAutoLog:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)handleStatusBarFrameChange:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithRootViewController:(id)arg1;
- (id)childViewControllerForStatusBarHidden;
- (id)childViewControllerForStatusBarStyle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

