//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QSMatchSupportInfo, QSSupportCheckButton, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface QSNewSupportView : UIView
{
    UILabel *_lbhomeNumber;
    UILabel *_lbguestNumber;
    UIImageView *_homeValueImageView;
    UIImageView *_guestValueImageView;
    QSSupportCheckButton *_homeSupport;
    QSSupportCheckButton *_guestSupport;
    UILabel *_lbSupportTip;
    _Bool _preStartMode;
    _Bool _isTintStyle;
    QSMatchSupportInfo *_supportInfo;
}

+ (id)MakeSupportString:(id)arg1;
@property(nonatomic) _Bool isTintStyle; // @synthesize isTintStyle=_isTintStyle;
@property(retain, nonatomic) QSMatchSupportInfo *supportInfo; // @synthesize supportInfo=_supportInfo;
@property(nonatomic) _Bool preStartMode; // @synthesize preStartMode=_preStartMode;
- (void).cxx_destruct;
- (void)updateWithAnimated:(_Bool)arg1;
- (void)updateSupportStatus:(long long)arg1;
- (void)rightSupportPressed:(id)arg1;
- (void)leftSupportPressed:(id)arg1;
- (void)supportWithStatus:(long long)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)loadSubViews;
- (id)initWithFrame:(struct CGRect)arg1 isTintStyle:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)createSupportBgImage:(struct CGSize)arg1 isHome:(_Bool)arg2 color:(id)arg3;

@end

