//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSLogTableViewCell.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface QSNetLogTableViewCell : QSLogTableViewCell
{
    UILabel *_statusCodeLabel;
    UILabel *_pathLabel;
    UILabel *_hostLabel;
    UILabel *_timeLabel;
    UILabel *_durationLabel;
    UILabel *_sizeLabel;
}

+ (double)heightWithModel:(id)arg1;
+ (double)CellHightWithItem:(id)arg1;
@property(retain, nonatomic) UILabel *sizeLabel; // @synthesize sizeLabel=_sizeLabel;
@property(retain, nonatomic) UILabel *durationLabel; // @synthesize durationLabel=_durationLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *hostLabel; // @synthesize hostLabel=_hostLabel;
@property(retain, nonatomic) UILabel *pathLabel; // @synthesize pathLabel=_pathLabel;
@property(retain, nonatomic) UILabel *statusCodeLabel; // @synthesize statusCodeLabel=_statusCodeLabel;
- (void).cxx_destruct;
- (void)updateWithModel:(id)arg1;
- (void)layoutSubviews;
- (void)update;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

