//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSNewsArticleCell.h"

#import "QSPartedRichTextLabelDelegate-Protocol.h"

@class NSString, QSPartedRichTextLabel;

__attribute__((visibility("hidden")))
@interface QSNewsArticleTextCell : QSNewsArticleCell <QSPartedRichTextLabelDelegate>
{
    QSPartedRichTextLabel *_itemLabel;
}

+ (double)heightWithModel:(id)arg1;
@property(retain, nonatomic) QSPartedRichTextLabel *itemLabel; // @synthesize itemLabel=_itemLabel;
- (void).cxx_destruct;
- (void)richTextLabel:(id)arg1 didClickedWithPartInfo:(id)arg2;
- (void)updateWithModel:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

