//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDictionary, QSWebImageView, UILabel;

__attribute__((visibility("hidden")))
@interface QSNewsTopicInfoAdButton : UIView
{
    QSWebImageView *_imageView;
    UILabel *_titleLabel;
    NSDictionary *_jumpData;
}

@property(retain, nonatomic) NSDictionary *jumpData; // @synthesize jumpData=_jumpData;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) QSWebImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)onTap;
- (void)setImage:(id)arg1 title:(id)arg2 jumpData:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

