//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface QSNewsContentAttributeInfo : QSModel
{
    NSString *_attributeId;
    NSDictionary *_jumpData;
    NSString *_name;
    NSString *_showTitle;
    unsigned long long _startIndex;
    unsigned long long _textLen;
    NSString *_strType;
    NSString *_url;
    unsigned long long _type;
}

+ (id)propertyNameFromParsedKey:(id)arg1;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *strType; // @synthesize strType=_strType;
@property(nonatomic) unsigned long long textLen; // @synthesize textLen=_textLen;
@property(nonatomic) unsigned long long startIndex; // @synthesize startIndex=_startIndex;
@property(copy, nonatomic) NSString *showTitle; // @synthesize showTitle=_showTitle;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSDictionary *jumpData; // @synthesize jumpData=_jumpData;
@property(copy, nonatomic) NSString *attributeId; // @synthesize attributeId=_attributeId;
- (void).cxx_destruct;

@end

