//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, QSNewsTopicNewsInfo;

__attribute__((visibility("hidden")))
@interface QSNewsTopicNews : QSModel
{
    NSArray *_news;
    QSNewsTopicNewsInfo *_topicInfo;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) QSNewsTopicNewsInfo *topicInfo; // @synthesize topicInfo=_topicInfo;
@property(retain, nonatomic) NSArray *news; // @synthesize news=_news;
- (void).cxx_destruct;

@end

