//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel, UIView;

__attribute__((visibility("hidden")))
@interface QSNewsArticleShareTitleCell : UITableViewCell
{
    UILabel *_shareTitleLabel;
    UIView *_leftLine;
    UIView *_rightLine;
}

+ (_Bool)checkDataCorrectness:(id)arg1;
+ (double)cellHeightWithInfo:(id)arg1;
@property(retain, nonatomic) UIView *rightLine; // @synthesize rightLine=_rightLine;
@property(retain, nonatomic) UIView *leftLine; // @synthesize leftLine=_leftLine;
@property(retain, nonatomic) UILabel *shareTitleLabel; // @synthesize shareTitleLabel=_shareTitleLabel;
- (void).cxx_destruct;
- (void)updateWithInfo:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

