//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSNewsArticleSkinCell.h"

#import "QSTableViewCellProtocol-Protocol.h"

@class NSString, QSNewsContentItem, QSViewController;
@protocol QSNewsArticleCellDelegate;

__attribute__((visibility("hidden")))
@interface QSNewsArticleCell : QSNewsArticleSkinCell <QSTableViewCellProtocol>
{
    QSNewsContentItem *_contentItem;
    QSViewController<QSNewsArticleCellDelegate> *_viewController;
}

+ (double)heightWithModel:(id)arg1;
@property(nonatomic) __weak QSViewController<QSNewsArticleCellDelegate> *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) QSNewsContentItem *contentItem; // @synthesize contentItem=_contentItem;
- (void).cxx_destruct;
- (void)didEndDisplay;
- (void)updateWithModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

