//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "QSNewMessageViewDelegate-Protocol.h"

@class NSString, UIViewController;
@protocol QSNewMessageManagerDelegate;

__attribute__((visibility("hidden")))
@interface QSNewMessageManager : NSObject <QSNewMessageViewDelegate>
{
    id <QSNewMessageManagerDelegate> _delegate;
    NSString *_sceneForBossReport;
    NSString *_eventForBossReport;
    UIViewController *_viewController;
}

@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(copy, nonatomic) NSString *eventForBossReport; // @synthesize eventForBossReport=_eventForBossReport;
@property(copy, nonatomic) NSString *sceneForBossReport; // @synthesize sceneForBossReport=_sceneForBossReport;
@property(nonatomic) __weak id <QSNewMessageManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)closeButtonDidTapInNewMessageView:(id)arg1;
- (void)clearAllMessages;
- (void)tap:(id)arg1;
- (void)hideNewMessageView:(id)arg1;
- (void)showNewMessage:(id)arg1 inViewController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

