//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSString, QSNewsContentRelateNewsInfo, QSNewsContentSourceLink, QSNewsContentTopAd, QSNewsListItem, QSNewsTopicItem, QSNewsTopicNews, QSNewsVideoAlbumItem;

__attribute__((visibility("hidden")))
@interface QSNewsContentInfo : QSModel
{
    _Bool _isShare;
    NSArray *_content;
    QSNewsListItem *_listData;
    QSNewsTopicItem *_topic;
    QSNewsVideoAlbumItem *_videoAlbum;
    NSArray *_tagsInfo;
    NSArray *_attendTags;
    QSNewsTopicNews *_topicNews;
    NSString *_url;
    QSNewsContentRelateNewsInfo *_relate;
    double _updateFrequency;
    QSNewsContentTopAd *_topAd;
    QSNewsContentSourceLink *_sourceLink;
}

@property(retain, nonatomic) QSNewsContentSourceLink *sourceLink; // @synthesize sourceLink=_sourceLink;
@property(retain, nonatomic) QSNewsContentTopAd *topAd; // @synthesize topAd=_topAd;
@property(nonatomic) double updateFrequency; // @synthesize updateFrequency=_updateFrequency;
@property(nonatomic) _Bool isShare; // @synthesize isShare=_isShare;
@property(retain, nonatomic) QSNewsContentRelateNewsInfo *relate; // @synthesize relate=_relate;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) QSNewsTopicNews *topicNews; // @synthesize topicNews=_topicNews;
@property(retain, nonatomic) NSArray *attendTags; // @synthesize attendTags=_attendTags;
@property(retain, nonatomic) NSArray *tagsInfo; // @synthesize tagsInfo=_tagsInfo;
@property(retain, nonatomic) QSNewsVideoAlbumItem *videoAlbum; // @synthesize videoAlbum=_videoAlbum;
@property(retain, nonatomic) QSNewsTopicItem *topic; // @synthesize topic=_topic;
@property(retain, nonatomic) QSNewsListItem *listData; // @synthesize listData=_listData;
@property(retain, nonatomic) NSArray *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (void)manualResetWithInfo:(id)arg1;

@end

