//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSVideoListController.h"

#import "QSBaseDataDelegate-Protocol.h"

@class NSString, QSNormalVideoListData, QSVideoLikeData;

__attribute__((visibility("hidden")))
@interface QSNormalVideoListController : QSVideoListController <QSBaseDataDelegate>
{
    _Bool _fromDropdownList;
    CDUnknownBlockType _dataUpdateBlock;
    QSNormalVideoListData *_videoData;
    QSVideoLikeData *_videoLikeData;
}

@property(retain, nonatomic) QSVideoLikeData *videoLikeData; // @synthesize videoLikeData=_videoLikeData;
@property(retain, nonatomic) QSNormalVideoListData *videoData; // @synthesize videoData=_videoData;
@property(nonatomic) _Bool fromDropdownList; // @synthesize fromDropdownList=_fromDropdownList;
@property(copy, nonatomic) CDUnknownBlockType dataUpdateBlock; // @synthesize dataUpdateBlock=_dataUpdateBlock;
- (void).cxx_destruct;
- (void)mediaPlayerViewController:(id)arg1 willShowUI:(_Bool)arg2 animate:(_Bool)arg3;
- (struct CGRect)frameForPresentedWarpperView;
- (void)showDropList;
- (void)data:(id)arg1 didFinishLoadWithError:(id)arg2;
- (void)dataWillStartLoad:(id)arg1;
- (void)shouldReloadSinceErrorPressed;
- (void)autoLoadMore;
- (id)tableViewDataLastUpdateTime:(id)arg1;
- (void)tableViewShouldLoadMoreData:(id)arg1;
- (_Bool)tableViewHasMoreData:(id)arg1;
- (void)tableViewShouldRefreshData:(id)arg1;
- (_Bool)tableViewDataIsLoading:(id)arg1;
- (_Bool)isEmpty;
- (void)playPreferredPlayingCell;
- (void)setCurrentPlayingVideoCell:(id)arg1;
- (void)setPreferredPlayingCell:(id)arg1;
- (void)playNextVisualItem;
- (void)cellAction:(id)arg1 performedWithData:(id)arg2 inCell:(id)arg3;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (_Bool)shouldStopWhenScroll;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)autoPlay;
- (_Bool)shouldShowSelfDefinedNavigationBar;
- (id)newPageDescription;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

