//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSOlympicPlayer : QSModel
{
    NSString *_playerId;
    long long _playerType;
    NSString *_cnName;
    NSString *_enName;
    NSString *_badge;
    NSString *_rank;
    NSString *_subscripts;
    NSString *_logo;
    NSString *_introUrl;
}

+ (id)propertyNameFromParsedKey:(id)arg1;
@property(copy, nonatomic) NSString *introUrl; // @synthesize introUrl=_introUrl;
@property(copy, nonatomic) NSString *logo; // @synthesize logo=_logo;
@property(copy, nonatomic) NSString *subscripts; // @synthesize subscripts=_subscripts;
@property(copy, nonatomic) NSString *rank; // @synthesize rank=_rank;
@property(copy, nonatomic) NSString *badge; // @synthesize badge=_badge;
@property(copy, nonatomic) NSString *enName; // @synthesize enName=_enName;
@property(copy, nonatomic) NSString *cnName; // @synthesize cnName=_cnName;
@property(nonatomic) long long playerType; // @synthesize playerType=_playerType;
@property(copy, nonatomic) NSString *playerId; // @synthesize playerId=_playerId;
- (void).cxx_destruct;

@end

