//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSOlympicScheduleItemView.h"

@class QSMatchItem, UIColor;

__attribute__((visibility("hidden")))
@interface QSOlympicScheduleDataView : QSOlympicScheduleItemView
{
    QSMatchItem *_matchItem;
    UIColor *_textColor;
}

+ (Class)playerViewClass;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) QSMatchItem *matchItem; // @synthesize matchItem=_matchItem;
- (void).cxx_destruct;
- (void)createSubviews;

@end

