//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSString, QSWebImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface QSOlympicCategoryCell : UICollectionViewCell
{
    NSString *_categoryIconUrl;
    QSWebImageView *_imageView;
    UILabel *_nameLabel;
    UIView *_bottomLine;
    UIView *_rightLine;
}

+ (id)cellIdentifier;
@property(retain, nonatomic) UIView *rightLine; // @synthesize rightLine=_rightLine;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) QSWebImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) NSString *categoryIconUrl; // @synthesize categoryIconUrl=_categoryIconUrl;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
@property(nonatomic) struct CGRect bottomLineFrame; // @dynamic bottomLineFrame;
@property(nonatomic) struct CGRect rightLineFrame; // @dynamic rightLineFrame;
- (struct CGRect)leftLineFrame;
@property(copy, nonatomic) NSString *categoryName; // @dynamic categoryName;
- (void)createSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

