//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSStatedData.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface QSOlympicCategoryData : QSStatedData
{
    NSString *_columnId;
    NSString *_columnVersion;
}

@property(copy, nonatomic) NSString *columnVersion; // @synthesize columnVersion=_columnVersion;
@property(copy, nonatomic) NSString *columnId; // @synthesize columnId=_columnId;
- (void).cxx_destruct;
- (_Bool)cacheExists;
- (double)cacheExpireTime;
- (void)resetFromCacheObject:(id)arg1;
@property(readonly, nonatomic) NSArray *categorys; // @dynamic categorys;
- (void)resetWithResponseModel:(id)arg1;
- (id)httpURLComponents;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)identifier;

@end

