//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSContainerViewController.h"

#import "QSCustomTabBarDelegate-Protocol.h"
#import "QSPushViewControllerProtocol-Protocol.h"

@class NSString, QSDetailTabBar;

__attribute__((visibility("hidden")))
@interface QSPersonalConsumeRecordViewController : QSContainerViewController <QSCustomTabBarDelegate, QSPushViewControllerProtocol>
{
    long long _defaultConsumeRecordType;
    QSDetailTabBar *_topTabBar;
}

+ (id)allViewControllerType;
@property(retain, nonatomic) QSDetailTabBar *topTabBar; // @synthesize topTabBar=_topTabBar;
@property(nonatomic) long long defaultConsumeRecordType; // @synthesize defaultConsumeRecordType=_defaultConsumeRecordType;
- (void).cxx_destruct;
- (void)tabBar:(id)arg1 didSelectSameItemAtIndex:(long long)arg2;
- (void)tabBar:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (id)tabBar:(id)arg1 titleForItemAtIndex:(long long)arg2;
- (unsigned long long)numberOfItemsInTabBar:(id)arg1;
- (void)handleBackPress:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)layoutAllContentViews;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)processMemoryWarning;
- (id)viewControllerAtIndex:(long long)arg1;
- (long long)defaultContentViewControllerIndex;
- (long long)countOfContentViewControllers;
- (_Bool)shouldShowSelfDefinedNavigationBar;
- (id)initWithParameters:(id)arg1;
- (id)currentParameters;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

