//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class QSPhotoAssetPreviewBottomView;

@protocol QSPhotoAssetPreviewBottomViewDelegate <NSObject>

@optional
- (void)didTapEditButtonInView:(QSPhotoAssetPreviewBottomView *)arg1;
- (void)didTapCompleteButtonInView:(QSPhotoAssetPreviewBottomView *)arg1;
@end

