//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class AVPlayer, AVPlayerLayer, PHAsset, QSPhotoAssetPreviewImageView, UIButton, UIImageView, UILabel;
@protocol QSPhotoAssetVideoPreviewCellDelegate;

__attribute__((visibility("hidden")))
@interface QSPhotoAssetVideoPreviewCell : UICollectionViewCell
{
    id <QSPhotoAssetVideoPreviewCellDelegate> _delegate;
    double _topBarOffset;
    PHAsset *_assetModel;
    AVPlayer *_player;
    AVPlayerLayer *_playerLayer;
    QSPhotoAssetPreviewImageView *_photoView;
    UIButton *_playBtn;
    UIImageView *_playImageView;
    UILabel *_topTipLable;
}

@property(retain, nonatomic) UILabel *topTipLable; // @synthesize topTipLable=_topTipLable;
@property(retain, nonatomic) UIImageView *playImageView; // @synthesize playImageView=_playImageView;
@property(retain, nonatomic) UIButton *playBtn; // @synthesize playBtn=_playBtn;
@property(retain, nonatomic) QSPhotoAssetPreviewImageView *photoView; // @synthesize photoView=_photoView;
@property(retain, nonatomic) AVPlayerLayer *playerLayer; // @synthesize playerLayer=_playerLayer;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) PHAsset *assetModel; // @synthesize assetModel=_assetModel;
@property(nonatomic) double topBarOffset; // @synthesize topBarOffset=_topBarOffset;
@property(nonatomic) __weak id <QSPhotoAssetVideoPreviewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)willResignActive:(id)arg1;
- (void)playbackFinished:(id)arg1;
@property(readonly, nonatomic) _Bool didGetPlayerItem; // @dynamic didGetPlayerItem;
- (void)clearPlayer;
- (void)pausePlayer;
- (void)playBtnClicked:(id)arg1;
- (void)updateTopTipWithText:(id)arg1;
- (void)updateWithModel:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

