//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface QSPlayerReporterCounter : NSObject
{
    NSMutableArray *_cachingStateArray;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *cachingStateArray; // @synthesize cachingStateArray=_cachingStateArray;
- (void).cxx_destruct;
- (void)push:(id)arg1;
- (void)clear;
- (id)shouldReport;
- (id)init;

@end

