//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class QSAvatarView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface QSPlayerRanklistSoccerPlayerContentCell : UITableViewCell
{
    _Bool _showFullSeparatorLine;
    UIView *_seperatorLine;
    UILabel *_rankLabel;
    QSAvatarView *_playerImageView;
    UILabel *_nameLabel;
    UILabel *_teamNameLabel;
    UILabel *_scoreLabel;
}

+ (id)defaultCellIdentifier;
+ (double)height;
@property(retain, nonatomic) UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
@property(retain, nonatomic) UILabel *teamNameLabel; // @synthesize teamNameLabel=_teamNameLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) QSAvatarView *playerImageView; // @synthesize playerImageView=_playerImageView;
@property(retain, nonatomic) UILabel *rankLabel; // @synthesize rankLabel=_rankLabel;
@property(retain, nonatomic) UIView *seperatorLine; // @synthesize seperatorLine=_seperatorLine;
@property(nonatomic) _Bool showFullSeparatorLine; // @synthesize showFullSeparatorLine=_showFullSeparatorLine;
- (void).cxx_destruct;
- (void)updateWithContentItem:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

