//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface QSPlayerReporter : NSObject
{
    NSString *_pid;
    NSString *_liveId;
    NSMutableArray *_stateArray;
}

@property(retain, nonatomic) NSMutableArray *stateArray; // @synthesize stateArray=_stateArray;
@property(retain, nonatomic) NSString *liveId; // @synthesize liveId=_liveId;
@property(retain, nonatomic) NSString *pid; // @synthesize pid=_pid;
- (void).cxx_destruct;
- (id)getParams:(id)arg1 time:(double)arg2 type:(long long)arg3;
- (void)report:(long long)arg1 time:(double)arg2;
- (void)onCatchPlayerError:(int)arg1;
- (id)init;

@end

