//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface QSPlayerRanklistDetailContentInfo : QSModel
{
    NSArray *_head;
    NSArray *_row;
    NSArray *_adLogoInfo;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) NSArray *adLogoInfo; // @synthesize adLogoInfo=_adLogoInfo;
@property(retain, nonatomic) NSArray *row; // @synthesize row=_row;
@property(retain, nonatomic) NSArray *head; // @synthesize head=_head;
- (void).cxx_destruct;

@end

