//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSDictionary;

__attribute__((visibility("hidden")))
@interface QSPlayerRanklistBasketballContentInfo : QSModel
{
    NSArray *_tabIndex;
    NSDictionary *_tabData;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) NSDictionary *tabData; // @synthesize tabData=_tabData;
@property(retain, nonatomic) NSArray *tabIndex; // @synthesize tabIndex=_tabIndex;
- (void).cxx_destruct;
- (_Bool)manualSetValue:(id)arg1 forKey:(id)arg2;

@end

