//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSFullScreenView.h"

#import "QSWebViewDelegate-Protocol.h"

@class NSString, QSWebView, UIView;

__attribute__((visibility("hidden")))
@interface QSPropsRankKickSuccessView : QSFullScreenView <QSWebViewDelegate>
{
    NSString *_jsonData;
    NSString *_url;
    QSWebView *_webView;
    UIView *_bgView;
    CDUnknownBlockType _completionBlock;
}

+ (void)showWithUrl:(id)arg1 andData:(id)arg2 completion:(CDUnknownBlockType)arg3;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) QSWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *jsonData; // @synthesize jsonData=_jsonData;
- (void).cxx_destruct;
- (void)dismiss;
- (void)show;
- (_Bool)qsWebView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (id)allParamentsInfoWithRequest:(id)arg1;
- (void)reloadWebView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

