//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSContainerViewController.h"

#import "QSBaseDataDelegate-Protocol.h"
#import "QSPresentedNavigationBarDataSource-Protocol.h"
#import "QSPropsRanklistDetailViewControllerDelegate-Protocol.h"
#import "QSPushViewControllerProtocol-Protocol.h"

@class NSMapTable, NSString, QSMatchItem, QSPropsRanklistDetailData, QSSegmentedControl, UIView;

__attribute__((visibility("hidden")))
@interface QSPropsRanklistContainerViewController : QSContainerViewController <QSPushViewControllerProtocol, QSBaseDataDelegate, QSPresentedNavigationBarDataSource, QSPropsRanklistDetailViewControllerDelegate>
{
    NSString *_targetCode;
    QSMatchItem *_matchItem;
    NSString *_userId;
    QSPropsRanklistDetailData *_propsRanklistDetailData;
    UIView *_topView;
    QSSegmentedControl *_segmentedControl;
    NSMapTable *_contentViewControllers;
    unsigned long long _currentNumberOfRankList;
}

+ (id)allViewControllerType;
@property(nonatomic) unsigned long long currentNumberOfRankList; // @synthesize currentNumberOfRankList=_currentNumberOfRankList;
@property(retain, nonatomic) NSMapTable *contentViewControllers; // @synthesize contentViewControllers=_contentViewControllers;
@property(retain, nonatomic) QSSegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) QSPropsRanklistDetailData *propsRanklistDetailData; // @synthesize propsRanklistDetailData=_propsRanklistDetailData;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(retain, nonatomic) QSMatchItem *matchItem; // @synthesize matchItem=_matchItem;
@property(copy, nonatomic) NSString *targetCode; // @synthesize targetCode=_targetCode;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)middleBarItemDidTap;
- (void)leftBarItemDidTap;
- (void)data:(id)arg1 didFinishLoadWithError:(id)arg2;
- (void)dataWillStartLoad:(id)arg1;
- (id)middleBarButtonItemForPresentedNavigationBar;
- (id)titleForPresentedNavigationBar;
- (void)segmentedControlValueDidChange:(id)arg1;
- (void)backButtonDidTap:(id)arg1;
- (id)propsRanklistDetailViewControllerLastUpdateTime:(id)arg1;
- (void)propsRanklistDetailViewControllerWantsToRefresh:(id)arg1;
- (_Bool)propsRanklistDetailViewControllerIsRefreshing:(id)arg1;
- (void)propsRanklistDetailViewController:(id)arg1 didFinishKickOffUserWithUserId:(id)arg2 kickOffInfo:(id)arg3;
- (id)createEmptyView;
- (_Bool)isEmpty;
- (void)viewDidLoad;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)layoutAllContentViews;
- (void)refreshController;
- (void)reloadAllController;
- (long long)defaultContentViewControllerIndex;
- (id)viewControllerAtIndex:(long long)arg1;
- (void)shouldReloadSinceErrorPressed;
- (long long)countOfContentViewControllers;
- (_Bool)shouldShowSelfDefinedNavigationBar;
- (id)externInfoForBossReporter;
- (_Bool)needBossReporter;
- (id)initWithParameters:(id)arg1;
- (id)currentParameters;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

