//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, QSMediaFormatInfo, QSSportsMediaCameraItem;

__attribute__((visibility("hidden")))
@interface QSProjectedMediaItem : NSObject
{
    NSString *_url;
    NSString *_title;
    NSString *_liveId;
    QSMediaFormatInfo *_formatInfo;
    QSSportsMediaCameraItem *_cameraItem;
    NSString *_mid;
}

+ (id)mediaItemWithURL:(id)arg1 liveMediaItem:(id)arg2 matchId:(id)arg3 formatInfo:(id)arg4 cameraItem:(id)arg5;
@property(copy, nonatomic) NSString *mid; // @synthesize mid=_mid;
@property(retain, nonatomic) QSSportsMediaCameraItem *cameraItem; // @synthesize cameraItem=_cameraItem;
@property(retain, nonatomic) QSMediaFormatInfo *formatInfo; // @synthesize formatInfo=_formatInfo;
@property(copy, nonatomic) NSString *liveId; // @synthesize liveId=_liveId;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (_Bool)isSameWithLiveMediaItem:(id)arg1 formatInfo:(id)arg2;

@end

