//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSString, QSPropsRanklistDetailRankRuleInfo;

__attribute__((visibility("hidden")))
@interface QSPropsRanklistDetailInfo : QSModel
{
    _Bool _beatAble;
    NSString *_targetCode;
    NSString *_mid;
    NSString *_seasonId;
    NSString *_title;
    NSString *_cartUrl;
    QSPropsRanklistDetailRankRuleInfo *_rankRule;
    NSArray *_rankList;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(nonatomic) _Bool beatAble; // @synthesize beatAble=_beatAble;
@property(retain, nonatomic) NSArray *rankList; // @synthesize rankList=_rankList;
@property(retain, nonatomic) QSPropsRanklistDetailRankRuleInfo *rankRule; // @synthesize rankRule=_rankRule;
@property(copy, nonatomic) NSString *cartUrl; // @synthesize cartUrl=_cartUrl;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *seasonId; // @synthesize seasonId=_seasonId;
@property(copy, nonatomic) NSString *mid; // @synthesize mid=_mid;
@property(copy, nonatomic) NSString *targetCode; // @synthesize targetCode=_targetCode;
- (void).cxx_destruct;

@end

