//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class QSPropsRanklistRankItem, QSWebImageView, UIImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface QSPropsRanklistCell : UITableViewCell
{
    QSWebImageView *_iconView;
    UILabel *_nameLabel;
    QSWebImageView *_prizeIconView;
    UILabel *_usernameLabel;
    UILabel *_contributionValueLabel;
    UIImageView *_arrowView;
    QSPropsRanklistRankItem *_info;
    UIView *_separatorLine;
    _Bool _separatorLineHidden;
}

+ (double)height;
@property(nonatomic) _Bool separatorLineHidden; // @synthesize separatorLineHidden=_separatorLineHidden;
- (void).cxx_destruct;
- (void)updateWithInfo:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

