//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, QSGuessUserAvatarView, UIButton, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface QSPreMatchGuessRandAndRecordCell : UITableViewCell
{
    QSGuessUserAvatarView *_iconView;
    UILabel *_nameLabel;
    UIImageView *_rightArrow1;
    UIButton *_goRecordButton;
    NSString *_defaultTip;
    NSString *_mid;
}

+ (double)height;
@property(retain, nonatomic) NSString *mid; // @synthesize mid=_mid;
@property(retain, nonatomic) NSString *defaultTip; // @synthesize defaultTip=_defaultTip;
- (void).cxx_destruct;
- (void)update;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

