//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPresentationController.h>

@class UIView;

__attribute__((visibility("hidden")))
@interface QSPresentationController : UIPresentationController
{
    UIView *_dimingView;
    struct CGRect _presentationFrame;
}

@property(nonatomic) struct CGRect presentationFrame; // @synthesize presentationFrame=_presentationFrame;
@property(retain, nonatomic) UIView *dimingView; // @synthesize dimingView=_dimingView;
- (void).cxx_destruct;
- (id)presentedView;
- (struct CGRect)frameOfPresentedViewInContainerView;
- (void)dismissalTransitionDidEnd:(_Bool)arg1;
- (void)dismissalTransitionWillBegin;
- (void)presentationTransitionDidEnd:(_Bool)arg1;
- (void)presentationTransitionWillBegin;
- (void)tap:(id)arg1;
- (id)initWithPresentedViewController:(id)arg1 presentingViewController:(id)arg2 presentationFrame:(struct CGRect)arg3;

@end

