//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSBusEvent.h"

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface QSPushViewEvent : QSBusEvent
{
    long long _type;
    NSDictionary *_param;
}

+ (id)viewControllerWithType:(long long)arg1 parameters:(id)arg2;
+ (void)didConsumeEventFromBus:(id)arg1;
+ (id)triggerDirectlyWithType:(long long)arg1 parameters:(id)arg2;
+ (id)triggerDirectlyWithInfo:(id)arg1;
+ (void)triggerWithType:(long long)arg1 parameters:(id)arg2;
+ (void)triggerWithInfo:(id)arg1;
+ (void)gotoWeixinProgram:(id)arg1 path:(id)arg2;
+ (void)load;
+ (id)allViewControllerTypes;
@property(retain, nonatomic) NSDictionary *param; // @synthesize param=_param;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

