//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSString, QSRanklistComment, QSRanklistConfig;

__attribute__((visibility("hidden")))
@interface QSRanklistInfo : QSModel
{
    long long _type;
    NSString *_title;
    NSArray *_rank;
    QSRanklistComment *_comment;
    QSRanklistConfig *_config;
    NSArray *_adLogoInfo;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) NSArray *adLogoInfo; // @synthesize adLogoInfo=_adLogoInfo;
@property(retain, nonatomic) QSRanklistConfig *config; // @synthesize config=_config;
@property(retain, nonatomic) QSRanklistComment *comment; // @synthesize comment=_comment;
@property(retain, nonatomic) NSArray *rank; // @synthesize rank=_rank;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (unsigned long long)numberOfItems;
- (unsigned long long)numberOfHeads;
- (unsigned long long)numberOfRanks;

@end

