//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class NSArray, NSDictionary;

__attribute__((visibility("hidden")))
@interface QSRanklistLabel : UILabel
{
    NSArray *_myRanklistTitleInfoArray;
    NSDictionary *_textInfo;
    double _totalWidth;
}

@property(nonatomic) double totalWidth; // @synthesize totalWidth=_totalWidth;
@property(retain, nonatomic) NSDictionary *textInfo; // @synthesize textInfo=_textInfo;
@property(retain, nonatomic) NSArray *myRanklistTitleInfoArray; // @synthesize myRanklistTitleInfoArray=_myRanklistTitleInfoArray;
- (void).cxx_destruct;
- (void)drawTextInRect:(struct CGRect)arg1;
- (void)update;

@end

