//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSRankTab : QSModel
{
    _Bool _isTeamRank;
    long long _type;
    NSString *_desc;
    NSString *_columnId;
    NSString *_competitionId;
    NSString *_url;
    long long _jumpType;
}

@property(nonatomic) long long jumpType; // @synthesize jumpType=_jumpType;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *competitionId; // @synthesize competitionId=_competitionId;
@property(copy, nonatomic) NSString *columnId; // @synthesize columnId=_columnId;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(nonatomic) _Bool isTeamRank; // @synthesize isTeamRank=_isTeamRank;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

