//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSPagedData.h"

@interface QSRelyonPrefixPagedData : QSPagedData
{
}

- (void)stateMachine:(id)arg1 eventDidHappen:(id)arg2;
- (void)stateMachine:(id)arg1 eventWillHappen:(id)arg2;
- (void)stateMachine:(id)arg1 enterState:(unsigned long long)arg2;
- (void)loadPrefixData;
- (void)resetWithPrefixResponseData:(id)arg1;
- (id)prefixHttpURLComponents;
- (void)refreshStateAction;
- (unsigned long long)refreshState;
- (void)initStateMachine;
- (unsigned long long)updateState;

@end

