//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KKMediaRootViewController.h"

@class NSArray, QSMediaFormatInfo;
@protocol QSRootPlayerViewControllerDelegate;

@interface QSRootPlayerViewController : KKMediaRootViewController
{
    id <QSRootPlayerViewControllerDelegate> _delegate;
    QSMediaFormatInfo *_currentMediaFormat;
    NSArray *_mediaFormatList;
}

@property(retain, nonatomic) NSArray *mediaFormatList; // @synthesize mediaFormatList=_mediaFormatList;
@property(retain, nonatomic) QSMediaFormatInfo *currentMediaFormat; // @synthesize currentMediaFormat=_currentMediaFormat;
@property(nonatomic) __weak id <QSRootPlayerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)willAnimateSecondHalfOfRotationFromInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)didAnimateFirstHalfOfRotationToInterfaceOrientation:(long long)arg1;
- (void)willAnimateFirstHalfOfRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)resumePlayer;
- (void)pause;
- (void)play;
- (void)didReceiveMemoryWarning;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)startMediaPlayToPlayAgainWithReason:(long long)arg1 withError:(id)arg2;
- (void)playerControlPlayerDidSinggleTag:(id)arg1;
- (void)setMuted:(_Bool)arg1;
- (long long)getLiveTime;
- (long long)getSeebackCurrentTime;
- (long long)getSeebackCanWatchStartTime;
- (long long)getSeebackStartTime;
- (_Bool)isSeeBackMode;
- (_Bool)canSeeBack;
- (void)seeBackSeekToTime:(long long)arg1;
- (void)seeBackChangeToLive;

@end

