//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSTabbedContainerViewController.h"

#import "QSTabBarContainedControllerDelegate-Protocol.h"
#import "QSTeamFilterViewControllerDelegate-Protocol.h"

@class NSString, QSAttendTagItem, QSWebImageView, UIButton;

__attribute__((visibility("hidden")))
@interface QSRootScheduleContainerViewController : QSTabbedContainerViewController <QSTeamFilterViewControllerDelegate, QSTabBarContainedControllerDelegate>
{
    UIButton *_filterButton;
    QSWebImageView *_teamIconView;
    UIButton *_clearButton;
    QSAttendTagItem *_currentTagItem;
}

@property(retain, nonatomic) QSAttendTagItem *currentTagItem; // @synthesize currentTagItem=_currentTagItem;
@property(retain, nonatomic) UIButton *clearButton; // @synthesize clearButton=_clearButton;
@property(retain, nonatomic) QSWebImageView *teamIconView; // @synthesize teamIconView=_teamIconView;
@property(retain, nonatomic) UIButton *filterButton; // @synthesize filterButton=_filterButton;
- (void).cxx_destruct;
- (void)tabbarPressedAgain;
- (id)viewControllerAtIndex:(long long)arg1;
- (long long)countOfContentViewControllers;
- (long long)defaultContentViewControllerIndex;
- (id)titleForViewControllerAtIndex:(unsigned long long)arg1;
- (void)setCurrentSelectedIndex:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)filterSchedules;
- (void)updateFilterControls;
- (void)clearFilteredSchedules;
- (void)filterSchedulesWithTagItem:(id)arg1;
- (void)userDidTapEditButtonInTeamFilterViewController:(id)arg1;
- (void)userDidTapCloseButtonInTeamFilterViewController:(id)arg1;
- (void)teamFilterViewController:(id)arg1 userDidSelectTeamWithTagItem:(id)arg2;
- (void)filterButtonDidTap:(id)arg1;
- (void)reloadAllController;
- (void)updateFilterState;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)followedTeamsDidChanged;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

