//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSRoundMapAd : QSModel
{
    NSString *_type;
    NSString *_widthRatio;
    NSString *_heightRatio;
    NSString *_adIcon;
    NSString *_adUrl;
}

@property(retain, nonatomic) NSString *adUrl; // @synthesize adUrl=_adUrl;
@property(retain, nonatomic) NSString *adIcon; // @synthesize adIcon=_adIcon;
@property(retain, nonatomic) NSString *heightRatio; // @synthesize heightRatio=_heightRatio;
@property(retain, nonatomic) NSString *widthRatio; // @synthesize widthRatio=_widthRatio;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

