//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSCircledData.h"

#import "QSAutoUpdateProtocol-Protocol.h"

@class NSString, QSMatchTimelineInfo;

__attribute__((visibility("hidden")))
@interface QSScheduleData : QSCircledData <QSAutoUpdateProtocol>
{
    _Bool _canForceUpdate;
    _Bool _shouldAutoScrollToToday;
    _Bool _needForceUpdate;
    NSString *_customFromDateStr;
    NSString *_scrollToDateStr;
}

+ (_Bool)cleanCacheWhenUserChanged;
@property(nonatomic) _Bool needForceUpdate; // @synthesize needForceUpdate=_needForceUpdate;
@property(nonatomic) _Bool shouldAutoScrollToToday; // @synthesize shouldAutoScrollToToday=_shouldAutoScrollToToday;
@property(retain, nonatomic) NSString *scrollToDateStr; // @synthesize scrollToDateStr=_scrollToDateStr;
@property(retain, nonatomic) NSString *customFromDateStr; // @synthesize customFromDateStr=_customFromDateStr;
@property(nonatomic) _Bool canForceUpdate; // @synthesize canForceUpdate=_canForceUpdate;
- (void).cxx_destruct;
- (_Bool)resetWithPreviousModels:(id)arg1;
- (id)loadPreviousHttpURLComponents;
- (_Bool)resetWithMoreModels:(id)arg1;
- (id)loadMoreHttpURLComponents;
- (void)resetWithResponseModel:(id)arg1;
- (id)httpURLComponents;
- (void)onAutoUpdate;
- (void)resetWithAutoRefreshModels:(id)arg1;
- (id)autoUpdateHttpURLComponents;
- (double)updateTimeInterval;
- (_Bool)updateTimeTriggered;
- (id)identifier;
@property(readonly, nonatomic) __weak QSMatchTimelineInfo *timelineInfo; // @dynamic timelineInfo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

