//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSMatchListBaseCell.h"

#import "QSHomePageFeedCellBossReportProtocol-Protocol.h"
#import "QSHomeRecommendCellProtocol-Protocol.h"

@class NSString, QSHomeRecommendBaseInfo, QSScheduleTeamView, UIButton, UIImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface QSScheduleItemCell : QSMatchListBaseCell <QSHomeRecommendCellProtocol, QSHomePageFeedCellBossReportProtocol>
{
    UIImageView *_winterOlyIsChinaImageView;
    UIView *_winterOlyRankContainerView;
    UILabel *_matchDateLabel;
    UIImageView *_vipTagView;
    UILabel *_matchDescLabel;
    QSScheduleTeamView *_homeTeamView;
    QSScheduleTeamView *_awayTeamView;
    UILabel *_homeScore;
    UILabel *_awayScore;
    UIView *_rightContainerView;
    UILabel *_commentatorLabel;
    UIImageView *_rightVideoImageView;
    UILabel *_rightTipLabel;
    UILabel *_rightSubTipLabel;
    UIButton *_adButton;
    UILabel *_adTitleLabel;
    UIImageView *_adTipImageView;
    UIView *_underlineView;
    QSHomeRecommendBaseInfo *_info;
}

+ (double)cellHeightWithMoreMatchItem:(id)arg1;
+ (_Bool)isAdVisible:(id)arg1;
+ (double)cellHeightWithInfo:(id)arg1;
+ (_Bool)checkDataCorrectness:(id)arg1;
@property(retain, nonatomic) QSHomeRecommendBaseInfo *info; // @synthesize info=_info;
@property(retain, nonatomic) UIView *underlineView; // @synthesize underlineView=_underlineView;
@property(retain, nonatomic) UIImageView *adTipImageView; // @synthesize adTipImageView=_adTipImageView;
@property(retain, nonatomic) UILabel *adTitleLabel; // @synthesize adTitleLabel=_adTitleLabel;
@property(retain, nonatomic) UIButton *adButton; // @synthesize adButton=_adButton;
@property(retain, nonatomic) UILabel *rightSubTipLabel; // @synthesize rightSubTipLabel=_rightSubTipLabel;
@property(retain, nonatomic) UILabel *rightTipLabel; // @synthesize rightTipLabel=_rightTipLabel;
@property(retain, nonatomic) UIImageView *rightVideoImageView; // @synthesize rightVideoImageView=_rightVideoImageView;
@property(retain, nonatomic) UILabel *commentatorLabel; // @synthesize commentatorLabel=_commentatorLabel;
@property(retain, nonatomic) UIView *rightContainerView; // @synthesize rightContainerView=_rightContainerView;
@property(retain, nonatomic) UILabel *awayScore; // @synthesize awayScore=_awayScore;
@property(retain, nonatomic) UILabel *homeScore; // @synthesize homeScore=_homeScore;
@property(retain, nonatomic) QSScheduleTeamView *awayTeamView; // @synthesize awayTeamView=_awayTeamView;
@property(retain, nonatomic) QSScheduleTeamView *homeTeamView; // @synthesize homeTeamView=_homeTeamView;
@property(retain, nonatomic) UILabel *matchDescLabel; // @synthesize matchDescLabel=_matchDescLabel;
@property(retain, nonatomic) UIImageView *vipTagView; // @synthesize vipTagView=_vipTagView;
@property(retain, nonatomic) UILabel *matchDateLabel; // @synthesize matchDateLabel=_matchDateLabel;
@property(retain, nonatomic) UIView *winterOlyRankContainerView; // @synthesize winterOlyRankContainerView=_winterOlyRankContainerView;
@property(retain, nonatomic) UIImageView *winterOlyIsChinaImageView; // @synthesize winterOlyIsChinaImageView=_winterOlyIsChinaImageView;
- (void).cxx_destruct;
- (void)refreshPartCommentatorUIAfterRightModule;
- (void)setNormalMatchState;
- (void)setDetailDateAndTypeMode:(_Bool)arg1;
- (void)removeKVO;
- (void)addKVO;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSeparatorLineHidden:(_Bool)arg1;
- (void)resetSeperatorLineWithWetherIsLastMatchItem:(_Bool)arg1;
- (void)refreshTeamLogoNameScore_ForNonVS;
- (void)refreshTeamLogoNameScore_ForVS;
- (void)refreshScoreForShootOutCategory;
- (void)refreshRightSubTipForShootOutCategory;
- (void)refreshForWinterOlympic;
- (void)reset;
- (void)setAdModule;
- (void)clickedControlAd:(id)arg1;
- (void)setMatchDateAndType;
- (void)setItemInfo:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)updateSeparatorLineFrame:(struct CGRect)arg1;
- (id)generateBossReportInfo;
- (id)bossReportInfoWhenScrollDidEnd;
- (id)bossReportInfoWhenUserDidSelect;
- (void)updateWithInfo:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

