//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CADisplayLink, NSMutableArray;
@protocol QSScrollLabelDelegate;

__attribute__((visibility("hidden")))
@interface QSScrollLabel : UIView
{
    id <QSScrollLabelDelegate> _delegate;
    NSMutableArray *_showingTextDatas;
    CADisplayLink *_displayLink;
    struct UIEdgeInsets _contentInset;
    struct UIEdgeInsets _currentContentInset;
}

@property(nonatomic) struct UIEdgeInsets currentContentInset; // @synthesize currentContentInset=_currentContentInset;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(retain, nonatomic) NSMutableArray *showingTextDatas; // @synthesize showingTextDatas=_showingTextDatas;
@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
@property(nonatomic) __weak id <QSScrollLabelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)createDisplayLinkIfNeeded;
- (void)needsUpdate:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)setContentInset:(struct UIEdgeInsets)arg1 animated:(_Bool)arg2;
- (double)contentInsetAnmationDuration;
- (void)removeAllAndClearContentInset;
- (void)removeAll;
- (void)addAttributedString:(id)arg1 estimatedContentInset:(struct UIEdgeInsets)arg2;
- (void)addText:(id)arg1 font:(id)arg2 textColor:(id)arg3 estimatedContentInset:(struct UIEdgeInsets)arg4;
- (void)didMoveToWindow;
- (void)willMoveToWindow:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

