//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QSMoreMatchItem, UIImageView;

__attribute__((visibility("hidden")))
@interface QSScheduleCell : UIView
{
    _Bool _showDate;
    UIImageView *_vipTagView;
    QSMoreMatchItem *_info;
}

@property(retain, nonatomic) QSMoreMatchItem *info; // @synthesize info=_info;
@property(retain, nonatomic) UIImageView *vipTagView; // @synthesize vipTagView=_vipTagView;
@property(nonatomic) _Bool showDate; // @synthesize showDate=_showDate;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateWithInfo:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setBlackSkin;

@end

