//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSContainerViewController.h"

#import "QSBaseDataDelegate-Protocol.h"
#import "QSCustomTabBarDelegate-Protocol.h"
#import "QSMatchCalendarViewControllerDelegate-Protocol.h"
#import "QSPushViewControllerProtocol-Protocol.h"
#import "QSWorldCupScheduleViewControllerDelegate-Protocol.h"

@class NSString, QSDetailTabBar, QSRankTabData, UIButton, UINavigationBar;

__attribute__((visibility("hidden")))
@interface QSScheduleDetailViewController : QSContainerViewController <QSCustomTabBarDelegate, QSBaseDataDelegate, QSMatchCalendarViewControllerDelegate, QSWorldCupScheduleViewControllerDelegate, QSPushViewControllerProtocol>
{
    _Bool _initialShouldSelectRankColumn;
    NSString *_columnId;
    long long _tabType;
    NSString *_columnName;
    long long _tab;
    long long _selectedTabType;
    UINavigationBar *_topBar;
    QSDetailTabBar *_tabBar;
    UIButton *_calendarButton;
    UIButton *_shareButton;
    QSRankTabData *_rankTabData;
}

+ (id)allViewControllerType;
@property(retain, nonatomic) QSRankTabData *rankTabData; // @synthesize rankTabData=_rankTabData;
@property(retain, nonatomic) UIButton *shareButton; // @synthesize shareButton=_shareButton;
@property(retain, nonatomic) UIButton *calendarButton; // @synthesize calendarButton=_calendarButton;
@property(retain, nonatomic) QSDetailTabBar *tabBar; // @synthesize tabBar=_tabBar;
@property(retain, nonatomic) UINavigationBar *topBar; // @synthesize topBar=_topBar;
@property(nonatomic) long long selectedTabType; // @synthesize selectedTabType=_selectedTabType;
@property(nonatomic) long long tab; // @synthesize tab=_tab;
@property(nonatomic) _Bool initialShouldSelectRankColumn; // @synthesize initialShouldSelectRankColumn=_initialShouldSelectRankColumn;
@property(copy, nonatomic) NSString *columnName; // @synthesize columnName=_columnName;
@property(nonatomic) long long tabType; // @synthesize tabType=_tabType;
@property(copy, nonatomic) NSString *columnId; // @synthesize columnId=_columnId;
- (void).cxx_destruct;
- (void)tabBar:(id)arg1 didSelectSameItemAtIndex:(long long)arg2;
- (void)tabBar:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (id)tabBar:(id)arg1 titleForItemAtIndex:(long long)arg2;
- (unsigned long long)numberOfItemsInTabBar:(id)arg1;
- (void)scheduleTypeDidChange;
- (void)processMemoryWarning;
- (id)viewControllerAtIndex:(long long)arg1;
- (long long)defaultContentViewControllerIndex;
- (long long)countOfContentViewControllers;
- (void)refreshContainer;
- (void)data:(id)arg1 didFinishFinallyWithError:(id)arg2;
- (void)data:(id)arg1 didFinishLoadWithError:(id)arg2;
- (void)dataWillStartLoad:(id)arg1;
- (_Bool)shouldShowLoading;
- (_Bool)isEmpty;
- (void)scrollViewDidScroll:(id)arg1;
- (void)clickedBtnCalendar;
- (void)clickedBtnShare;
- (void)resetShareButtonShownStatus;
- (void)resetCalendarButtonShownStatus;
- (void)updateContentViewControllerSinceScrollDidFinish;
- (void)qsMatchCalendarViewController:(id)arg1 didSelectDay:(id)arg2;
- (void)handleBackPress:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)hideContentView;
- (void)showContentView;
- (void)layoutAllContentViews;
- (void)reloadAllController;
- (_Bool)shouldShowToolBar;
- (void)viewDidLoad;
- (struct CGPoint)centerOfLoadingView;
- (void)forceHideBottomLineForNavigationBar;
- (void)updateNavigationBar;
- (void)shouldReloadSinceErrorPressed;
- (_Bool)shouldShowSelfDefinedNavigationBar;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithParameters:(id)arg1;
- (id)currentParameters;
- (_Bool)notAutoReloadData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

