//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSWebViewControllerWithUserInfo.h"

__attribute__((visibility("hidden")))
@interface QSSettingFeedbackViewController : QSWebViewControllerWithUserInfo
{
}

- (void)backButtonDidTap:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRelativePath:(id)arg2 info:(id)arg3;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

