//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSFullScreenView.h"

#import "QSSharedTCPNotiViewDelegate-Protocol.h"
#import "QSWebViewDelegate-Protocol.h"

@class NSString, QSTCPNotiItem, QSWebView, UIButton;
@protocol QSSharedTCPH5NotiViewDelegate;

__attribute__((visibility("hidden")))
@interface QSSharedTCPH5NotiView : QSFullScreenView <QSWebViewDelegate, QSSharedTCPNotiViewDelegate>
{
    id <QSSharedTCPH5NotiViewDelegate> _delegate;
    QSTCPNotiItem *_notiItem;
    QSWebView *_webView;
    UIButton *_closeBtn;
}

@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) QSWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) QSTCPNotiItem *notiItem; // @synthesize notiItem=_notiItem;
@property(nonatomic) __weak id <QSSharedTCPH5NotiViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)cookieIdentifier;
- (id)allParamentsInfoWithRequest:(id)arg1;
- (_Bool)qsWebView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)closeBtnClicked:(id)arg1;
- (id)pageInfo;
- (void)dismiss;
- (void)dismissWithCompletion:(CDUnknownBlockType)arg1 animated:(_Bool)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

