//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QSWebImageView, UILabel;

__attribute__((visibility("hidden")))
@interface QSSignInCardVsContentView : UIView
{
    UILabel *_scoreLabel;
    QSWebImageView *_rightAvatar;
    UIView *_rightMaskView;
    QSWebImageView *_leftAvatar;
    UIView *_leftMaskView;
}

@property(retain, nonatomic) UIView *leftMaskView; // @synthesize leftMaskView=_leftMaskView;
@property(retain, nonatomic) QSWebImageView *leftAvatar; // @synthesize leftAvatar=_leftAvatar;
@property(retain, nonatomic) UIView *rightMaskView; // @synthesize rightMaskView=_rightMaskView;
@property(retain, nonatomic) QSWebImageView *rightAvatar; // @synthesize rightAvatar=_rightAvatar;
@property(retain, nonatomic) UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

