//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "QSPullToRefreshProtocol-Protocol.h"

@class NSDate, NSString, QSSigngnInCardHeaderView, UIImageView, UILabel;
@protocol QSSignedInCardDelegate, QSTableViewDelegate;

__attribute__((visibility("hidden")))
@interface QSSignedInCardRefreshView : UIView <QSPullToRefreshProtocol>
{
    _Bool _isTriggerByDrag;
    id <QSTableViewDelegate> _delegate;
    long long _state;
    NSDate *_lastUpdateDate;
    UIImageView *_bgView;
    UIImageView *_topView;
    UIImageView *_loadingView;
    UILabel *_statusLabel;
    UILabel *_lastUpdateDateLabel;
    NSString *_refreshNomoreText;
    NSString *_refreshNormalText;
    NSString *_refreshText;
    NSString *_refreshLoadingText;
    QSSigngnInCardHeaderView *_cardView;
    id <QSSignedInCardDelegate> _signedInCardDelegate;
}

@property(nonatomic) __weak id <QSSignedInCardDelegate> signedInCardDelegate; // @synthesize signedInCardDelegate=_signedInCardDelegate;
@property(retain, nonatomic) QSSigngnInCardHeaderView *cardView; // @synthesize cardView=_cardView;
@property(copy, nonatomic) NSString *refreshLoadingText; // @synthesize refreshLoadingText=_refreshLoadingText;
@property(copy, nonatomic) NSString *refreshText; // @synthesize refreshText=_refreshText;
@property(copy, nonatomic) NSString *refreshNormalText; // @synthesize refreshNormalText=_refreshNormalText;
@property(copy, nonatomic) NSString *refreshNomoreText; // @synthesize refreshNomoreText=_refreshNomoreText;
@property(retain, nonatomic) UILabel *lastUpdateDateLabel; // @synthesize lastUpdateDateLabel=_lastUpdateDateLabel;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) UIImageView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UIImageView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) UIImageView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) NSDate *lastUpdateDate; // @synthesize lastUpdateDate=_lastUpdateDate;
@property(nonatomic) _Bool isTriggerByDrag; // @synthesize isTriggerByDrag=_isTriggerByDrag;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(nonatomic) __weak id <QSTableViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setSignedInStateSuccess:(_Bool)arg1;
- (void)forceLoading:(id)arg1 animate:(_Bool)arg2;
- (void)scrollViewDataSourceDidFinishedLoading:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1;
- (double)offsetYOfScrollView:(id)arg1;
- (double)offsetStartY;
- (double)offsetEndY;
- (double)height;
- (void)refresh;
- (void)refreshLastUpdatedDate;
- (id)stringFromDate:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)willMoveToWindow:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

