//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QSRoundBackgroundAvatarView, UIActivityIndicatorView, UIButton, UIImageView, UILabel;
@protocol QSSignedInCardDelegate;

__attribute__((visibility("hidden")))
@interface QSSigngnInCardHeaderView : UIView
{
    id <QSSignedInCardDelegate> _signedInCardDelegate;
    UIImageView *_bgImg;
    UIButton *_goSignedBtn;
    UIView *_goMyCardBtnView;
    UIView *_bgViewVS;
    UIView *_bgViewNoneVS;
    UILabel *_matchDescLabel;
    UILabel *_timeLabel;
    UILabel *_noneVsLabel1;
    UILabel *_noneVsLabel2;
    UILabel *_bonusLabel;
    UILabel *_successLabel1;
    UILabel *_successLabel2;
    UIImageView *_rightArrowImg;
    QSRoundBackgroundAvatarView *_noneAvatar;
    QSRoundBackgroundAvatarView *_leftAvatar;
    QSRoundBackgroundAvatarView *_rightAvatar;
    UIActivityIndicatorView *_activityIndicator;
}

+ (double)heightWithState:(long long)arg1;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) QSRoundBackgroundAvatarView *rightAvatar; // @synthesize rightAvatar=_rightAvatar;
@property(retain, nonatomic) QSRoundBackgroundAvatarView *leftAvatar; // @synthesize leftAvatar=_leftAvatar;
@property(retain, nonatomic) QSRoundBackgroundAvatarView *noneAvatar; // @synthesize noneAvatar=_noneAvatar;
@property(retain, nonatomic) UIImageView *rightArrowImg; // @synthesize rightArrowImg=_rightArrowImg;
@property(retain, nonatomic) UILabel *successLabel2; // @synthesize successLabel2=_successLabel2;
@property(retain, nonatomic) UILabel *successLabel1; // @synthesize successLabel1=_successLabel1;
@property(retain, nonatomic) UILabel *bonusLabel; // @synthesize bonusLabel=_bonusLabel;
@property(retain, nonatomic) UILabel *noneVsLabel2; // @synthesize noneVsLabel2=_noneVsLabel2;
@property(retain, nonatomic) UILabel *noneVsLabel1; // @synthesize noneVsLabel1=_noneVsLabel1;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *matchDescLabel; // @synthesize matchDescLabel=_matchDescLabel;
@property(retain, nonatomic) UIView *bgViewNoneVS; // @synthesize bgViewNoneVS=_bgViewNoneVS;
@property(retain, nonatomic) UIView *bgViewVS; // @synthesize bgViewVS=_bgViewVS;
@property(retain, nonatomic) UIView *goMyCardBtnView; // @synthesize goMyCardBtnView=_goMyCardBtnView;
@property(retain, nonatomic) UIButton *goSignedBtn; // @synthesize goSignedBtn=_goSignedBtn;
@property(retain, nonatomic) UIImageView *bgImg; // @synthesize bgImg=_bgImg;
@property(nonatomic) __weak id <QSSignedInCardDelegate> signedInCardDelegate; // @synthesize signedInCardDelegate=_signedInCardDelegate;
- (void).cxx_destruct;
- (void)goMyCardBtnPressed:(id)arg1;
- (void)setSignedInStateSuccess:(_Bool)arg1;
- (void)signedInButtonPressed:(id)arg1;
- (id)displayStringForDateString:(id)arg1;
- (void)showSigngnInCardStateYes;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (double)height;

@end

