//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSMutableArray, QSAvatarView, QSDetailItemView;

__attribute__((visibility("hidden")))
@interface QSSignInProfileCell : UITableViewCell
{
    QSAvatarView *_avatar;
    NSMutableArray *_itemViews;
    QSDetailItemView *_memorialDay;
    QSDetailItemView *_memorialCard;
    QSDetailItemView *_vanityItem;
}

+ (double)heightWithModel:(id)arg1;
@property(retain, nonatomic) QSDetailItemView *vanityItem; // @synthesize vanityItem=_vanityItem;
@property(retain, nonatomic) QSDetailItemView *memorialCard; // @synthesize memorialCard=_memorialCard;
@property(retain, nonatomic) QSDetailItemView *memorialDay; // @synthesize memorialDay=_memorialDay;
@property(retain, nonatomic) NSMutableArray *itemViews; // @synthesize itemViews=_itemViews;
@property(retain, nonatomic) QSAvatarView *avatar; // @synthesize avatar=_avatar;
- (void).cxx_destruct;
- (void)updateWithModel:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

