//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSSmallScreenVideoControlViewController.h"

@class UIButton;

__attribute__((visibility("hidden")))
@interface QSSmallScreenVRVideoControlViewController : QSSmallScreenVideoControlViewController
{
    UIButton *_binoButton;
}

@property(retain, nonatomic) UIButton *binoButton; // @synthesize binoButton=_binoButton;
- (void).cxx_destruct;
- (void)binoButtonDidTap:(id)arg1;
- (void)updateUI;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)hideControlUI;
- (void)showControlUI;

@end

