//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSViewController.h"

#import "QSMPVideoPlayerLayerViewControllerDelegate-Protocol.h"

@class NSString, QSBusSystem, QSMPSharedItem, UIView;

__attribute__((visibility("hidden")))
@interface QSSmallScreenFeedControlVC : QSViewController <QSMPVideoPlayerLayerViewControllerDelegate>
{
    QSMPSharedItem *_sharedItem;
    QSBusSystem *_mediaPlayerBusSystem;
    UIView *_progressView;
    UIView *_playableView;
}

@property(retain, nonatomic) UIView *playableView; // @synthesize playableView=_playableView;
@property(retain, nonatomic) UIView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) QSBusSystem *mediaPlayerBusSystem; // @synthesize mediaPlayerBusSystem=_mediaPlayerBusSystem;
@property(retain, nonatomic) QSMPSharedItem *sharedItem; // @synthesize sharedItem=_sharedItem;
- (void).cxx_destruct;
- (void)updateUI;
- (void)removeObserver;
- (void)addObserver;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=isPlayerMuted) _Bool playerMuted;
@property(readonly) Class superclass;

@end

