//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSBaseMatchLivePropsListView.h"

#import "QSSmallScreenMatchLivePropsItemViewDelegate-Protocol.h"
#import "QSWebImageViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, NSString, QSMatchLivePropsListItem, QSWebImageViewEx, UIActivityIndicatorView, UIButton, UIControl, UIImageView, UILabel, UIPageControl, UIScrollView, UIView;

__attribute__((visibility("hidden")))
@interface QSSmallScreenMatchLivePropsListView : QSBaseMatchLivePropsListView <QSSmallScreenMatchLivePropsItemViewDelegate, UIScrollViewDelegate, QSWebImageViewDelegate>
{
    _Bool _hasReceiveData;
    _Bool _hasReceiveError;
    _Bool _didShow;
    _Bool _didDismiss;
    UIView *_bgView;
    UIView *_contentView;
    UIView *_adView;
    UILabel *_adWordLabel;
    UILabel *_adLinkLabel;
    UIImageView *_adArrowView;
    UIView *_bottomView;
    QSWebImageViewEx *_skinImageView;
    UIScrollView *_propsScrollView;
    UIPageControl *_pageControl;
    UIView *_bottomLine;
    UIImageView *_rankIconView;
    UILabel *_rankLabel;
    UIControl *_rankControl;
    UIImageView *_kbIconView;
    UILabel *_kbLabel;
    UIImageView *_diamondIconView;
    UILabel *_diamondLabel;
    UIControl *_walletControl;
    UIButton *_buyButton;
    UIActivityIndicatorView *_activityView;
    UILabel *_errorLabel;
    UIImageView *_emptyView;
    NSMutableArray *_propsItemViewArray;
    long long _currentPageIndex;
    unsigned long long _totalPage;
    QSMatchLivePropsListItem *_selectedProps;
    NSString *_errorText;
}

+ (int)propsNumOfOnePage;
+ (double)propsListContentViewHeight;
+ (double)propsListBottomViewHeight;
+ (double)propsListScrollViewHeight;
@property(copy, nonatomic) NSString *errorText; // @synthesize errorText=_errorText;
@property(nonatomic) _Bool didDismiss; // @synthesize didDismiss=_didDismiss;
@property(nonatomic) _Bool didShow; // @synthesize didShow=_didShow;
@property(nonatomic) _Bool hasReceiveError; // @synthesize hasReceiveError=_hasReceiveError;
@property(nonatomic) _Bool hasReceiveData; // @synthesize hasReceiveData=_hasReceiveData;
@property(retain, nonatomic) QSMatchLivePropsListItem *selectedProps; // @synthesize selectedProps=_selectedProps;
@property(nonatomic) unsigned long long totalPage; // @synthesize totalPage=_totalPage;
@property(nonatomic) long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(retain, nonatomic) NSMutableArray *propsItemViewArray; // @synthesize propsItemViewArray=_propsItemViewArray;
@property(retain, nonatomic) UIImageView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) UILabel *errorLabel; // @synthesize errorLabel=_errorLabel;
@property(retain, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView=_activityView;
@property(retain, nonatomic) UIButton *buyButton; // @synthesize buyButton=_buyButton;
@property(retain, nonatomic) UIControl *walletControl; // @synthesize walletControl=_walletControl;
@property(retain, nonatomic) UILabel *diamondLabel; // @synthesize diamondLabel=_diamondLabel;
@property(retain, nonatomic) UIImageView *diamondIconView; // @synthesize diamondIconView=_diamondIconView;
@property(retain, nonatomic) UILabel *kbLabel; // @synthesize kbLabel=_kbLabel;
@property(retain, nonatomic) UIImageView *kbIconView; // @synthesize kbIconView=_kbIconView;
@property(retain, nonatomic) UIControl *rankControl; // @synthesize rankControl=_rankControl;
@property(retain, nonatomic) UILabel *rankLabel; // @synthesize rankLabel=_rankLabel;
@property(retain, nonatomic) UIImageView *rankIconView; // @synthesize rankIconView=_rankIconView;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIScrollView *propsScrollView; // @synthesize propsScrollView=_propsScrollView;
@property(retain, nonatomic) QSWebImageViewEx *skinImageView; // @synthesize skinImageView=_skinImageView;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIImageView *adArrowView; // @synthesize adArrowView=_adArrowView;
@property(retain, nonatomic) UILabel *adLinkLabel; // @synthesize adLinkLabel=_adLinkLabel;
@property(retain, nonatomic) UILabel *adWordLabel; // @synthesize adWordLabel=_adWordLabel;
@property(retain, nonatomic) UIView *adView; // @synthesize adView=_adView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
- (void).cxx_destruct;
- (void)pageChanged:(id)arg1;
- (void)bgClicked:(id)arg1;
- (void)walletClicked:(id)arg1;
- (void)rankClicked:(id)arg1;
- (void)adClicked:(id)arg1;
- (void)buyButtonClicked:(id)arg1;
- (void)webImageViewDidFinishLoading:(id)arg1;
- (void)propsItemViewBeenClicked:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollToPropsIndex:(long long)arg1;
- (void)updateUI;
- (void)showContent;
- (void)setPropsList:(id)arg1;
- (void)showError:(id)arg1;
- (void)dismissAnimated:(_Bool)arg1;
- (void)dismiss;
- (void)showInView:(id)arg1;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

