//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface QSSourceMediaItem : NSObject
{
    NSDictionary *_reportInfo;
    NSString *_title;
    NSString *_previewImgURL;
}

+ (id)mediaItemWithVid:(id)arg1 cid:(id)arg2 isPortrait:(_Bool)arg3;
+ (id)mediaItemWithMid:(id)arg1;
+ (id)mediaItemWithVid:(id)arg1 cid:(id)arg2;
@property(copy, nonatomic) NSString *previewImgURL; // @synthesize previewImgURL=_previewImgURL;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSDictionary *reportInfo; // @synthesize reportInfo=_reportInfo;
- (void).cxx_destruct;
- (id)logDic;
- (_Bool)isEqual:(id)arg1;

@end

