//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class QSRoundMapThirdRound, QSStructMatchNode;

__attribute__((visibility("hidden")))
@interface QSStructThirdMatchNode : NSObject
{
    QSStructMatchNode *_structMatchNode;
    QSRoundMapThirdRound *_thirdMatchInfo;
    struct CGRect _thirdIconFrame;
}

@property(retain, nonatomic) QSRoundMapThirdRound *thirdMatchInfo; // @synthesize thirdMatchInfo=_thirdMatchInfo;
@property(retain, nonatomic) QSStructMatchNode *structMatchNode; // @synthesize structMatchNode=_structMatchNode;
@property(nonatomic) struct CGRect thirdIconFrame; // @synthesize thirdIconFrame=_thirdIconFrame;
- (void).cxx_destruct;

@end

