//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor;

__attribute__((visibility("hidden")))
@interface QSTableViewCellCommonConfigure : NSObject
{
    _Bool _shouldCacheHeight;
    _Bool _showTopSeparateLine;
    _Bool _showBottomSeparateLine;
    _Bool _autoPadding;
    double _cellHeight;
    double _cellWidth;
    UIColor *_separateLineColor;
    UIColor *_customSelectedBackgroudColor;
    struct UIEdgeInsets _separateLinePadding;
    struct UIEdgeInsets _padding;
}

@property(retain, nonatomic) UIColor *customSelectedBackgroudColor; // @synthesize customSelectedBackgroudColor=_customSelectedBackgroudColor;
@property(nonatomic) struct UIEdgeInsets padding; // @synthesize padding=_padding;
@property(nonatomic) _Bool autoPadding; // @synthesize autoPadding=_autoPadding;
@property(nonatomic) struct UIEdgeInsets separateLinePadding; // @synthesize separateLinePadding=_separateLinePadding;
@property(retain, nonatomic) UIColor *separateLineColor; // @synthesize separateLineColor=_separateLineColor;
@property(nonatomic) _Bool showBottomSeparateLine; // @synthesize showBottomSeparateLine=_showBottomSeparateLine;
@property(nonatomic) _Bool showTopSeparateLine; // @synthesize showTopSeparateLine=_showTopSeparateLine;
@property(nonatomic) double cellWidth; // @synthesize cellWidth=_cellWidth;
@property(nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
@property(nonatomic) _Bool shouldCacheHeight; // @synthesize shouldCacheHeight=_shouldCacheHeight;
- (void).cxx_destruct;
- (struct UIEdgeInsets)separatePadding;
- (id)init;

@end

