//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class QSTCPNotiItemContentBoxData, QSTCPNotiItemContentH5Data, QSTCPNotiItemContentStatusData;

__attribute__((visibility("hidden")))
@interface QSTCPNotiItemContent : QSModel
{
    QSTCPNotiItemContentStatusData *_statusData;
    QSTCPNotiItemContentBoxData *_boxData;
    QSTCPNotiItemContentH5Data *_h5Data;
}

@property(retain, nonatomic) QSTCPNotiItemContentH5Data *h5Data; // @synthesize h5Data=_h5Data;
@property(retain, nonatomic) QSTCPNotiItemContentBoxData *boxData; // @synthesize boxData=_boxData;
@property(retain, nonatomic) QSTCPNotiItemContentStatusData *statusData; // @synthesize statusData=_statusData;
- (void).cxx_destruct;

@end

