//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, NSMutableData, QSTCPConnection;

@protocol QSTCPConnectionDelegate <NSObject>
- (void)tcpConnectionConnectDidEnd:(QSTCPConnection *)arg1;
- (void)tcpConnectionConnectSucceed:(QSTCPConnection *)arg1;
- (void)tcpConnection:(QSTCPConnection *)arg1 didReceiveData:(NSMutableData *)arg2;
- (void)tcpConnection:(QSTCPConnection *)arg1 errorHappened:(NSError *)arg2;
@end

