//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSTextLivePicVideoView.h"

@class QSTextLiveItemImages;

__attribute__((visibility("hidden")))
@interface QSTextLiveImageView : QSTextLivePicVideoView
{
    QSTextLiveItemImages *_images;
}

@property(retain, nonatomic) QSTextLiveItemImages *images; // @synthesize images=_images;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

