//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QSTextLiveQuarterItem, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface QSTextLiveHeaderView : UIView
{
    _Bool _isRedMode;
    QSTextLiveQuarterItem *_quarterItem;
    UIImageView *_bgImageView;
    UILabel *_tipLabel;
}

+ (double)heightWithItem:(id)arg1;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(retain, nonatomic) QSTextLiveQuarterItem *quarterItem; // @synthesize quarterItem=_quarterItem;
@property(nonatomic) _Bool isRedMode; // @synthesize isRedMode=_isRedMode;
- (void).cxx_destruct;
- (void)updateUIWidthItem:(id)arg1 red:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

