//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer;

__attribute__((visibility("hidden")))
@interface QSTicketBackgroudView : UIView
{
    CAShapeLayer *_shapeLayer;
    CAShapeLayer *_lineLayer;
    double _middleHeightRatio;
    double _radius;
}

+ (Class)layerClass;
@property(nonatomic) double radius; // @synthesize radius=_radius;
@property(nonatomic) double middleHeightRatio; // @synthesize middleHeightRatio=_middleHeightRatio;
@property(readonly, nonatomic) CAShapeLayer *lineLayer; // @synthesize lineLayer=_lineLayer;
@property(readonly, nonatomic) __weak CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
- (void).cxx_destruct;
- (id)_createBounderPath;
- (id)_createLinePath;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

