//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSViewController.h"

#import "QSObservedObjectDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UIPanGestureRecognizer, UIScrollView, UISwipeGestureRecognizer, UIView, UIViewController;
@protocol QSRootVCProtocol, QSTopVCProtocol;

__attribute__((visibility("hidden")))
@interface QSTopRootController : QSViewController <UIGestureRecognizerDelegate, QSObservedObjectDelegate>
{
    _Bool _isViewAppeared;
    UIViewController<QSTopVCProtocol> *_topViewController;
    UIViewController<QSRootVCProtocol> *_rootViewController;
    UIView *_topContentView;
    double _collapseHeight;
    double _expandHeight;
    UIScrollView *_observeScrollView;
    UISwipeGestureRecognizer *_swipeShowRecognizer;
    UISwipeGestureRecognizer *_swipeHideRecognizer;
    UIPanGestureRecognizer *_panShowRecognizer;
}

@property(retain, nonatomic) UIPanGestureRecognizer *panShowRecognizer; // @synthesize panShowRecognizer=_panShowRecognizer;
@property(retain, nonatomic) UISwipeGestureRecognizer *swipeHideRecognizer; // @synthesize swipeHideRecognizer=_swipeHideRecognizer;
@property(retain, nonatomic) UISwipeGestureRecognizer *swipeShowRecognizer; // @synthesize swipeShowRecognizer=_swipeShowRecognizer;
@property(retain, nonatomic) UIScrollView *observeScrollView; // @synthesize observeScrollView=_observeScrollView;
@property(nonatomic) double expandHeight; // @synthesize expandHeight=_expandHeight;
@property(nonatomic) double collapseHeight; // @synthesize collapseHeight=_collapseHeight;
@property(retain, nonatomic) UIView *topContentView; // @synthesize topContentView=_topContentView;
@property(nonatomic) _Bool isViewAppeared; // @synthesize isViewAppeared=_isViewAppeared;
@property(readonly, nonatomic) UIViewController<QSRootVCProtocol> *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(readonly, nonatomic) UIViewController<QSTopVCProtocol> *topViewController; // @synthesize topViewController=_topViewController;
- (void).cxx_destruct;
- (void)observedObjectDidUpdate:(id)arg1 withKey:(id)arg2;
- (void)onSwipeHide:(id)arg1;
- (void)addSwipeHideGesture:(id)arg1;
- (void)removeSwipeHideGesture;
- (void)checkSwipeHideGesture:(id)arg1;
- (void)resetSwipeHideValue;
- (void)onSwipeShow:(id)arg1;
- (void)addSwipeShowGesture:(id)arg1;
- (void)removeSwipeShowGesture;
- (void)checkSwipeShowGesture:(id)arg1;
- (void)resetSwipeShowValue;
- (void)onPanShow:(id)arg1;
- (void)addPanShowGesture:(id)arg1;
- (void)removePanShowGesture;
- (void)checkPanShowGesture:(id)arg1;
- (void)resetPanShowValue;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)resetPanValue;
- (void)contentViewFollow:(double)arg1 animate:(_Bool)arg2;
- (void)topViewSwipeShow:(_Bool)arg1 animate:(_Bool)arg2;
- (double)topViewShow:(_Bool)arg1 animate:(_Bool)arg2;
- (void)topHeightDidChange:(double)arg1 animate:(_Bool)arg2 duration:(double)arg3;
- (void)resetTopHeight;
- (void)resetAllValues;
- (void)updateViewContent;
- (void)updateContentViewWithRootViewController:(id)arg1;
- (void)updateTopContentViewWithTopViewController:(id)arg1;
- (void)setRootViewController:(id)arg1;
- (void)setTopViewController:(id)arg1;
- (void)setTopViewController:(id)arg1 andRootViewController:(id)arg2 animationType:(long long)arg3;
- (void)setRootViewController:(id)arg1 animationType:(long long)arg2;
- (void)setTopViewController:(id)arg1 animationType:(long long)arg2;
- (_Bool)interactivePopGestureShouldBegin;
- (void)resetDidAppearDate;
- (void)logSelfImmediately;
- (void)logSelfImmediatelyWhenAppear;
- (void)setShouldAutoLog:(_Bool)arg1;
- (void)hideContentView;
- (void)showContentView;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)childViewControllerForStatusBarStyle;
- (id)childViewControllerForStatusBarHidden;
- (void)expandTop;
- (_Bool)canSwipeTopToHide;
- (_Bool)canSwipeTopToShow;
- (_Bool)canScrollTopToHidden;
- (unsigned long long)topRootRelation;
- (_Bool)needBossReporter;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

