//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class QSComUserItem, QSTopicDetailZanTableViewCell;

@protocol QSTopicDetailZanTableViewCellDelegate <NSObject>
- (void)supportTableViewCell:(QSTopicDetailZanTableViewCell *)arg1 didTapUser:(QSComUserItem *)arg2;
- (void)zanCellDidOperationFinished:(QSTopicDetailZanTableViewCell *)arg1;
@end

