//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "QSAutoUpdateProtocol-Protocol.h"
#import "QSWTLoginDelegate-Protocol.h"
#import "QSWTLoginViewControllerDelegate-Protocol.h"
#import "QSWXLoginDelegate-Protocol.h"

@class NSData, NSDate, NSDictionary, NSMutableDictionary, NSString, QSUserInfo, QSVIPInfo, QSVIPInfoManagement, QSWTLogin, QSWTLoginViewController, QSWXLogin, UINavigationController;

__attribute__((visibility("hidden")))
@interface QSUserInfoManagement : NSObject <QSWTLoginDelegate, QSWTLoginViewControllerDelegate, QSWXLoginDelegate, QSAutoUpdateProtocol>
{
    _Bool _canRefeshLoginInfo;
    QSUserInfo *_userInfo;
    UINavigationController *_rootNavigationController;
    QSWTLoginViewController *_wtLoginViewController;
    QSWTLogin *_wtLogin;
    QSWXLogin *_wxLogin;
    QSVIPInfoManagement *_vipInfoManagement;
    CDUnknownBlockType _loginCompletion;
    CDUnknownBlockType _refreshCompletion;
    NSMutableDictionary *_cookieOwners;
    NSDate *_userInfoUpdateTime;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSDate *userInfoUpdateTime; // @synthesize userInfoUpdateTime=_userInfoUpdateTime;
@property(retain, nonatomic) NSMutableDictionary *cookieOwners; // @synthesize cookieOwners=_cookieOwners;
@property(nonatomic) _Bool canRefeshLoginInfo; // @synthesize canRefeshLoginInfo=_canRefeshLoginInfo;
@property(copy, nonatomic) CDUnknownBlockType refreshCompletion; // @synthesize refreshCompletion=_refreshCompletion;
@property(copy, nonatomic) CDUnknownBlockType loginCompletion; // @synthesize loginCompletion=_loginCompletion;
@property(retain, nonatomic) QSVIPInfoManagement *vipInfoManagement; // @synthesize vipInfoManagement=_vipInfoManagement;
@property(retain, nonatomic) QSWXLogin *wxLogin; // @synthesize wxLogin=_wxLogin;
@property(retain, nonatomic) QSWTLogin *wtLogin; // @synthesize wtLogin=_wtLogin;
@property(retain, nonatomic) QSWTLoginViewController *wtLoginViewController; // @synthesize wtLoginViewController=_wtLoginViewController;
@property(nonatomic) __weak UINavigationController *rootNavigationController; // @synthesize rootNavigationController=_rootNavigationController;
@property(retain, nonatomic) QSUserInfo *userInfo; // @synthesize userInfo=_userInfo;
- (void).cxx_destruct;
- (void)wxLogin:(id)arg1 didFailedWithError:(id)arg2;
- (void)wxLoginDidSucceed:(id)arg1;
- (void)wtLoginDidFailed:(id)arg1 didFailedWithError:(id)arg2;
- (void)wtLoginDidSucceed:(id)arg1;
- (void)wtLoginViewControllerUserNeedQQSSOLogin:(id)arg1;
- (void)wtLoginViewControllerUserNeedWeixinSSOLogin:(id)arg1;
- (void)wtLoginViewControllerUserDidCancel:(id)arg1;
- (void)loginFailedWithError:(id)arg1;
- (void)loginFinished;
- (void)updateUserInfo;
- (void)syncUserInfo;
- (void)readInfo;
- (void)saveInfo;
- (id)userInfoPath;
- (_Bool)isErrorLoginFailed:(id)arg1 checkedOperation:(CDUnknownBlockType)arg2;
- (void)hideLoadingView;
- (void)cookiesDidInvalidFromServer;
- (void)logoutWithCompletion:(CDUnknownBlockType)arg1;
- (void)showLoginViewController;
- (void)loginWithType:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loginFromViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loginWithTipTitle:(id)arg1 tipDetail:(id)arg2 completion:(CDUnknownBlockType)arg3 animated:(_Bool)arg4 didShowCompletion:(CDUnknownBlockType)arg5;
- (void)loginWithTipTitle:(id)arg1 tipDetail:(id)arg2 completion:(CDUnknownBlockType)arg3 animated:(_Bool)arg4;
- (void)loginWithCompletion:(CDUnknownBlockType)arg1 didShowCompletion:(CDUnknownBlockType)arg2;
- (void)loginWithCompletion:(CDUnknownBlockType)arg1;
- (long long)loginStatus;
- (_Bool)isLoggedIn;
- (void)showLoginViewControllerWithForceWeiXinHidden:(_Bool)arg1 animated:(_Bool)arg2 didShowCompletion:(CDUnknownBlockType)arg3;
- (void)logout;
- (void)clear;
- (void)appEndBackground;
- (id)init;
@property(readonly, nonatomic) unsigned int accessTokenHashValue; // @dynamic accessTokenHashValue;
@property(readonly, nonatomic) NSString *wxAccessToken;
@property(readonly, nonatomic) NSString *wxOpenId; // @dynamic wxOpenId;
@property(readonly, nonatomic) NSData *qqSKEYData; // @dynamic qqSKEYData;
@property(readonly, nonatomic) NSData *qqLSKEYData;
@property(readonly, nonatomic) NSString *qq; // @dynamic qq;
@property(readonly, nonatomic) __weak NSDictionary *externInfoForImageUpload; // @dynamic externInfoForImageUpload;
- (void)onAutoUpdate;
- (double)autoFoceUpdateTimeInterval;
- (double)minimumCallbackTimeInterval;
- (_Bool)canUpdate;
- (void)refreshUserInfoWithCompletion:(CDUnknownBlockType)arg1;
- (id)currentUserDocumentPath;
- (void)updateVIPInfoWithCompletion:(CDUnknownBlockType)arg1;
- (void)migrateFromGuestVIPAndWaitingForResult:(CDUnknownBlockType)arg1;
- (void)waitingForVipResult:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) QSVIPInfo *vipInfo; // @dynamic vipInfo;
- (void)weixinAppDidAuthFailedWithError:(id)arg1;
- (void)weixinAppDidAuthSuccessWithCode:(id)arg1 state:(id)arg2;
- (_Bool)handleOpenURL:(id)arg1;
- (void)clearCookiesToLocalWithURL:(id)arg1 ownerIdentifier:(id)arg2;
- (void)saveCookiesToLocalWithURL:(id)arg1 ownerIdentifier:(id)arg2 shouldNotClearOldCookies:(_Bool)arg3;
- (void)saveCookiesToLocalWithURL:(id)arg1 ownerIdentifier:(id)arg2;
- (id)cookies;
@property(readonly, nonatomic) NSString *cookieString; // @dynamic cookieString;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

