//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

#import "NSCopying-Protocol.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface QSVIPInfo : QSModel <NSCopying>
{
    _Bool _xinyingStatus;
    long long _vip;
    long long _deviceVip;
    double _pollInterval;
    NSDate *_updateDate;
    NSString *_vipSig;
    NSString *_deviceVipSig;
}

+ (id)ignoredPropertiesWhenEncoding;
@property(nonatomic) _Bool xinyingStatus; // @synthesize xinyingStatus=_xinyingStatus;
@property(copy, nonatomic) NSString *deviceVipSig; // @synthesize deviceVipSig=_deviceVipSig;
@property(copy, nonatomic) NSString *vipSig; // @synthesize vipSig=_vipSig;
@property(retain, nonatomic) NSDate *updateDate; // @synthesize updateDate=_updateDate;
@property(nonatomic) double pollInterval; // @synthesize pollInterval=_pollInterval;
@property(nonatomic) long long deviceVip; // @synthesize deviceVip=_deviceVip;
@property(nonatomic) long long vip; // @synthesize vip=_vip;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (_Bool)clearUserVIP;
- (_Bool)manualSetValue:(id)arg1 forKey:(id)arg2;
- (_Bool)isNeedUpdate;
- (_Bool)isVIPValid;

@end

