//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "QSWebImageViewDelegate-Protocol.h"

@class NSString, QSVideoListByColumnIdInfo, QSWebImageView, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface QSVideoColumnsListHeadCell : UITableViewCell <QSWebImageViewDelegate>
{
    UIImageView *_headBgImageView;
    UILabel *_videoHeadLabel;
    QSWebImageView *_adImageView;
    QSVideoListByColumnIdInfo *_videoInfo;
}

+ (double)fixedHeight;
@property(retain, nonatomic) QSVideoListByColumnIdInfo *videoInfo; // @synthesize videoInfo=_videoInfo;
@property(retain, nonatomic) QSWebImageView *adImageView; // @synthesize adImageView=_adImageView;
@property(retain, nonatomic) UILabel *videoHeadLabel; // @synthesize videoHeadLabel=_videoHeadLabel;
@property(retain, nonatomic) UIImageView *headBgImageView; // @synthesize headBgImageView=_headBgImageView;
- (void).cxx_destruct;
- (void)webImageViewDidFinishLoading:(id)arg1;
- (void)clickedAdBtn:(id)arg1;
- (void)refreshUIAfterAdIconDownloadFinished;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

