//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSString, QSVideoCoverItem, QSVideoItem;

__attribute__((visibility("hidden")))
@interface QSVideoDetailInfo : QSModel
{
    NSString *_topTitle;
    QSVideoItem *_video;
    QSVideoCoverItem *_cover;
    NSArray *_documentory;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) NSArray *documentory; // @synthesize documentory=_documentory;
@property(retain, nonatomic) QSVideoCoverItem *cover; // @synthesize cover=_cover;
@property(retain, nonatomic) QSVideoItem *video; // @synthesize video=_video;
@property(copy, nonatomic) NSString *topTitle; // @synthesize topTitle=_topTitle;
- (void).cxx_destruct;

@end

