//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSConcurrentOperation.h"

@class QSVipCenterServiceSingleImageInfo;

__attribute__((visibility("hidden")))
@interface QSVipCenterServiceIconDownloadOperation : QSConcurrentOperation
{
    QSVipCenterServiceSingleImageInfo *_singleImageInfo;
    CDUnknownBlockType _downloadCompletionBlock;
    CDUnknownBlockType _singleFinishedBlock;
}

@property(copy, nonatomic) CDUnknownBlockType singleFinishedBlock; // @synthesize singleFinishedBlock=_singleFinishedBlock;
@property(copy, nonatomic) CDUnknownBlockType downloadCompletionBlock; // @synthesize downloadCompletionBlock=_downloadCompletionBlock;
@property(retain, nonatomic) QSVipCenterServiceSingleImageInfo *singleImageInfo; // @synthesize singleImageInfo=_singleImageInfo;
- (void).cxx_destruct;
- (void)downloadImageIcon;
- (void)main;

@end

