//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSVideoListMatchGoalModel : QSModel
{
    NSString *_leftGoal;
    NSString *_rightGoal;
}

@property(copy, nonatomic) NSString *rightGoal; // @synthesize rightGoal=_rightGoal;
@property(copy, nonatomic) NSString *leftGoal; // @synthesize leftGoal=_leftGoal;
- (void).cxx_destruct;

@end

