//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString, QSVideoTagList;

__attribute__((visibility("hidden")))
@interface QSVideoItem : QSModel
{
    _Bool _isPay;
    _Bool _fullView;
    NSString *_duration;
    NSString *_pic;
    NSString *_pic2;
    NSString *_stitle;
    NSString *_targetId;
    NSString *_title;
    NSString *_vid;
    NSString *_views;
    NSString *_tag;
    QSVideoTagList *_tagList;
    unsigned long long _commentNum;
}

@property(nonatomic) unsigned long long commentNum; // @synthesize commentNum=_commentNum;
@property(nonatomic) _Bool fullView; // @synthesize fullView=_fullView;
@property(retain, nonatomic) QSVideoTagList *tagList; // @synthesize tagList=_tagList;
@property(retain, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(nonatomic) _Bool isPay; // @synthesize isPay=_isPay;
@property(retain, nonatomic) NSString *views; // @synthesize views=_views;
@property(retain, nonatomic) NSString *vid; // @synthesize vid=_vid;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *targetId; // @synthesize targetId=_targetId;
@property(retain, nonatomic) NSString *stitle; // @synthesize stitle=_stitle;
@property(retain, nonatomic) NSString *pic2; // @synthesize pic2=_pic2;
@property(retain, nonatomic) NSString *pic; // @synthesize pic=_pic;
@property(retain, nonatomic) NSString *duration; // @synthesize duration=_duration;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (_Bool)manualSetValue:(id)arg1 forKey:(id)arg2;

@end

