//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSContainerViewController.h"

#import "QSBaseDataDelegate-Protocol.h"
#import "QSCustomTabBarDelegate-Protocol.h"
#import "QSPushViewControllerProtocol-Protocol.h"

@class NSDictionary, NSString, QSDetailTabBar, QSVideoTabData;

__attribute__((visibility("hidden")))
@interface QSVideoTabViewController : QSContainerViewController <QSCustomTabBarDelegate, QSBaseDataDelegate, QSPushViewControllerProtocol>
{
    NSDictionary *_jumpParams;
    QSDetailTabBar *_topTabBar;
    QSVideoTabData *_tabData;
}

+ (id)allViewControllerType;
@property(retain, nonatomic) QSVideoTabData *tabData; // @synthesize tabData=_tabData;
@property(retain, nonatomic) QSDetailTabBar *topTabBar; // @synthesize topTabBar=_topTabBar;
@property(retain, nonatomic) NSDictionary *jumpParams; // @synthesize jumpParams=_jumpParams;
- (void).cxx_destruct;
- (struct CGRect)frameForPresentedWarpperView;
- (void)data:(id)arg1 didFinishLoadWithError:(id)arg2;
- (void)dataWillStartLoad:(id)arg1;
- (_Bool)isEmpty;
- (void)shouldReloadSinceErrorPressed;
- (void)tabBar:(id)arg1 didSelectSameItemAtIndex:(long long)arg2;
- (void)tabBar:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (id)tabBar:(id)arg1 titleForItemAtIndex:(long long)arg2;
- (unsigned long long)numberOfItemsInTabBar:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)processMemoryWarning;
- (void)dealloc;
- (void)reloadAllController;
- (void)dropButtonPressed;
- (id)viewControllerAtIndex:(long long)arg1;
- (long long)countOfContentViewControllers;
- (id)titleForViewControllerAtIndex:(unsigned long long)arg1;
- (void)viewDidLoad;
- (void)layoutAllContentViews;
- (double)topBarOffset;
- (void)updateNavigationBar;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (_Bool)shouldShowSelfDefinedNavigationBar;
- (id)initWithParameters:(id)arg1;
- (id)currentParameters;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

