//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface QSVideoListMatchModel : QSModel
{
    NSString *_mid;
    NSString *_leftId;
    NSString *_leftName;
    NSString *_leftBadge;
    NSString *_leftGoal;
    NSString *_rightId;
    NSString *_rightGoal;
    NSString *_rightName;
    NSString *_rightBadge;
    NSString *_startDay;
    NSString *_startHour;
    NSArray *_goals;
    NSDictionary *_jumpData;
}

+ (Class)classForObjectInArrayProperty:(id)arg1;
@property(retain, nonatomic) NSDictionary *jumpData; // @synthesize jumpData=_jumpData;
@property(retain, nonatomic) NSArray *goals; // @synthesize goals=_goals;
@property(copy, nonatomic) NSString *startHour; // @synthesize startHour=_startHour;
@property(copy, nonatomic) NSString *startDay; // @synthesize startDay=_startDay;
@property(copy, nonatomic) NSString *rightBadge; // @synthesize rightBadge=_rightBadge;
@property(copy, nonatomic) NSString *rightName; // @synthesize rightName=_rightName;
@property(copy, nonatomic) NSString *rightGoal; // @synthesize rightGoal=_rightGoal;
@property(copy, nonatomic) NSString *rightId; // @synthesize rightId=_rightId;
@property(copy, nonatomic) NSString *leftGoal; // @synthesize leftGoal=_leftGoal;
@property(copy, nonatomic) NSString *leftBadge; // @synthesize leftBadge=_leftBadge;
@property(copy, nonatomic) NSString *leftName; // @synthesize leftName=_leftName;
@property(copy, nonatomic) NSString *leftId; // @synthesize leftId=_leftId;
@property(copy, nonatomic) NSString *mid; // @synthesize mid=_mid;
- (void).cxx_destruct;

@end

