//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSVipCenterServiceSingleImageInfo : QSModel
{
    int _state;
    NSString *_imgUrl;
    double _whRatio;
}

@property(nonatomic) double whRatio; // @synthesize whRatio=_whRatio;
@property(nonatomic) int state; // @synthesize state=_state;
@property(retain, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
- (void).cxx_destruct;

@end

