//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSBaseData.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSVideoRecommendData : QSBaseData
{
    NSString *_itemId;
    NSString *_setId;
}

@property(copy, nonatomic) NSString *setId; // @synthesize setId=_setId;
@property(copy, nonatomic) NSString *itemId; // @synthesize itemId=_itemId;
- (void).cxx_destruct;
- (id)recommendVideo;
- (void)emptyMemoryCache;
- (void)resetWithResponseModel:(id)arg1;
- (id)httpURLComponents;

@end

