//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "QSMediaPlayerViewControllerDelegate-Protocol.h"

@class NSMutableDictionary, NSString, QSMediaPlayerViewController;

__attribute__((visibility("hidden")))
@interface QSVideoMediaPlayerManager : NSObject <QSMediaPlayerViewControllerDelegate>
{
    _Bool _isPlayerAnimating;
    _Bool _currentMutedState;
    _Bool _isAutoPaused;
    NSMutableDictionary *_likeNumCache;
    QSMediaPlayerViewController *_mediaPlayer;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool isAutoPaused; // @synthesize isAutoPaused=_isAutoPaused;
@property(retain, nonatomic) QSMediaPlayerViewController *mediaPlayer; // @synthesize mediaPlayer=_mediaPlayer;
@property(retain, nonatomic) NSMutableDictionary *likeNumCache; // @synthesize likeNumCache=_likeNumCache;
@property(nonatomic) _Bool currentMutedState; // @synthesize currentMutedState=_currentMutedState;
@property(nonatomic) _Bool isPlayerAnimating; // @synthesize isPlayerAnimating=_isPlayerAnimating;
- (void).cxx_destruct;
- (void)mediaPlayerViewController:(id)arg1 progressUpdated:(double)arg2 playableDuration:(double)arg3 duration:(double)arg4;
- (_Bool)mediaPlayerViewControllerDidPausedOrPlayByUser:(id)arg1;
- (_Bool)mediaPlayerViewControllerAutoPlayWhenSettingMediaItem:(id)arg1;
- (void)mediaPlayerViewControllerPlayPreVideo:(id)arg1;
- (void)mediaPlayerViewControllerPlayNextVideo:(id)arg1;
- (_Bool)mediaPlayerViewControllerHasPreVideo:(id)arg1;
- (_Bool)mediaPlayerViewControllerHasNextVideo:(id)arg1 nextVideoName:(id *)arg2;
- (_Bool)mediaPlayerViewControllerShowPreNextVideoButton:(id)arg1;
- (void)mediaPlayerViewController:(id)arg1 willShowUI:(_Bool)arg2 animate:(_Bool)arg3;
- (void)mediaPlayerViewController:(id)arg1 willShowUI:(_Bool)arg2;
- (void)mediaPlayerViewControllerDidChangeMediaPlayerState:(id)arg1;
- (void)stop;
- (void)resume;
- (void)pause;
- (void)playWithItem:(id)arg1 forced:(_Bool)arg2;
- (id)currentPlayerVid;
- (id)playingVid;
- (void)attachToView:(id)arg1 withInsets:(struct UIEdgeInsets)arg2;
- (void)attachToView:(id)arg1 withFrame:(struct CGRect)arg2;
- (void)removeFromControler:(id)arg1;
- (void)moveToControler:(id)arg1;
- (void)setMediaPlayercanPlayBackground:(_Bool)arg1;
- (void)setPlayerMuted:(_Bool)arg1;
- (_Bool)isPlayerMuted;
- (void)enterBackground:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

