//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSViewController.h"

#import "QSBusEventConsumerDelegate-Protocol.h"
#import "QSFullScreenLiveChatPropsListViewDelegate-Protocol.h"
#import "QSHttpDataDelegate-Protocol.h"
#import "QSMPVideoPlayerLayerViewControllerDelegate-Protocol.h"
#import "QSMediaHitTestViewDelegate-Protocol.h"

@class NSString, QSBusSystem, QSFullScreenMatchLivePropsListView, QSMPLayersViewController, QSMPSharedItem, QSMatchLivePropsListData, QSVideoPlayerPropsSharedData;

__attribute__((visibility("hidden")))
@interface QSVideoPlayerPropsListViewController : QSViewController <QSMediaHitTestViewDelegate, QSBusEventConsumerDelegate, QSHttpDataDelegate, QSFullScreenLiveChatPropsListViewDelegate, QSMPVideoPlayerLayerViewControllerDelegate>
{
    QSMPSharedItem *_sharedItem;
    QSBusSystem *_mediaPlayerBusSystem;
    QSMPLayersViewController *_videoPlayerViewController;
    QSVideoPlayerPropsSharedData *_propsSharedData;
    QSMatchLivePropsListData *_propsListData;
    QSFullScreenMatchLivePropsListView *_propsListView;
    NSString *_lastSelectPropsId;
}

@property(copy, nonatomic) NSString *lastSelectPropsId; // @synthesize lastSelectPropsId=_lastSelectPropsId;
@property(retain, nonatomic) QSFullScreenMatchLivePropsListView *propsListView; // @synthesize propsListView=_propsListView;
@property(retain, nonatomic) QSMatchLivePropsListData *propsListData; // @synthesize propsListData=_propsListData;
@property(retain, nonatomic) QSVideoPlayerPropsSharedData *propsSharedData; // @synthesize propsSharedData=_propsSharedData;
@property(nonatomic) __weak QSMPLayersViewController *videoPlayerViewController; // @synthesize videoPlayerViewController=_videoPlayerViewController;
@property(retain, nonatomic) QSBusSystem *mediaPlayerBusSystem; // @synthesize mediaPlayerBusSystem=_mediaPlayerBusSystem;
@property(retain, nonatomic) QSMPSharedItem *sharedItem; // @synthesize sharedItem=_sharedItem;
- (void).cxx_destruct;
- (void)userChanged;
- (void)needLogin;
- (void)goToBuyKb;
- (_Bool)purchaseIsBusy;
- (_Bool)shouldReceiveTouchEventsWithPoint:(struct CGPoint)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setSharedData:(id)arg1;
- (void)didConsumeEventFromBus:(id)arg1;
- (void)httpData:(id)arg1 didFinishWithError:(id)arg2;
- (void)buyKCoinClickedInView:(id)arg1;
- (void)walletClickedInView:(id)arg1;
- (void)buyButtonClickedInView:(id)arg1 propsItemIsSelected:(id)arg2;
- (void)hidePropsListView;
- (void)startPropsListDataWithDefaultPropsId:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=isPlayerMuted) _Bool playerMuted;
@property(readonly) Class superclass;

@end

