//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class QSWatchMatchTicketExchangeListInfoAd, QSWatchMatchTicketExchangeListInfoBalance;

__attribute__((visibility("hidden")))
@interface QSWatchMatchTicketExchangeListInfo : QSModel
{
    unsigned long long _rate;
    unsigned long long _limit;
    QSWatchMatchTicketExchangeListInfoBalance *_balance;
    QSWatchMatchTicketExchangeListInfoAd *_ad;
}

@property(retain, nonatomic) QSWatchMatchTicketExchangeListInfoAd *ad; // @synthesize ad=_ad;
@property(retain, nonatomic) QSWatchMatchTicketExchangeListInfoBalance *balance; // @synthesize balance=_balance;
@property(nonatomic) unsigned long long limit; // @synthesize limit=_limit;
@property(nonatomic) unsigned long long rate; // @synthesize rate=_rate;
- (void).cxx_destruct;

@end

