//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSWatchMatchTicketExchangeCell.h"

#import "QSWatchMatchTicketExchangeCellDelegate-Protocol.h"

@class NSString, QSAddSubtractCounter, UILabel;
@protocol QSWatchMatchTicketExchangeAmountCellDelegate;

__attribute__((visibility("hidden")))
@interface QSWatchMatchTicketExchangeAmountCell : QSWatchMatchTicketExchangeCell <QSWatchMatchTicketExchangeCellDelegate>
{
    unsigned long long _watchMatchTickets;
    unsigned long long _minWatchMatchTickets;
    unsigned long long _maxWatchMatchTickets;
    id <QSWatchMatchTicketExchangeAmountCellDelegate> _delegate;
    UILabel *_titleLabel;
    QSAddSubtractCounter *_addSubtractCounter;
}

+ (id)getReuseIdentifier;
@property(retain, nonatomic) QSAddSubtractCounter *addSubtractCounter; // @synthesize addSubtractCounter=_addSubtractCounter;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <QSWatchMatchTicketExchangeAmountCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long maxWatchMatchTickets; // @synthesize maxWatchMatchTickets=_maxWatchMatchTickets;
@property(nonatomic) unsigned long long minWatchMatchTickets; // @synthesize minWatchMatchTickets=_minWatchMatchTickets;
@property(nonatomic) unsigned long long watchMatchTickets; // @synthesize watchMatchTickets=_watchMatchTickets;
- (void).cxx_destruct;
- (void)updateCount:(id)arg1;
- (void)hideKeyboard;
- (void)updateLayout;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

