//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSWatchMatchTicketExchangeCell.h"

#import "QSWatchMatchTicketExchangeCellDelegate-Protocol.h"

@class NSString, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface QSWatchMatchTicketExchangeTotalCell : QSWatchMatchTicketExchangeCell <QSWatchMatchTicketExchangeCellDelegate>
{
    unsigned long long _totalKCoin;
    UILabel *_titleLabel;
    UILabel *_totalKCoinTextLabel;
    UIImageView *_totalKCoinImageView;
}

+ (id)getReuseIdentifier;
@property(retain, nonatomic) UIImageView *totalKCoinImageView; // @synthesize totalKCoinImageView=_totalKCoinImageView;
@property(retain, nonatomic) UILabel *totalKCoinTextLabel; // @synthesize totalKCoinTextLabel=_totalKCoinTextLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) unsigned long long totalKCoin; // @synthesize totalKCoin=_totalKCoin;
- (void).cxx_destruct;
- (void)updateLayout;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

