//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSLinkedNode.h"

@class NSString, QSWeakedLinkedList;

@interface QSWeakedLinkedNode : QSLinkedNode
{
    id _weakedObject;
    QSWeakedLinkedList *_linkedList;
    NSString *_identifier;
}

@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) __weak QSWeakedLinkedList *linkedList; // @synthesize linkedList=_linkedList;
@property(nonatomic) __weak id weakedObject; // @synthesize weakedObject=_weakedObject;
- (void).cxx_destruct;
- (id)object;
- (void)setObject:(id)arg1;
- (id)init;

@end

