//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSWebViewController.h"

#import "QSContainerViewControllerContainedVCProtocol-Protocol.h"
#import "QSPushViewControllerProtocol-Protocol.h"
#import "QSShareKitDelegate-Protocol.h"

@class NSDictionary, NSString, QSAttendTagItem, QSShareButtonInfo, QSWebViewNavbar;

__attribute__((visibility("hidden")))
@interface QSWebViewControllerWithUserInfo : QSWebViewController <QSShareKitDelegate, QSPushViewControllerProtocol, QSContainerViewControllerContainedVCProtocol>
{
    _Bool _hideTopBar;
    _Bool _shouldNotClearCookieWhenDisappear;
    _Bool _useLightStatusBar;
    _Bool _shouldShowDefaultH5RightBtn;
    _Bool _alwaysBright;
    CDUnknownBlockType _dismissBlock;
    CDUnknownBlockType _herfBlock;
    NSString *_rightBtnTitle;
    NSDictionary *_rightBtnJumpData;
    QSAttendTagItem *_tagItem;
    NSString *_rightBtnTagCallBack;
    QSWebViewNavbar *_navbar;
    QSShareButtonInfo *_refreshBtnInfo;
    QSShareButtonInfo *_pasteboardBtnInfo;
    QSShareButtonInfo *_browserBtnInfo;
    NSString *_onShowJscode;
    NSString *_onHideJscode;
}

+ (id)allViewControllerType;
@property(copy, nonatomic) NSString *onHideJscode; // @synthesize onHideJscode=_onHideJscode;
@property(copy, nonatomic) NSString *onShowJscode; // @synthesize onShowJscode=_onShowJscode;
@property(nonatomic) _Bool alwaysBright; // @synthesize alwaysBright=_alwaysBright;
@property(retain, nonatomic) QSShareButtonInfo *browserBtnInfo; // @synthesize browserBtnInfo=_browserBtnInfo;
@property(retain, nonatomic) QSShareButtonInfo *pasteboardBtnInfo; // @synthesize pasteboardBtnInfo=_pasteboardBtnInfo;
@property(retain, nonatomic) QSShareButtonInfo *refreshBtnInfo; // @synthesize refreshBtnInfo=_refreshBtnInfo;
@property(nonatomic) _Bool shouldShowDefaultH5RightBtn; // @synthesize shouldShowDefaultH5RightBtn=_shouldShowDefaultH5RightBtn;
@property(retain, nonatomic) QSWebViewNavbar *navbar; // @synthesize navbar=_navbar;
@property(nonatomic) _Bool useLightStatusBar; // @synthesize useLightStatusBar=_useLightStatusBar;
@property(copy, nonatomic) NSString *rightBtnTagCallBack; // @synthesize rightBtnTagCallBack=_rightBtnTagCallBack;
@property(copy, nonatomic) QSAttendTagItem *tagItem; // @synthesize tagItem=_tagItem;
@property(retain, nonatomic) NSDictionary *rightBtnJumpData; // @synthesize rightBtnJumpData=_rightBtnJumpData;
@property(copy, nonatomic) NSString *rightBtnTitle; // @synthesize rightBtnTitle=_rightBtnTitle;
@property(nonatomic) _Bool shouldNotClearCookieWhenDisappear; // @synthesize shouldNotClearCookieWhenDisappear=_shouldNotClearCookieWhenDisappear;
@property(copy, nonatomic) CDUnknownBlockType herfBlock; // @synthesize herfBlock=_herfBlock;
@property(nonatomic) _Bool hideTopBar; // @synthesize hideTopBar=_hideTopBar;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
- (void).cxx_destruct;
- (id)cookieIdentifier;
- (void)saveCookies;
- (void)openURLWithBrowser;
- (void)copyURL;
- (void)refreshWebView;
- (_Bool)isShareActive;
- (id)externButtonsAfterShareButtons;
- (_Bool)checkAndShowWeixinProgramAlertWhenLeave;
- (_Bool)transitionShouldCancelWithAnimator:(id)arg1;
- (void)closeButtonDidTap:(id)arg1;
- (void)backButtonDidTap:(id)arg1;
- (void)shareButtonDidTap:(id)arg1;
- (_Bool)qsWebView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (_Bool)webViewControllerWithUserInfo:(id)arg1 shouldStartLoadWithRequest:(id)arg2 isSpecialProtocol:(_Bool)arg3;
- (void)startPayReportWithId:(id)arg1 payItem:(id)arg2 offerId:(id)arg3 productId:(id)arg4 pf:(id)arg5 pfKey:(id)arg6 varItem:(id)arg7 error:(id)arg8;
- (id)allParamentsInfoWithRequest:(id)arg1;
- (void)resetTopBarWithColor:(id)arg1;
- (void)jumpDataPressed:(id)arg1;
- (void)updateRightAction;
- (void)appWillResignActive:(id)arg1;
- (void)appDidBecomeActive:(id)arg1;
- (void)appEnterForeground:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithParameters:(id)arg1;
- (id)currentParameters;
- (void)setTitle:(id)arg1;
- (void)updateNavigationBar;
- (_Bool)hideNavbarRightBtn;
- (_Bool)shouldShowSelfDefinedNavigationBar;
- (long long)preferredStatusBarStyle;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

