//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString, QSWinterOlympicCategoryJumpData;

__attribute__((visibility("hidden")))
@interface QSWinterOlympicCategoryItem : QSModel
{
    NSString *_logo;
    NSString *_name;
    QSWinterOlympicCategoryJumpData *_jumpData;
}

@property(retain, nonatomic) QSWinterOlympicCategoryJumpData *jumpData; // @synthesize jumpData=_jumpData;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *logo; // @synthesize logo=_logo;
- (void).cxx_destruct;

@end

