//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString, QSWinterOlympicCategoryParam;

__attribute__((visibility("hidden")))
@interface QSWinterOlympicCategoryJumpData : QSModel
{
    NSString *_type;
    QSWinterOlympicCategoryParam *_param;
}

@property(retain, nonatomic) QSWinterOlympicCategoryParam *param; // @synthesize param=_param;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

