//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSWinterOlyMedalInfoItem : QSModel
{
    NSString *_level;
    NSString *_levelName;
    NSString *_name;
    NSString *_nationality;
}

@property(copy, nonatomic) NSString *nationality; // @synthesize nationality=_nationality;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *levelName; // @synthesize levelName=_levelName;
@property(copy, nonatomic) NSString *level; // @synthesize level=_level;
- (void).cxx_destruct;

@end

