//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSArray, NSString, QSGradientView, UICollectionView;

__attribute__((visibility("hidden")))
@interface QSWorldCupNewsEntranceView : UIView <UICollectionViewDelegateFlowLayout, UICollectionViewDataSource>
{
    double _leftMargin;
    double _rightMargin;
    NSArray *_tabInfos;
    UICollectionView *_collectionView;
    QSGradientView *_leftGradientView;
    QSGradientView *_rightGradientView;
    double _firstTextWidth;
    double _lastTextWidth;
}

@property(nonatomic) double lastTextWidth; // @synthesize lastTextWidth=_lastTextWidth;
@property(nonatomic) double firstTextWidth; // @synthesize firstTextWidth=_firstTextWidth;
@property(retain, nonatomic) QSGradientView *rightGradientView; // @synthesize rightGradientView=_rightGradientView;
@property(retain, nonatomic) QSGradientView *leftGradientView; // @synthesize leftGradientView=_leftGradientView;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSArray *tabInfos; // @synthesize tabInfos=_tabInfos;
@property(nonatomic) double rightMargin; // @synthesize rightMargin=_rightMargin;
@property(nonatomic) double leftMargin; // @synthesize leftMargin=_leftMargin;
- (void).cxx_destruct;
- (void)webImageViewDidFinishLoading:(id)arg1 inCell:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateCollectionViewContentInset;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

