//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class QSHomeRecommendWordCupMenuItem, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface QSWorldCupNewsEntranceItemCell : UICollectionViewCell
{
    _Bool _isLast;
    UILabel *_titleLabel;
    UIImageView *_imageView;
    UIImageView *_roundSeparatorView;
    QSHomeRecommendWordCupMenuItem *_model;
}

@property(nonatomic) _Bool isLast; // @synthesize isLast=_isLast;
@property(retain, nonatomic) QSHomeRecommendWordCupMenuItem *model; // @synthesize model=_model;
@property(retain, nonatomic) UIImageView *roundSeparatorView; // @synthesize roundSeparatorView=_roundSeparatorView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)updateWithModel:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

