//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSData, NSRecursiveLock, NSString, QSMemSig, WloginSdk_v2, WloginUserInfo;
@protocol QSWTLoginDelegate;

__attribute__((visibility("hidden")))
@interface QSWTLogin : NSObject
{
    id <QSWTLoginDelegate> _delegate;
    WloginSdk_v2 *_g_loginSdk;
    WloginUserInfo *_userInfo;
    QSMemSig *_lskeySig;
    QSMemSig *_skeySig;
    NSRecursiveLock *_lock;
    NSString *_userInputName;
    NSString *_userInputPassword;
}

@property(retain, nonatomic) NSString *userInputPassword; // @synthesize userInputPassword=_userInputPassword;
@property(retain, nonatomic) NSString *userInputName; // @synthesize userInputName=_userInputName;
@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) QSMemSig *skeySig; // @synthesize skeySig=_skeySig;
@property(retain, nonatomic) QSMemSig *lskeySig; // @synthesize lskeySig=_lskeySig;
@property(retain, nonatomic) WloginUserInfo *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) WloginSdk_v2 *g_loginSdk; // @synthesize g_loginSdk=_g_loginSdk;
@property(nonatomic) __weak id <QSWTLoginDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)loginFailed_v2:(id)arg1 andRst:(int)arg2 withErrInfo:(id)arg3 tag:(long long)arg4;
- (void)loginSuccessSig_v2:(id)arg1 andSig:(id)arg2 andBaseInfo:(id)arg3 tag:(long long)arg4;
- (_Bool)handleQuickLoginURL:(id)arg1 result:(_Bool *)arg2;
- (void)quickLogin;
- (void)refresh;
- (void)logOut;
@property(readonly, nonatomic) NSArray *cookies; // @dynamic cookies;
@property(readonly, nonatomic) NSString *lastLoginQQ; // @dynamic lastLoginQQ;
@property(readonly, nonatomic) NSData *skeyData; // @dynamic skeyData;
@property(readonly, nonatomic) NSData *lskeyData;
@property(readonly, nonatomic) NSString *qq; // @dynamic qq;
@property(readonly, nonatomic) _Bool isLoggedIn; // @dynamic isLoggedIn;
@property(readonly, nonatomic) _Bool needUpdateLoginStatus; // @dynamic needUpdateLoginStatus;
- (void)setSigArray:(id)arg1 andUserInfo:(id)arg2;
- (void)loginCheck;
- (id)init;
- (id)appVersion;

@end

