//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class QSMatchDetailZhiBoGoalsItem, UILabel;

__attribute__((visibility("hidden")))
@interface QSZhiBoGoalsCell : UITableViewCell
{
    UILabel *_leftGoal;
    UILabel *_rightGoal;
    UILabel *_titleLabel;
    _Bool _firstRow;
    QSMatchDetailZhiBoGoalsItem *_item;
}

+ (double)height;
@property(nonatomic) _Bool firstRow; // @synthesize firstRow=_firstRow;
@property(retain, nonatomic) QSMatchDetailZhiBoGoalsItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)update;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

