//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TADReportBase-Protocol.h"

@class CTTelephonyNetworkInfo, NSMutableDictionary, NSRecursiveLock, NSString;

@interface TADUserInfo : NSObject <TADReportBase>
{
    NSString *_pu;
    NSString *_mid;
    NSString *_userQQ;
    NSString *_deviceToken;
    NSString *_requestId;
    NSString *_pf;
    NSString *_radioATG;
    NSString *_uin;
    NSString *_skey;
    NSString *_guid;
    NSString *_openid;
    NSString *_userWXNewsOpenID;
    NSString *_customUserAgent;
    unsigned long long _activeSource;
    NSString *_latitude;
    NSString *_longitude;
    NSString *_city;
    NSString *_street;
    NSString *_omgid;
    NSString *_omgbizid;
    double _lbsTimestamp;
    NSMutableDictionary *_userInfo;
    NSRecursiveLock *_userInfoLock;
    NSString *_openUDID;
    NSString *_netStatus;
    NSString *_mobileNetworkCode;
    CTTelephonyNetworkInfo *_telephonyInfo;
}

+ (id)radioATGeneration:(id)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) CTTelephonyNetworkInfo *telephonyInfo; // @synthesize telephonyInfo=_telephonyInfo;
@property(retain, nonatomic) NSString *mobileNetworkCode; // @synthesize mobileNetworkCode=_mobileNetworkCode;
@property(copy, nonatomic) NSString *netStatus; // @synthesize netStatus=_netStatus;
@property(copy, nonatomic) NSString *openUDID; // @synthesize openUDID=_openUDID;
@property(retain, nonatomic) NSRecursiveLock *userInfoLock; // @synthesize userInfoLock=_userInfoLock;
@property(retain, nonatomic) NSMutableDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) double lbsTimestamp; // @synthesize lbsTimestamp=_lbsTimestamp;
@property(copy, nonatomic) NSString *omgbizid; // @synthesize omgbizid=_omgbizid;
@property(copy, nonatomic) NSString *omgid; // @synthesize omgid=_omgid;
@property(copy, nonatomic) NSString *street; // @synthesize street=_street;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(copy, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(copy, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(nonatomic) unsigned long long activeSource; // @synthesize activeSource=_activeSource;
@property(copy, nonatomic) NSString *customUserAgent; // @synthesize customUserAgent=_customUserAgent;
@property(copy, nonatomic) NSString *userWXNewsOpenID; // @synthesize userWXNewsOpenID=_userWXNewsOpenID;
@property(copy, nonatomic) NSString *openid; // @synthesize openid=_openid;
@property(copy, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(copy, nonatomic) NSString *skey; // @synthesize skey=_skey;
@property(copy, nonatomic) NSString *uin; // @synthesize uin=_uin;
@property(copy, nonatomic) NSString *radioATG; // @synthesize radioATG=_radioATG;
@property(copy, nonatomic) NSString *pf; // @synthesize pf=_pf;
@property(copy, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
@property(copy, nonatomic) NSString *deviceToken; // @synthesize deviceToken=_deviceToken;
@property(copy, nonatomic) NSString *userQQ; // @synthesize userQQ=_userQQ;
@property(copy, nonatomic) NSString *mid; // @synthesize mid=_mid;
@property(copy, nonatomic) NSString *pu; // @synthesize pu=_pu;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)dataDictWithKey;
@property(readonly, nonatomic) NSString *applicationState;
@property(readonly, nonatomic) long long clientCode;
@property(readonly, copy, nonatomic) NSString *sdkVersion;
@property(readonly, nonatomic) NSString *appVersion;
- (id)identifierForVendor;
@property(readonly, nonatomic) NSString *advertisingIdentifier;
@property(readonly, nonatomic) NSString *macAddress;
- (id)screenResolution;
- (_Bool)isPadPro;
- (_Bool)isPadMini;
- (id)screenSize;
- (id)encodeData:(id)arg1;
@property(readonly, nonatomic) NSString *appName;
- (id)appShortVersion;
- (id)appBundleName;
- (id)osversion;
- (void)handleCTRadioAccessTechnologyDidChangeNotification;
- (void)handleReachabilityChangeNotification;
@property(readonly, nonatomic) NSString *encodeUserData;
- (_Bool)shouldFreqControl;
- (void)syncUserInfo:(id)arg1;
- (void)setWiFiNameAndRouterMacAddress;
- (void)p_initUserInfo;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

