//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, TADVideoViewController;

@protocol TADVideoViewControllerDelegate <NSObject>
- (void)adPlayFailed:(TADVideoViewController *)arg1 error:(NSError *)arg2;
- (void)adPlayDidFinish:(TADVideoViewController *)arg1;
- (void)adPlayReady:(TADVideoViewController *)arg1;

@optional
- (_Bool)adPlayViewisRotating:(TADVideoViewController *)arg1;
- (void)adLandingViewDidDismiss:(TADVideoViewController *)arg1;
- (void)adLandingViewWillPresent:(TADVideoViewController *)arg1;
- (void)adPlayVipClick:(TADVideoViewController *)arg1;
- (void)adPlayExpand:(TADVideoViewController *)arg1 fullScreen:(_Bool)arg2;
- (void)adPlayWillFinish:(TADVideoViewController *)arg1;
@end

