//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "QSNavigationInteractiveTransitionProtocal-Protocol.h"

@class NSString, QSNavigationController;

@interface UIViewController (QSNavigationController) <QSNavigationInteractiveTransitionProtocal>
- (void)finishTransitionWithAnimator:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)cancelTransitionWithCompletion:(CDUnknownBlockType)arg1;
- (void)updateTransition:(double)arg1;
- (void)startTransitionWithAnimator:(id)arg1;
- (_Bool)transitionGestureRecognizerShouldBegin:(id)arg1;
- (id)animatorWithOperation:(long long)arg1 withGesture:(id)arg2;
- (_Bool)transitionShouldCancelWithAnimator:(id)arg1;
- (void)transitionDidFinishWithAnimator:(id)arg1;
- (void)transitionWillStartWithAnimator:(id)arg1;
- (void)updateAnimator:(id)arg1;
@property(readonly, nonatomic) QSNavigationController *customNavigationController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

