//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIWindow, UnityAppController;

__attribute__((visibility("hidden")))
@interface UnityManager : NSObject
{
    int _cachedArgc;
    UIWindow *_unityWindow;
    UnityAppController *_unityController;
    char **_cachedArgv;
}

+ (id)shareManager;
@property(nonatomic) char **cachedArgv; // @synthesize cachedArgv=_cachedArgv;
@property(nonatomic) int cachedArgc; // @synthesize cachedArgc=_cachedArgc;
@property(retain, nonatomic) UnityAppController *unityController; // @synthesize unityController=_unityController;
@property(retain, nonatomic) UIWindow *unityWindow; // @synthesize unityWindow=_unityWindow;
- (void).cxx_destruct;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)didFinishLaunching:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (_Bool)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)unregistNotificationEvents;
- (void)registNotificationEvents;
- (void)setInterfaceOrientation:(long long)arg1;
- (void)cacheArgs:(int)arg1 argv:(char **)arg2;
- (void)unloadUnity3D;
- (void)startUnity3D;
- (void)showUnitySence;
- (void)loadUnity3DWithARSourceUrl:(id)arg1 ARMusicUrl:(id)arg2;
- (void)hideUnityWindow;
- (void)showUnityWindow;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;

@end

